### ISSUE TITLE
outline levels collapse after changing a heading level

### ISSUE THREAD

**Issue by jechlin** [asciidocfx/AsciidocFX#100]
Would be nice if it remembered what nodes were open in the outline, and didn't collapse them all. As it is it's not very useful, although it could be.

**Comment by ozlerhakan** [comment]
This was done 2 days ago ([setAutoExpand true for outline(https://github.com/asciidocfx/AsciidocFX/commit/815b32cf702129f209e3d65418a4a4906ea37543)) in the master and it will be available for the RC2 (I guess so).

**Comment by jechlin-test** [comment]
Thanks - all expanded is fine for me, although I can imagine some people would prefer it just maintained the open/closed state for each node, particularly if you have a very large tree.

**Comment by rahmanusta** [comment]
@jechlin-test , please try RC2 Please try https://github.com/asciidocfx/AsciidocFX/releases

**Comment by rahmanusta** [comment]
@jechlin  Can you try RC6 ? https://github.com/asciidocfx/AsciidocFX#how-to-install-asciidocfx
