### ISSUE TITLE
The render principle of the numbered list property

### ISSUE THREAD

**Issue by hakdogan** [asciidocfx/AsciidocFX#101]
When text is entered under numbered list, numbering starts from 1 again.

For example:

1. clause 
bla bla bla bla

2. clause
bla bla bla bla

As the output of the above syntax

1. clause bla bla bla bla

2. clause bla bla bla bla

To me, this is a problem. Let's get to the point.

1. clause 

bla bla bla bla

2. clause

bla bla bla bla

As the output of the above syntax

1. clause

bla bla bla bla

1. clause

bla bla bla bla

If you ask me, this is more bigger problem.
![screen shot 2015-07-16 at 00 03 58](https://cloud.githubusercontent.com/assets/657846/8709910/8031bd1c-2b4e-11e5-9024-c35d9255b0be.png)
![screen shot 2015-07-16 at 00 03 51](https://cloud.githubusercontent.com/assets/657846/8709914/897948ea-2b4e-11e5-86d0-95db1ac50f2b.png)

**Comment by hakdogan** [comment]
Interesting. GitHub editor behaved the same :)
![screen shot 2015-07-16 at 00 11 38](https://cloud.githubusercontent.com/assets/657846/8710051/84e4040e-2b4f-11e5-8fa6-aa7d3da1e265.png)
![screen shot 2015-07-16 at 00 11 51](https://cloud.githubusercontent.com/assets/657846/8710054/8c4bf594-2b4f-11e5-87dd-e97b3a53e3ad.png)

**Comment by rahmanusta** [comment]
Dear @hakdogan abi;

You can try like below?;

```asciidoc
1. List 1

+
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eu odio nisl.
+

2. List 2

+
Mauris scelerisque vel turpis vel feugiat. Suspendisse semper ex vestibulum sem vulputate egestas.
+

3. List 3

+
Donec accumsan augue vitae tortor efficitur imperdiet. Nullam ultrices nibh purus, mattis accumsan sem efficitur at.
+
```

**Comment by hakdogan** [comment]
Thansk a lot @rahmanusta 

It works...
