### ISSUE TITLE
Font rendering of text elements is not as expected

### ISSUE THREAD

**Issue by phayz** [asciidocfx/AsciidocFX#102]
The font rendering of text elements in AsciidocFX doesn't look like the native font rendering. I have tried several configuration options in the 'AsciidocFX.vmoptions' file, including those below, but the font rendering does not change.

To illustrate the issue I have included two screenshots, one which shows gedit and next to it, Firefox with a rendered AsciiDoc file, and another which shows the same file as rendered by AsciidocFX.

Environment:
Fedora 21, 64-bit (Running GNOME)

I have also tested this on Linux Mint 17.2 (64-bit), but on different hardware, and the issue is the same.

Configuration options tested:
-Dprism.lcdtext=true
-Dprism.text=t2k

![asciidocfx](https://cloud.githubusercontent.com/assets/438816/8711374/b887abae-2b94-11e5-86e4-e71039192840.png)
![gedit_and_firefox](https://cloud.githubusercontent.com/assets/438816/8711377/b9f45cf8-2b94-11e5-904b-13723499216f.png)

**Comment by rahmanusta** [comment]
It is about CSS. We customized default stylesheet a little bit.

**Comment by phayz** [comment]
OK, thanks. Can I examine the CSS and do some testing with different fonts?

**Comment by rahmanusta** [comment]
@phayz You can edit or change default stylesheet in RC5 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.3.7-RC5 .Can you try it ? Press F4 to edit.

**Comment by rahmanusta** [comment]
@phayz  Can you try RC6 ? https://github.com/asciidocfx/AsciidocFX#how-to-install-asciidocfx You can change default css or edit it in Settings page (Press F4)
