### ISSUE TITLE
support variables in includes

### ISSUE THREAD

**Issue by jechlin** [asciidocfx/AsciidocFX#103]
Typically we include files like this:

[source,java]
----
include::{projectdir}/src/test/resources/RemainingWorkInLinkedIssues.groovy[]
----
The important part of this *projectdir*, which is a variable pointing to the root of the project. 
We could use fully relative paths, but the problem then is you can't easily move the doc up or down a level.

projectdir is set in *_config.yml*, the main jekyll config file.

I would like to be able to set projectdir in asciidocfx to an absolute path, so it can resolve these include files. Perhaps in a dialog, but a system property or config file would be more than fine.

**Comment by rahmanusta** [comment]
For example, it works;

```asciidoc
:projectdir: C:\Users\usta\Dropbox\AsciidocFX


[source,yaml]
----
include::{projectdir}\conf\config.yml[]
----

```

**Comment by jechlin** [comment]
Ah, that does work... but I'd have to define it in each file, and then there's the risk of leaving that committed, and then my CI site build would break. 

I would like to set it as a transient property, because it's different for everyone working on the docs, depending on where their git checkout is.

**Comment by rahmanusta** [comment]
Maybe you can use conditinitoal ifs;

```asciidoc
ifdef::env-browser[]
:projectdir: C:\Users\usta\Dropbox\AsciidocFX
endif::env-browser[]


[source,yaml]
----
include::{projectdir}\conf\config.yml[]
----
```

In this example, if your build environment is browser, asciidofx it will set projectdir property, if not it will use the property from your build environment.

**Comment by jechlin** [comment]
That would help, but seems like there must be a better solution than every user adding that to every page.

**Comment by rahmanusta** [comment]
You are right. This is a need. We will implement it via config files.

**Comment by jechlin** [comment]
Many thanks. I am looking forward to it. 

I started trying to add it myself, but I didn't realise that the actual rendering is done through javascript, and it's already minified in the the source distro. At that point I got a bit stuck.

**Comment by rahmanusta** [comment]
@jechlin please try RC4 and press F4 to show settings. There is Asciidoctor settings. You can set global attributes on there.

**Comment by jechlin** [comment]
Thanks - I can't see to edit a new property. I am doing it in the Preview attributes panel.

![image](https://cloud.githubusercontent.com/assets/1714400/8932334/68fe7096-3534-11e5-8632-8d1102665dd5.png)

When I click in the grey area on the right to set the value the left side disappears.

**Comment by rahmanusta** [comment]
Edit and press enter

**Comment by jechlin** [comment]
As a windows user that's not intuitive, but yep.

That works perfectly, thanks a lot.

**Comment by rahmanusta** [comment]
Sure, this is default behaviour of JavaFx TableView, but we can do that more intuitive.
