### ISSUE TITLE
Drag outline items, images and tables into document as links

### ISSUE THREAD

**Issue by shawngiese** [asciidocfx/AsciidocFX#104]
Just an enhancement I would love to see. Some of my documents get big and are spread across multiple files.

**Comment by rahmanusta** [comment]
@shawngiese Thanks for your suggestion, but I did not understand it :) Can you give more details for your idea?

**Comment by shawngiese** [comment]
Already, from the outline you get a list of all parts of your document, well of the single document (not of a book it seems). What I would like would be the ability to drag an item from the outline, into the text, and that it will appear a link in the text. Currently I can drag a folder into my document and it appears in the file tree markup. The same for images... I can drag one into the document and something like image::images/image2993.png[] appears. Something similar for links to a part of the document would be nice.

**Comment by rahmanusta** [comment]
@ozlerhakan I didnt understand exactly, did you understand the feature request?

**Comment by ozlerhakan** [comment]
I am not sure @rahmanusta as well. I am guessing now, you can refer a file into another file. More clearly, you can drag a file into an asiidoc file that will use the include directive and appear like this (assuming that your adoc file name is example.adoc):

example.adoc:
```
include::anotherdocfile.adoc[]
```

that feature is good if your documents are spread across multiple files. Is that what you suggest us, @shawngiese ?

**Comment by shawngiese** [comment]
Yes, it is especially nice when there are multiple files, but also useful when you have a section in a long document and want to link to it... such as "For more information about xxx see yyy". Across multiple files would also require an enhancement to the outline to scan for section titles in the files of the same folder... so maybe just from a single file's outline could be a good start.
