### ISSUE TITLE
Folder contexts go missing after light navigation (RC2)

### ISSUE THREAD

**Issue by takapa** [asciidocfx/AsciidocFX#106]
After changing folders 3 or 4 times, the folder contents go missing.

This appears to be a new bug in RC2. The below animated gif was made immediately after a fresh restart of AsciiDocFX 1.3.7 RC2.

Prior to encountering this bug, I had added a favourite directory (see previous bug report). Not sure if adding a favourite directory was a trigger for this bug or not, but this happens every time I load RC2 now, so it is impossible to navigate to my working folder without triggering the bug meaning I have to go back to RC1.

![asciidoc_bug](https://cloud.githubusercontent.com/assets/201870/8759134/14c1439c-2ce6-11e5-88a1-9f1e11e63101.gif)

**Comment by rahmanusta** [comment]
Yes this is a bug @takapa , I pushed RC3, it will be available to download in 10 minutes. Can you try it ?

**Comment by takapa** [comment]
I confirm this is fixed in RC3.
