### ISSUE TITLE
Favourite folders are forgotten when AsciidocFX is closed and then opened again.

### ISSUE THREAD

**Issue by takapa** [asciidocfx/AsciidocFX#108]
Favourite folders are forgotten when AsciidocFX is closed and then opened again.

**Comment by rahmanusta** [comment]
Do you have write permission to installdir ?

**Comment by talios** [comment]
Writing the `./conf` directory to the install dir seems rather problematic, the OSX .dmg installer installs into the global `/Applications` folder by default, which isn't user writable. This is also somewhat problematic if running from a build - `mvn clean install` deletes the `conf` dir under `target`.

Would it not be better to store the config in the users home dir?

**Comment by rahmanusta** [comment]
No, you will not use maven with installer. Can you give mi more detail for your installation + running path ?

**Comment by takapa** [comment]
Hi,

I tried this out in admin mode and yes, the favourites folders are stored, but ONLY if I start AsciiDocFX in admin mode (in Windows holding Ctrl+Shift as a click the application icon). Obviously, this is not a workable solution because a documentation application should not require admin rights from a security standpoint and of course, it's extremely un-user-friendly.

So - I still list this as an issue. Config settings should not require admin permissions to save. I guess storing settings underneath the ~user/username/.asciidocfx/settings folder is probably the correct solution (that's the approach I use in my own applications).

**Comment by rahmanusta** [comment]
@takapa Can you try latest prerelease ? https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.3.7-RC5

**Comment by takapa** [comment]
I updated to 1.3.7-RC5 and it seems not fixed.

I tried the latest pre-release, and I did NOT start AsciiDocFX as admin.

I added two favourite folders, then I closed the program, then I re-opened AsciiDocFX (without admin again), and the favourite folders were gone.

**Comment by rahmanusta** [comment]
@takapa  Could you try to run it with sudo for first time only ?

**Comment by takapa** [comment]
OK, tried RC5 (new build).

If I start ADFX in sudo/admin mode, and I create a favourite directory, then if I restart the application in user mode (not admin), then the favourite folder is retrieved correctly.

If however I start ADFX in user mode, make a favourite folder, then the favourite folder is not retrieved upon restart of the application. It seems that changes cannot be saved unless in admin mode still..

**Comment by rahmanusta** [comment]
@takapa conf directory must be writable to record configurations. Your suggested folder in user home is best to get over this issue. We can implement it in further releases. But, for now, if you start the application for one time with admin permissions, AsciidocFX will automatically give write permissions to /conf folder. Let'us look at the code. https://github.com/asciidocfx/AsciidocFX/blob/master/src/main/java/com/kodcu/controller/ApplicationController.java#L985

**Comment by takapa** [comment]
I understand the logic, but this doesn't work on Windows - based on my own
test results.

It doesn't matter if I run in admin mode once or not, if I don't run in
admin mode in subsequent times then it doesn't update the config.

**Comment by rahmanusta** [comment]
But, I think It is easy to give write permission to application directory

**Comment by talios** [comment]
@rahmanusta Mmm, Having ApplicationController grant full read/write/execute permissions to that folder seems rather nasty - sure I like the idea of applications granting _everyone_ execute permissions etc.

**Comment by rahmanusta** [comment]
@talios I'm open to a pull request

**Comment by stallio** [comment]
+1 for putting config stuff in user's home folder. 

I was confused about why I couldn't make any config changes -- it was because I didn't have write permissions in the conf folder. I had to manually change my folder permissions, which is not a good solution.

On Windows, programs are installed in /Program Files by default and those folders require admin permissions by default. (I'm running RC5 on win 8.1.)

**Comment by rahmanusta** [comment]
@stallio We will solve this issue by moving config files to a writable folder in user's home

**Comment by rahmanusta** [comment]
@takapa  @stallio  @talios Can you try RC6 ? https://github.com/asciidocfx/AsciidocFX#how-to-install-asciidocfx
