### ISSUE TITLE
Feature request: Word wrap in the editor

### ISSUE THREAD

**Issue by takapa** [asciidocfx/AsciidocFX#109]
I use the ":hardbreaks:" setting in my documents which means that I don't manually use linefeeds in the middle of paragraphs to stay in some arbitary screen width limit. That said, I depend upon word wrap so I can keep track of where I am in the document. Long lines should be wrapped around in the .asciidoc source file.

I can see you use Ace Editor as the underlying editor technology. Please can you expose a toggle in the editor window to toggle on the Ace editor API setting "EditSession.setUseWrapMode(Boolean useWrapMode)".

I know the workaround is not using ":hardbreaks:" setting and manually using linefeeds, and in this case that asciidoc will ignore single linebreaks and append fragments of the current paragraph together, but I require ":hardbreaks:" so that I can insert carriage return characters into table cells.

A word wrap toggle either on the menu or submenu should hopefully be fairly trivial to implement given Ace already supports it.

NOTE: Horizontal scrollbar should also be enabled for the editor panel as when I type off the edge of the editor, I lose my cursor. AceEditor.Renderer.setHScrollBarAlwaysVisible() might be useful.

**Comment by rahmanusta** [comment]
@takapa Please try RC4 and press F4 to show settings. Can you test and give feedbacks?

**Comment by rahmanusta** [comment]
@takapa Did you try that?

**Comment by takapa** [comment]
Hi,

Yes, I tried this, and it does work.
