### ISSUE TITLE
App window closes after startup on Mac

### ISSUE THREAD

**Issue by michael1maass** [asciidocfx/AsciidocFX#110]
V 1.3.7 rc3 
MAC OS X.10.10.4 

after Update from 1.3.6 Asciidoc Fx starts, runs the update and then closes the main window. While the Icon remains active in the dock and the Taskbar shows the program title, the Workplace window is closed and does not come back. 

only option is to close the program. 

Michael

**Comment by rahmanusta** [comment]
Can you share a screen recording?

**Comment by michael1maass** [comment]
on the way via pm

**Comment by rahmanusta** [comment]
Michael, why did you close this issue?

**Comment by michael1maass** [comment]
i messed it up by clicking the false link

**Comment by michael1maass** [comment]
tried it again from scratch. 1.3.6. works fine. Do the update and the main screen does not even appear. 
regards

Michael
