### ISSUE TITLE
Multiple bugs with reveal.js backend

### ISSUE THREAD

**Issue by Zlika** [asciidocfx/AsciidocFX#113]
Hello,

I tried to use the reveal.js backend with AsciidocFX 1.3.7-RC3 and I found multiple bugs with it (some of them are also present with the Deck.js backend, but not all). These bugs are not present when I directly render the slides with Asciidoctor 1.5.2 + latest version of reveal.js backend + reveal.js 3.1.0.

* Title slide is not rendered.
* Inline images (image:img.jpeg[]) are not rendered.
* The following table attributes are not taken into account: frame, grid
* When I use a table with 1 row and 2 columns and I put one block image inside each cell, the table does not take into account the size of the images to size itself.

Regards,
Thomas

**Comment by rahmanusta** [comment]
@Zlika Can you try the latest prerelease ? https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.3.7-RC5

**Comment by Zlika** [comment]
Hi @rahmanusta,
I tested the RC5 release with reveal.js backend. It's much better, but there are still some problems:
* The title slide is still not rendered.
* There is a glitch in the preview window with slide titles, only the first left half is displayed (in fact we can read the full title when the slide rotates, but as soon as the slide is still the right part of the title disappears).
* On one of my slides I have a table with 3 lines, with images or text in the cells: only the first row is rendered.
* Asciidoc definitions (with syntax "::") are not rendered.
* I can see the following warning in the logs: DEBUG => revealjsExt is not found while flipping page, but don't worry. (For info, I use reveal.js v3.1.0).
* There is HTML code in code blocks (<span class=...)!
* Moving from one slide to another is extremely slow (something like 2s!)

**Comment by rahmanusta** [comment]
> The title slide is still not rendered.

By default, in asciidoctor template first level title shows in <title> tag. In jade templates that was not impelemented. I updated it. Does it work for you?

> There is a glitch in the preview window with slide titles, only the first left half is displayed (in fact we can read the full title when the slide rotates, but as soon as the slide is still the right part of the title disappears).

I faced with your problem, I didnt found real cause of it, it may be cause with JavaFX or preview window's width.

> On one of my slides I have a table with 3 lines, with images or text in the cells: only the first row is rendered.

> I didnt see any problem in my work, can you share a screenshot with me ?

dlist template is not implemented. I will do that.

> I can see the following warning in the logs: DEBUG => revealjsExt is not found while flipping page, but don't worry. (For info, I use reveal.js v3.1.0).

Dont worry for that, it is transient issue

> There is HTML code in code blocks (<span class=...)!

I didnt solve this issue yet.

> Moving from one slide to another is extremely slow (something like 2s!)

It is interesting, which version of Java are you using ?

**Comment by Zlika** [comment]
Thank you for your answers.

> By default, in asciidoctor template first level title shows in title tag. In jade templates that was not impelemented. I updated it. Does it work for you?

When I use AsciiDoctor to render my slides, the title slide is correctly rendered, so I don't know who is right but this is not consistent with the Asciidoctor Ruby implementation. Moreover, when I click on "Browser", the generated presentation has: `<title>Slaytshow</title>`.

> I didnt see any problem in my work, can you share a screenshot with me ?

Try something like:
```
[cols=".^1,.^2",width="100%",frame="none",grid="none"]
|====================
| image:https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/2000px-Tux.svg.png[width=150] | Line 1
|====================
[cols=".^1a,.^2a",width="100%",frame="none",grid="none"]
|====================
| image:https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/2000px-Tux.svg.png[width=150] | Line 2
|====================
[cols=".^1a,.^2a",width="100%",frame="none",grid="none"]
|====================
| image:https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/2000px-Tux.svg.png[width=150] | Line 3
|====================
```
It's correctly rendered with Asciidoctor, but not with AsciiDocFX (both with reveal.js backend).

> It is interesting, which version of Java are you using ?

The one bundled with the RC release (I cannot make AsciidocFX use the installed Java 8 version on my computer. I have the same problem on both Windows and Linux. So I directly use the versions with a bundled JRE). Also, AsciiDocFX uses more than 300MB of memory just at the beginning, without any document in the editor, and it reachs more than 600MB with my simple and short (18 slides) presentation. That's a lot!

**Comment by rahmanusta** [comment]
>When I use AsciiDoctor to render my slides, the title slide is correctly rendered, so I don't know who is right but this is not consistent with the Asciidoctor Ruby implementation. Moreover, when I click on "Browser", the generated presentation has: &lt;title&gt;Slaytshow&lt;/title&gt;

It will be available in further pre-release

>Table issue

Yes, it seems not correctly rendered. It works with deckjs backend but not with revealjs for now. It will be available in further pre-release

>Performance issue

Default Xmx is 1GB so that AsciidocFX may use all of it. You can try to limit Xmx to for example 512 mb. Just edit AsciidocFX.vmoptions in installation directory.

>Slowness

Can you record a short video for that? Can we make a teamviewer session ?

**Comment by Zlika** [comment]
What is really slow is the preview in the browser (with the URL http://localhost:49605/slide/index.slide#/). I don't remember it was so slow in the previous RC I tested, and of course it is not slow at all when using the same browser (Firefox) to display the final presentation generated by AsciiDoctor.

**Comment by rahmanusta** [comment]
If slowness is only on external browser, this problem is not about AsciidocFX. What about in embedded preview ? Can you create your slide template with New > Slide menu ?

**Comment by Zlika** [comment]
I don't have the problem if I create a new slide from New > Slide menu, so it must be something related to my slides. However, I don't understand why my presentation is so slow with the "external" browser ONLY when the browser is launched from AsciidocFX. If I generate my presentation with asciidoc + reveal.js backend and open it with Firefox everything is fine. You must do something special with AsciidocFX to "stream" the presentation to the browser with your own server at localhost:49605.

**Comment by rahmanusta** [comment]
Could you send me a sample project that has that problem ?

**Comment by Zlika** [comment]
I'll try to do that when I come back from hollidays.

**Comment by rahmanusta** [comment]
@Zlika Can you try RC6 ? https://github.com/asciidocfx/AsciidocFX/releases

Also, in  [cols=".^1a,.^2a",width="100%",frame="none",grid="none"] if you remove "a" from "^1a" and "^2a" output will be normal. I didn't find the cause yet, but there is a bug/problem with "a"
