### ISSUE TITLE
Book Cover Feature

### ISSUE THREAD

**Issue by cortix** [asciidocfx/AsciidocFX#114]
Hi all,

I want add book cover to my pdf..If you add this feature next couple days, it would be great !!

**Comment by nelruk** [comment]
Add cover not only for pdf but also for epub3

**Comment by shawngiese** [comment]
Can't you just add a custom XSL into your docbook workflow and then the docinfo.xml addition to put your cover info?

**Comment by life888888** [comment]
AsciidocFX 1.8.1

**Cover page image**

- add `:front-cover-image: image:front-cover.png[]`

https://docs.asciidoctor.org/epub3-converter/latest/



**Title Page Image**

- add `:title-page-background-image: image:title-bg.png[]`

https://docs.asciidoctor.org/pdf-converter/2.1/title-page/

**Logo Image**
- add `:title-logo-image: image:logo.png[top=25%,align=center,pdfwidth=0.5in]`

https://docs.asciidoctor.org/pdf-converter/2.1/title-page/


```adoc
= Book Name
Author Name
:doctype: book
:encoding: utf-8
:lang: en
:toc: left
:toclevels: 2
:numbered:
:showtitle:
//https://github.com/asciidocfx/AsciidocFX/issues/130
//https://github.com/asciidocfx/AsciidocFX/issues/114
//FRONT COVER PAGE
//PURE IMAGE PAGE ONLY, BEFORE TITLE PAGE
:front-cover-image: image:front-cover.png[]
//TITLE PAGE
:title-page:
//ADD IMAGE IN TITLE PAGE 
:title-page-background-image: image:title-bg.png[]
//:title-logo-image: image:logo.png[top=25%,align=center,pdfwidth=0.5in]
```
3 image in images dir

- front-cover.png
- title-bg.png[
- logo.png

Example PDF 
[book.pdf](https://github.com/asciidocfx/AsciidocFX/files/9877361/book.pdf)

Example EPUB , UNZIP book.zip -> book.epub
[book.zip](https://github.com/asciidocfx/AsciidocFX/files/9877363/book.zip)
