### ISSUE TITLE
Save periodically or on app out of focus, like IntelliJ

### ISSUE THREAD

**Issue by LightGuard** [asciidocfx/AsciidocFX#115]
Saving periodically would be great, or at least saving on application blur would be nice.

**Comment by rahmanusta** [comment]
I see this feature request two times. I think we should implement this nice feature.

**Comment by rahmanusta** [comment]
@LightGuard We just released v1.3.8 and imitated intellij's save/restore approach. Could you try v1.3.8 ? https://github.com/asciidocfx/AsciidocFX/releases
