### ISSUE TITLE
image link

### ISSUE THREAD

**Issue by cortix** [asciidocfx/AsciidocFX#119]
Hi,

Is AscidocFx able to create image link ? For example, I want to give link to social icons like that
![facebook](https://cloud.githubusercontent.com/assets/6178404/8934761/dd4d402c-3551-11e5-90b6-8e54e513b051.png)

**Comment by rahmanusta** [comment]
Of course, use the link option;

```
image::https://ci5.googleusercontent.com/proxy/x_rYQvTohgB_Vd5DIrRnJRO7Ml-ADGe__y7nc2S9RH8g8YJtqjsQGwDhiHDoTpEXXHqM_2g6D8ZfK_WvCrtymVLgwZuiI9BVbqbQL3sJB5O3E8jchVzgAX5sG3uPooJMFAEdVy70VDOz1EgWDls0gHCurrf1ff3ViA=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/6178404/8934761/dd4d402c-3551-11e5-90b6-8e54e513b051.png[facebook]
```

**Comment by cortix** [comment]
Thanks

in the preview screen, all links works well but after rendering all links looks like at below

![2015-07-28 20-12-10 ekran goruntusu](https://cloud.githubusercontent.com/assets/6178404/8938365/ea3f1c00-3566-11e5-928a-3cde2365cfdd.png)
![2015-07-28 20-13-24 ekran goruntusu](https://cloud.githubusercontent.com/assets/6178404/8938374/f878bc40-3566-11e5-90ec-6d4b2b68b3d1.png)


and also when I change the :lang: en to :lang: tr in the  book.asc class, I am getting some rendering error..

**Comment by rahmanusta** [comment]
There is a problem when rendering PDF, please give white area to image's left and right to see well content. It is a workaround for now.

**Comment by cortix** [comment]
![2015-07-28 20-35-59 ekran goruntusu](https://cloud.githubusercontent.com/assets/6178404/8938634/6ec10712-3568-11e5-9d89-4b058a5ce7b1.png)

When I change the the :lang: en to :lang: tr in the book.asc class, rendering pdf looks like at below

![2015-07-28 20-36-36 ekran goruntusu](https://cloud.githubusercontent.com/assets/6178404/8938652/90673b84-3568-11e5-92cb-c34e1eb66dc5.png)

**Comment by rahmanusta** [comment]
It is interesting by changing lang, first doctype is book and other is article, which version are u using?

**Comment by cortix** [comment]
my version 1.3.7

actually many time it works but many time I am getting error :)

**Comment by ozlerhakan** [comment]
another option may be that you can fix the size of an image so that in a rendered PDF file, you will see the image being 100px:
```
image::https://ci5.googleusercontent.com/proxy/x_rYQvTohgB_Vd5DIrRnJRO7Ml-ADGe__y7nc2S9RH8g8YJtqjsQGwDhiHDoTpEXXHqM_2g6D8ZfK_WvCrtymVLgwZuiI9BVbqbQL3sJB5O3E8jchVzgAX5sG3uPooJMFAEdVy70VDOz1EgWDls0gHCurrf1ff3ViA=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/6178404/8934761/dd4d402c-3551-11e5-90b6-8e54e513b051.png[facebook,link="http://facebook.com",100]
```

**Comment by cortix** [comment]
Hi @ozlerhakan ,

I tried your solution, yes it worked but the image was not clickable !!!

but I put social icons to image folder and I used like that;

image::images/facebook.png[facebook,link="https://www.facebook.com/groups/abhibe/",100]

**Comment by rahmanusta** [comment]
I tried this; it seems clickable 

```
image::https://ci5.googleusercontent.com/proxy/x_rYQvTohgB_Vd5DIrRnJRO7Ml-ADGe__y7nc2S9RH8g8YJtqjsQGwDhiHDoTpEXXHqM_2g6D8ZfK_WvCrtymVLgwZuiI9BVbqbQL3sJB5O3E8jchVzgAX5sG3uPooJMFAEdVy70VDOz1EgWDls0gHCurrf1ff3ViA=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/6178404/8934761/dd4d402c-3551-11e5-90b6-8e54e513b051.png[facebook,link="http://facebook.com",100]
```

**Comment by cortix** [comment]
Rahman Hocam,

After rendering process, I am getting this result. In the video, facebook icon(sixth one) is your suggestion. 

https://drive.google.com/file/d/0BwZ-K9WC0XGBVWFYTTNXODlLVXc/view?usp=sharing

Is this about Adobe reader latest version ? Now I am using Adobe Acrobat Reader DC latest version

**Comment by rahmanusta** [comment]
Dosyayı bana gönderebilir misin @cortix ? Bende hata vermedi ama resme link de koymadı

**Comment by cortix** [comment]
Yandex disk üzerinden dosyayı paylaştım hocam.

**Comment by rahmanusta** [comment]
@mojavelinux It seems that image with link rendered correctly, but in docbook, it renders image but with no link. Is there a limitation or workaround for that?

**Comment by mojavelinux** [comment]
It appears that image links are not implemented in the DocBook converter (it doesn't check for the link). This would need to be added. Could you file an issue in core?

One workaround is to wrap the inline image inside a link, like:

```
http://github.com[image:images/octocat.png[]]
```

But that only applies to inline images, not block images.

**Comment by cortix** [comment]
Hi @mojavelinux ,

I've tested your saying, it worked but size of the social icons are very big..Is there any way to decrease size of icons ?

https://drive.google.com/file/d/0BwZ-K9WC0XGBYkZpMy1sT3FzMTA/view?usp=sharing

**Comment by mojavelinux** [comment]
That looks like the images are being stretched to 100% (or something) by the toolchain (I'm assuming you are converting to PDF using DocBook XSL or something). You could set the size explicitly, but they really should be the normal size unless you set an explicit width.

```
image:facebook.png[Facebook,80,scaledwidth=10%]
```

The scaledwidth is one way to control the width of the image in the generated PDF...but it really, really depends on what the DocBook XSL is doing with the DocBook. That's well outside of Asciidoctor's hands.

**Comment by mojavelinux** [comment]
If you are using the DocBook XSL provided by fopub (I'm just guessing), this was a known issue. See https://github.com/asciidoctor/asciidoctor-fopub/blob/master/src/dist/docbook-xsl/fo-pdf.xsl#L429

**Comment by rahmanusta** [comment]
@mojavelinux Yes we are using DocBook XSL based on fopub.

I also file an issue for linked images in the core.

**Comment by mojavelinux** [comment]
> we are using DocBook XSL based on fopub

If you are interested, we do need a new maintainer for fopub as my focus is on other modules (Asciidoctor PDF, EPUB3, etc).

Regarding the issue at hand, that linked code needs to be changed so that it does the right thing with images (unless you are working on a copy, then the changes needed to be in your modification).

> I also file an issue for linked images in the core.

Thanks!

If you can suggest what the expected DocBook output is using a sample DocBook snippet, that would help move things along for 1.5.4.

**Comment by cortix** [comment]
Thank you @rahmanusta and @mojavelinux 

I've changed my codes like that

https://www.facebook.com/groups/abhibe/[image:images/facebook.png[Facebook,80,scaledwidth=10%]]
https://www.facebook.com/abhibedanismanlik[image:images/facebook.png[Facebook,80,scaledwidth=10%]]
https://twitter.com/ab_hibe[image:images/twitter.png[Twitter,80,scaledwidth=10%]]
https://plus.google.com/u/0/communities/107697266958805176168[image:images/google.png[Google,80,scaledwidth=10%]]
https://www.linkedin.com/groups/Erasmus-News-Eu-Projects-wwwabhibecom-8200353/about[image:images/linkedin.png[Linkedin,80,scaledwidth=10%]]
http://ab-hibe.com/index.php/tr/blog[image:images/blog.png[Blog,80,scaledwidth=10%]]
http://ab-hibe.com/index.php/tr/sorunu-sor[image:images/forum.png[Forum,80,scaledwidth=10%]]

now there is no problem :)

**Comment by rahmanusta** [comment]
So good @cortix :)

@mojavelinux it seems that docbook doesnt support links with block images.
