### ISSUE TITLE
Request : Be able to detach preview scrolling from editor scrolling

### ISSUE THREAD

**Issue by takapa** [asciidocfx/AsciidocFX#120]
When I scroll through my document, the preview window scrolls. Nice behaviour mostly, but ideally this should be configurable.

My (personal) ideal behaviour would be to move the render window scroll position on data entry (after keypress time expires). Do not move the scroll position on scrolling up and down in the editor window.

When in non-rendering mode, then the scroll position should not move at all even on data entry. Ideally there would be a visual cue in the header or overlayed in the corner of the preview window to signal that rendering is disabled so that users do not get disorientated.

**Comment by rahmanusta** [comment]
@takapa  Can you try RC6 ? https://github.com/asciidocfx/AsciidocFX#how-to-install-asciidocfx

Right click preview and you will see stop scrolling, stop jump line ..
