### ISSUE TITLE
 v1.3.7-RC5 - crashes on Windows when conf/cheatsheet/cheatsheet.adoc is opened.

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#125]
Easily reproducible using Java 1.8 (u51) (x64) and Graphviz 2.38 installed. Use "Open file" to load cheatsheet.adoc; AsciiDocFX crashes immediately.

![image](https://cloud.githubusercontent.com/assets/13682850/9180248/9240784c-3fa1-11e5-9e26-c6830ada3601.png)

**Comment by rahmanusta** [comment]
@wfouche I didnt faced with this problem. Could you test with JDK 8 U60, or JRE bundled version of AsciidocFX ?

**Comment by wfouche** [comment]
@rahmanusta - AsciidocFX works fine with the embedded JRE (Java 8 u60) on my Windows 10 laptop; however it crashes with Java 8 U51 on the same laptop. Seems like Java 8 u60 is required, but it is not officially released yet. See https://www.java.com/en/download/faq/release_dates.xml

**Comment by rahmanusta** [comment]
@wfouche There were crashes issues before Java 8 U60, it is not final but resolves crash issues.

**Comment by wfouche** [comment]
@rahmanusta In that case, I'll close this ticket given that 8u60 resolves the crash. Thanks.
