### ISSUE TITLE
v1.3.7-RC5: booksample/chapter-08.adoc is not rendered correctly.

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#126]
Appears as follows in AsciiDocFX.

![image](https://cloud.githubusercontent.com/assets/13682850/9180374/62b138ae-3fa2-11e5-8d63-e66caf715cb3.png)

**Comment by rahmanusta** [comment]
@wfouche Documentation updated, can you try with @startditaa and @endditaa  ?

https://github.com/asciidocfx/AsciidocFX/blob/master/README.asc#ditaa-extension

**Comment by wfouche** [comment]
@rahmanusta The Java extension created by @joemat is not activated although it has been integrated into the code base. See change https://github.com/asciidocfx/AsciidocFX/commit/1fbb1f089c8a855ec2932614e0cf2dcf50fcda3d 

Change https://github.com/asciidocfx/AsciidocFX/blob/master/README.asc#ditaa-extension is not required in this case and should best be reverted and @joemat's extension activated / fixed.

**Comment by rahmanusta** [comment]
This is my sorry @wfouche . I forgot to add ditaa-block.js script after some changes. I'll release RC5 again with this hotfix.

**Comment by wfouche** [comment]
@rahmanusta Do you have a pre-release check list for AsciidoxFX? If not, it would be beneficial to create one and then before each release just run through the check list to see that key bits of functionality still work. Here's my attempt at a pre-release Check List:

*  Open conf/cheatsheet.adoc and see if it renders correctly, then save it as PDF and see if the PDF is rendered correctly as well.
* Create a sample book and verify that it renders correctly on screen and when saved to PDF.
* .... etc.

**Comment by wfouche** [comment]
@rahmanusta issue resolved in latest build of 1.3.7 RC5. Thanks!

**Comment by joemat** [comment]
There is a similar problem with the [README.asc](https://github.com/asciidocfx/AsciidocFX#ditaa-extension)  in the project root folder in the chapter "ditaa Extension" :

The block:
````
.ditaa Diagram Example
[ditaa,file="images/ditaa-example.png"]
--
@startditaa
    +--------+   +-------+    +-------+
    |        |---+ ditaa +--->|       |
    |  Text  |   +-------+    |diagram|
    |Document|   |!magic!|    |       |
    |     {d}|   |       |    |       |
    +---+----+   +-------+    +-------+
        :                         ^
        |       Lots of work      |
        +-------------------------+
@endditaa
--
````
should be written without the @startditaa and @endditaa tags:

````
.ditaa Diagram Example
[ditaa,file="images/ditaa-example.png"]
--
    +--------+   +-------+    +-------+
    |        |---+ ditaa +--->|       |
    |  Text  |   +-------+    |diagram|
    |Document|   |!magic!|    |       |
    |     {d}|   |       |    |       |
    +---+----+   +-------+    +-------+
        :                         ^
        |       Lots of work      |
        +-------------------------+
--
````

**Comment by rahmanusta** [comment]
Yes, can you make a pull request for readme ?
