### ISSUE TITLE
Issue with bold/italics inside code font when rendering PDF

### ISSUE THREAD

**Issue by stallio** [asciidocfx/AsciidocFX#127]
I was having trouble making PDFs from a test file and eventually figured out that it was because my file had the following text:

`code font with *bold inside*`, `code font with _italics inside_`, `code with *_bold and italics_*`

When I try to save a PDF, I instead get a temp XML file and am prompted to fix a validation error. The error seems to be that this formatting results in a <emphasis> inside a <literal> and this is invalid in Docbook:
http://www.docbook.org/tdg/en/html/literal.html
http://www.docbook.org/tdg/en/html/emphasis.html

The same is also true for other tags like <code> etc. Docbook assumes the <emphasis> will always be the parent and never the child.

**Comment by rahmanusta** [comment]
Indeed I dont know how to workaround with your issue. @mojavelinux Do you have a suggestion for @stallio ?

**Comment by rahmanusta** [comment]
@ozlerhakan What do you think about the issue ?

**Comment by ozlerhakan** [comment]
Kardeşim, I have pushed a branch that is available to be merged anytime, so that <emphasis> elements can occur in <literal> and <code> elements.

We are now able to generate a PDF with a small change in the format of the (above) example :

```
`code font with *bold inside*`, `code font with _italics inside_`, `code with _**bold and italics**_`
 ```
