### ISSUE TITLE
Pre-release checklist for AsciidocFX

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#128]
@rahmanusta Do you have a pre-release check list for AsciidoxFX? If not, it would be beneficial to create one and then before each release just run through the check list to see that key bits of functionality still work. Here's my attempt at starting a pre-release checklist:

* Open conf/cheatsheet.adoc and see if it renders correctly, then save it as PDF and see if the PDF is rendered correctly as well.
* Create a sample book and verify that it renders correctly on screen and when saved to PDF.
* .... etc.

**Comment by rahmanusta** [comment]
@wfouche That is quite well suggestion. Can you lead us to do that?

**Comment by wfouche** [comment]
@rahmanusta  Here's an example of what another project on Github has done:

* https://github.com/mixpanel/mixpanel-js/wiki/Release-Checklist

Something similar would benefit the AsciidocFX project. This is a document that you are in a better position than me to create. If you can start it, I'll review and help revise it.

**Comment by rahmanusta** [comment]
@wfouche I will try that, Thank you
