### ISSUE TITLE
Request : save PDF (please add coverpage image support to book pdf coverpage )

### ISSUE THREAD

**Issue by simplelife201008** [asciidocfx/AsciidocFX#130]
Request : save PDF (please add coverpage image support to book pdf coverpage )

EX:
# Pro Git

:doctype:   book
:docinfo:
:toc:
:toclevels: 2
:front-cover-image: image:book/cover.png[width=1050,height=1600]

**Comment by simplelife201008** [comment]
my request is duplicate request :  Book Cover Feature #114 

I hope  one of these code can set Book Cover
* `:front-cover-image: image:book/cover.png[width=1050,height=1600]`
* `:titlepage-logo: images/cover.png`


* `include::titlepage.adoc[]`
.titlepage.adoc content
`[titlepage]`
`image::images/cover.png[]`

**Comment by rahmanusta** [comment]
@simplelife201008  We are thinking to implement it.
