### ISSUE TITLE
Issue : Generate PDF Fail because some special char

### ISSUE THREAD

**Issue by simplelife201008** [asciidocfx/AsciidocFX#131]
Open https://github.com/asciidocfx/AsciidocFX/README.asc
PDF , Save As , not generated PDF File , it generate a temp docbook xml ,  
then get error message: ERROR => Please fix Docbook validation error. LineNumber: 648, Column: 85
org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'emphasis'. One of '{"http://docbook.org/ns/docbook":inlinemediaobject, "http://docbook.org/ns/docbook":remark, "http://docbook.org/ns/docbook":superscript, "http://docbook.org/ns/docbook":subscript, "http://docbook.org/ns/docbook":xref, "http://docbook.org/ns/docbook":link, "http://docbook.org/ns/docbook":olink, "http://docbook.org/ns/docbook":anchor, "http://docbook.org/ns/docbook":biblioref, "http://docbook.org/ns/docbook":alt, "http://docbook.org/ns/docbook":annotation, "http://docbook.org/ns/docbook":indexterm, "http://docbook.org/ns/docbook":phrase, "http://docbook.org/ns/docbook":replaceable}' is expected.

the temp docbook xml at line 648 is: =>     
`    <entry align="left" valign="top"><simpara><keycombo><keycap><emphasis role="strong">tblx&#44;y</emphasis></keycap><keycap>Tab</keycap></keycombo></simpara></entry>`

I found the README.asc is 
`    |kbd:[*tblx&#44;y* + Tab] |Generates asciidoc table (x=row,y=column)`

It looks  special char is `&#44;`   make AsciidocFX  translate to docbook xml not validattion

**Comment by rahmanusta** [comment]
Problems caused from **, please try updated readme in master.

**Comment by rahmanusta** [comment]
@simplelife201008 Did you try that?
