### ISSUE TITLE
Automatic reloading of document on file modification.

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#132]
Requesting that AsciidocFX be enhanced to automatically reload the current document if it is modified externally by another application. Some of the other Asciidoc editors support this feature.

The following information from Oracle on Java file change notifications seem relevant: https://docs.oracle.com/javase/tutorial/essential/io/notification.html

**Comment by rahmanusta** [comment]
AsciidocFX is already support this feature

**Comment by wfouche** [comment]
@rahmanusta That's good to know. However this functionality is not working on Windows. I'll try on Linux.

**Comment by rahmanusta** [comment]
@wfouche  Hmm, which version of Win are you using? Did you have a chance to try in Linuz ?

**Comment by rahmanusta** [comment]
@wfouche We are watching the files in Workdir but not outside.
