### ISSUE TITLE
Navigate from Preview Panel to corresponding line in Editor Panel.

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#133]
Requesting that AsciidocFX be extended to support the following functionality. When holding down the CTRL key and left clicking in the Preview panel, the corresponding text in the Editor Panel should be displayed. Currently when reviewing the output in the Preview Panel, there is no way of quickly locating finding the corresponding text in the Editor Panel (if changes are required).

**Comment by rahmanusta** [comment]
Should we search in editor by selecting text in preview pane with CTRL key?

**Comment by rahmanusta** [comment]
@wfouche Could you try v1.3.9 ? Just click corresponded element, and it will show its counterpart in editor pane

**Comment by gernotstarke** [comment]
works, I propose to close this issue.
