### ISSUE TITLE
Process manager already initialized: can't fully enable headless mode

### ISSUE THREAD

**Issue by cosyman** [asciidocfx/AsciidocFX#134]
in mac osx 10.10.5,I run latest source code in intellij idea,window splashed and lost 

/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -Didea.launcher.port=7533 ................intellij.rt.execution.application.AppMain com.kodcu.boot.AppStarter
   #                 #   #      #                #####  #   #
  # #    ####   ###          ####   ###    ###   #       # #
 #   #  ###    #     #   #  #   #  #   #  #      ####     #
 #####    ###  #     #   #  #   #  #   #  #      #       # #
 #   #  ####    ###  #   #   ####   ###    ###   #      #   #
 ============================================================
 :: Asciidoc FX ::     (v1.3.7)

 Website: http://asciidocfx.com

2015-08-21 22:13:55.164 java[1574:50095] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
2015-08-21 22:13:55.184 java[1574:50095] *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
2015-08-21 22:13:55.186 java[1574:50095] (
	0   CoreFoundation                      0x00007fff8f6da03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff98e9a76e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8f585329 -[__NSArrayM insertObject:atIndex:] + 1033
	3   AppKit                              0x00007fff8c054d12 -[NSMenu insertItem:atIndex:] + 487
	4   libawt_lwawt.dylib                  0x000000012da8a5e7 addMenuItem + 185
	5   libawt_lwawt.dylib                  0x000000012da89f54 -[ApplicationDelegate _updatePreferencesMenu:enabled:] + 211
	6   libawt_lwawt.dylib                  0x000000012da8a179 __Java_com_apple_eawt__1AppMenuBarHandler_nativeSetMenuState_block_invoke_1 + 159
	7   JavaNativeFoundation                0x000000011f12fd3a +[JNFRunLoop _performCopiedBlock:] + 17
	8   Foundation                          0x00007fff8f04edd0 __NSThreadPerformPerform + 293
	9   CoreFoundation                      0x00007fff8f5f6a01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	10  CoreFoundation                      0x00007fff8f5e8c5c __CFRunLoopDoSources0 + 476
	11  CoreFoundation                      0x00007fff8f5e81bf __CFRunLoopRun + 927
	12  CoreFoundation                      0x00007fff8f5e7bd8 CFRunLoopRunSpecific + 296
	13  HIToolbox                           0x00007fff8cc1e56f RunCurrentEventLoopInMode + 235
	14  HIToolbox                           0x00007fff8cc1e2ea ReceiveNextEventCommon + 431
	15  HIToolbox                           0x00007fff8cc1e12b _BlockUntilNextEventMatchingListInModeWithFilter + 71
	16  AppKit                              0x00007fff8c0648ab _DPSNextEvent + 978
	17  AppKit                              0x00007fff8c063e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
	18  AppKit                              0x00007fff8c059af3 -[NSApplication run] + 594
	19  libglass.dylib                      0x00000001226b05ec -[GlassApplication runLoop:] + 1836
	20  Foundation                          0x00007fff8f04edd0 __NSThreadPerformPerform + 293
	21  CoreFoundation                      0x00007fff8f5f6a01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x00007fff8f5e8b8d __CFRunLoopDoSources0 + 269
	23  CoreFoundation                      0x00007fff8f5e81bf __CFRunLoopRun + 927
	24  CoreFoundation                      0x00007fff8f5e7bd8 CFRunLoopRunSpecific + 296
	25  java                                0x0000000107696463 CreateExecutionEnvironment + 871
	26  java                                0x00000001076921ac JLI_Launch + 1952
	27  java                                0x00000001076984c0 main + 101
	28  java                                0x0000000107691a04 start + 52
	29  ???                                 0x0000000000000008 0x0 + 8
)
2015-08-21 22:13:55.187 java[1574:50095] *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
2015-08-21 22:13:55.189 java[1574:50095] (
	0   CoreFoundation                      0x00007fff8f6da03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff98e9a76e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8f585329 -[__NSArrayM insertObject:atIndex:] + 1033
	3   AppKit                              0x00007fff8c054d12 -[NSMenu insertItem:atIndex:] + 487
	4   libawt_lwawt.dylib                  0x000000012da8a5e7 addMenuItem + 185
	5   libawt_lwawt.dylib                  0x000000012da89f54 -[ApplicationDelegate _updatePreferencesMenu:enabled:] + 211
	6   libawt_lwawt.dylib                  0x000000012da8a179 __Java_com_apple_eawt__1AppMenuBarHandler_nativeSetMenuState_block_invoke_1 + 159
	7   JavaNativeFoundation                0x000000011f12fd3a +[JNFRunLoop _performCopiedBlock:] + 17
	8   Foundation                          0x00007fff8f04edd0 __NSThreadPerformPerform + 293
	9   CoreFoundation                      0x00007fff8f5f6a01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	10  CoreFoundation                      0x00007fff8f5e8c5c __CFRunLoopDoSources0 + 476
	11  CoreFoundation                      0x00007fff8f5e81bf __CFRunLoopRun + 927
	12  CoreFoundation                      0x00007fff8f5e7bd8 CFRunLoopRunSpecific + 296
	13  HIToolbox                           0x00007fff8cc1e56f RunCurrentEventLoopInMode + 235
	14  HIToolbox                           0x00007fff8cc1e1ee ReceiveNextEventCommon + 179
	15  HIToolbox                           0x00007fff8cc1e12b _BlockUntilNextEventMatchingListInModeWithFilter + 71
	16  AppKit                              0x00007fff8c0648ab _DPSNextEvent + 978
	17  AppKit                              0x00007fff8c063e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
	18  AppKit                              0x00007fff8c059af3 -[NSApplication run] + 594
	19  libglass.dylib                      0x00000001226b05ec -[GlassApplication runLoop:] + 1836
	20  Foundation                          0x00007fff8f04edd0 __NSThreadPerformPerform + 293
	21  CoreFoundation                      0x00007fff8f5f6a01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x00007fff8f5e8b8d __CFRunLoopDoSources0 + 269
	23  CoreFoundation                      0x00007fff8f5e81bf __CFRunLoopRun + 927
	24  CoreFoundation                      0x00007fff8f5e7bd8 CFRunLoopRunSpecific + 296
	25  java                                0x0000000107696463 CreateExecutionEnvironment + 871
	26  java                                0x00000001076921ac JLI_Launch + 1952
	27  java                                0x00000001076984c0 main + 101
	28  java                                0x0000000107691a04 start + 52
	29  ???                                 0x0000000000000008 0x0 + 8
)
12728 [AWT-AppKit] DEBUG c.k.service.ui.FileBrowseService - Filesystem Tree relisted for /Users/cosyman 
12744 [pool-2-thread-8] DEBUG com.kodcu.service.FileWatchService - Watchservice started for: /Users/cosyman 
[Fatal Error] entities.ent:16:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] l10n.dtd:1:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] targetdatabase.dtd:4:3: The markup in the document preceding the root element must be well-formed.

**Comment by rahmanusta** [comment]
@cosyman I don't know the reason but, firstly I want to ask you that are you able to run any JavaFX application in your system ?

**Comment by rahmanusta** [comment]
@cosyman did you solve this issue ?

**Comment by cosyman** [comment]
No,I didn't.

I just download and update my AsciidocFX to v1.3.7-RC6,I open AsciidocFX app,The AsciidoxFX window show,However, after a while child,The Window has disappeared only toolbar left.

I pull latest code,and run it in eclipse, the error were same. I have delete the code ralated to install4j,and It didn't work.
I'think it may be caused by **[Fatal Error] entities.ent**

-------------------------------------
The follow is error in detail.

   #                 #   #      #                #####  #   #
  # #    ####   ###          ####   ###    ###   #       # #
 #   #  ###    #     #   #  #   #  #   #  #      ####     #
 #####    ###  #     #   #  #   #  #   #  #      #       # #
 #   #  ####    ###  #   #   ####   ###    ###   #      #   #
 ============================================================
 :: Asciidoc FX ::     (v1.3.7-RC6)

 Website: http://asciidocfx.com

2015-09-07 21:51:46.681 java[387:3507] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
2015-09-07 21:51:46.719 java[387:3507] *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
2015-09-07 21:51:46.722 java[387:3507] (
	0   CoreFoundation                      0x00007fff88f2003c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff94f4476e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff88dcb329 -[__NSArrayM insertObject:atIndex:] + 1033
	3   AppKit                              0x00007fff8b878d12 -[NSMenu insertItem:atIndex:] + 487
	4   libawt_lwawt.dylib                  0x000000013376f5e7 addMenuItem + 185
	5   libawt_lwawt.dylib                  0x000000013376ef54 -[ApplicationDelegate _updatePreferencesMenu:enabled:] + 211
	6   libawt_lwawt.dylib                  0x000000013376f179 __Java_com_apple_eawt__1AppMenuBarHandler_nativeSetMenuState_block_invoke_1 + 159
	7   JavaNativeFoundation                0x000000012514ed3a +[JNFRunLoop _performCopiedBlock:] + 17
	8   Foundation                          0x00007fff88ab4dd0 __NSThreadPerformPerform + 293
	9   CoreFoundation                      0x00007fff88e3ca01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	10  CoreFoundation                      0x00007fff88e2ec5c __CFRunLoopDoSources0 + 476
	11  CoreFoundation                      0x00007fff88e2e1bf __CFRunLoopRun + 927
	12  CoreFoundation                      0x00007fff88e2dbd8 CFRunLoopRunSpecific + 296
	13  HIToolbox                           0x00007fff8ea4156f RunCurrentEventLoopInMode + 235
	14  HIToolbox                           0x00007fff8ea412ea ReceiveNextEventCommon + 431
	15  HIToolbox                           0x00007fff8ea4112b _BlockUntilNextEventMatchingListInModeWithFilter + 71
	16  AppKit                              0x00007fff8b8888ab _DPSNextEvent + 978
	17  AppKit                              0x00007fff8b887e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
	18  AppKit                              0x00007fff8b87daf3 -[NSApplication run] + 594
	19  libglass.dylib                      0x0000000127d645ec -[GlassApplication runLoop:] + 1836
	20  Foundation                          0x00007fff88ab4dd0 __NSThreadPerformPerform + 293
	21  CoreFoundation                      0x00007fff88e3ca01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x00007fff88e2eb8d __CFRunLoopDoSources0 + 269
	23  CoreFoundation                      0x00007fff88e2e1bf __CFRunLoopRun + 927
	24  CoreFoundation                      0x00007fff88e2dbd8 CFRunLoopRunSpecific + 296
	25  java                                0x000000010d6b2463 CreateExecutionEnvironment + 871
	26  java                                0x000000010d6ae1ac JLI_Launch + 1952
	27  java                                0x000000010d6b44c0 main + 101
	28  java                                0x000000010d6ada04 start + 52
	29  ???                                 0x0000000000000005 0x0 + 5
)
2015-09-07 21:51:46.725 java[387:3507] *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
2015-09-07 21:51:46.727 java[387:3507] (
	0   CoreFoundation                      0x00007fff88f2003c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff94f4476e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff88dcb329 -[__NSArrayM insertObject:atIndex:] + 1033
	3   AppKit                              0x00007fff8b878d12 -[NSMenu insertItem:atIndex:] + 487
	4   libawt_lwawt.dylib                  0x000000013376f5e7 addMenuItem + 185
	5   libawt_lwawt.dylib                  0x000000013376ef54 -[ApplicationDelegate _updatePreferencesMenu:enabled:] + 211
	6   libawt_lwawt.dylib                  0x000000013376f179 __Java_com_apple_eawt__1AppMenuBarHandler_nativeSetMenuState_block_invoke_1 + 159
	7   JavaNativeFoundation                0x000000012514ed3a +[JNFRunLoop _performCopiedBlock:] + 17
	8   Foundation                          0x00007fff88ab4dd0 __NSThreadPerformPerform + 293
	9   CoreFoundation                      0x00007fff88e3ca01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	10  CoreFoundation                      0x00007fff88e2ec5c __CFRunLoopDoSources0 + 476
	11  CoreFoundation                      0x00007fff88e2e1bf __CFRunLoopRun + 927
	12  CoreFoundation                      0x00007fff88e2dbd8 CFRunLoopRunSpecific + 296
	13  HIToolbox                           0x00007fff8ea4156f RunCurrentEventLoopInMode + 235
	14  HIToolbox                           0x00007fff8ea411ee ReceiveNextEventCommon + 179
	15  HIToolbox                           0x00007fff8ea4112b _BlockUntilNextEventMatchingListInModeWithFilter + 71
	16  AppKit                              0x00007fff8b8888ab _DPSNextEvent + 978
	17  AppKit                              0x00007fff8b887e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
	18  AppKit                              0x00007fff8b87daf3 -[NSApplication run] + 594
	19  libglass.dylib                      0x0000000127d645ec -[GlassApplication runLoop:] + 1836
	20  Foundation                          0x00007fff88ab4dd0 __NSThreadPerformPerform + 293
	21  CoreFoundation                      0x00007fff88e3ca01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x00007fff88e2eb8d __CFRunLoopDoSources0 + 269
	23  CoreFoundation                      0x00007fff88e2e1bf __CFRunLoopRun + 927
	24  CoreFoundation                      0x00007fff88e2dbd8 CFRunLoopRunSpecific + 296
	25  java                                0x000000010d6b2463 CreateExecutionEnvironment + 871
	26  java                                0x000000010d6ae1ac JLI_Launch + 1952
	27  java                                0x000000010d6b44c0 main + 101
	28  java                                0x000000010d6ada04 start + 52
	29  ???                                 0x0000000000000005 0x0 + 5
)
8414 [AWT-AppKit] DEBUG c.k.service.ui.FileBrowseService - Filesystem Tree relisted for /Users/cosyman 
8428 [pool-2-thread-8] DEBUG com.kodcu.service.FileWatchService - Watchservice started for: /Users/cosyman 
[Fatal Error] entities.ent:16:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] l10n.dtd:1:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] targetdatabase.dtd:4:3: The markup in the document preceding the root element must be well-formed.

**Comment by rahmanusta** [comment]
[Fatal Error] entities.ent errors are normal.

@cosyman  Could you try a basic JavaFX application whether it works or not ?

**Comment by cosyman** [comment]
Yes I have tried [sdkfx](https://github.com/guigarage/sdkfx),javafx demo in java8,jitwatch and others. They all work.

**Comment by rahmanusta** [comment]
Could you record a short video for the issue? It is interesting. What version of Mac ane you using?

**Comment by cosyman** [comment]
@rahmanusta 
[my short video on baidu](http://pan.baidu.com/s/1ntrdHqT)

**Comment by rahmanusta** [comment]
Thanks @cosyman , The URL redirects me to http://pan.baidu.com/error/404.html

**Comment by rahmanusta** [comment]
@cosyman  I watched the video that you sent me. I see there is some errors with red lines. Could you post here all of the output ?

**Comment by cosyman** [comment]
```shell
   #                 #   #      #                #####  #   #
  # #    ####   ###          ####   ###    ###   #       # #
 #   #  ###    #     #   #  #   #  #   #  #      ####     #
 #####    ###  #     #   #  #   #  #   #  #      #       # #
 #   #  ####    ###  #   #   ####   ###    ###   #      #   #
 ============================================================
 :: Asciidoc FX ::     (v1.3.7-RC6)

 Website: http://asciidocfx.com

2015-09-11 13:04:39.088 java[1426:38457] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
2015-09-11 13:04:39.136 java[1426:38457] *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
2015-09-11 13:04:39.140 java[1426:38457] (
	0   CoreFoundation                      0x00007fff8b1f103c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9721576e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8b09c329 -[__NSArrayM insertObject:atIndex:] + 1033
	3   AppKit                              0x00007fff8db49d12 -[NSMenu insertItem:atIndex:] + 487
	4   libawt_lwawt.dylib                  0x000000013356e5e7 addMenuItem + 185
	5   libawt_lwawt.dylib                  0x000000013356df54 -[ApplicationDelegate _updatePreferencesMenu:enabled:] + 211
	6   libawt_lwawt.dylib                  0x000000013356e179 __Java_com_apple_eawt__1AppMenuBarHandler_nativeSetMenuState_block_invoke_1 + 159
	7   JavaNativeFoundation                0x0000000122d46d3a +[JNFRunLoop _performCopiedBlock:] + 17
	8   Foundation                          0x00007fff8ad85dd0 __NSThreadPerformPerform + 293
	9   CoreFoundation                      0x00007fff8b10da01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	10  CoreFoundation                      0x00007fff8b0ffc5c __CFRunLoopDoSources0 + 476
	11  CoreFoundation                      0x00007fff8b0ff1bf __CFRunLoopRun + 927
	12  CoreFoundation                      0x00007fff8b0febd8 CFRunLoopRunSpecific + 296
	13  HIToolbox                           0x00007fff90d1256f RunCurrentEventLoopInMode + 235
	14  HIToolbox                           0x00007fff90d121ee ReceiveNextEventCommon + 179
	15  HIToolbox                           0x00007fff90d1212b _BlockUntilNextEventMatchingListInModeWithFilter + 71
	16  AppKit                              0x00007fff8db598ab _DPSNextEvent + 978
	17  AppKit                              0x00007fff8db58e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
	18  AppKit                              0x00007fff8db4eaf3 -[NSApplication run] + 594
	19  libglass.dylib                      0x000000012595b5ec -[GlassApplication runLoop:] + 1836
	20  Foundation                          0x00007fff8ad85dd0 __NSThreadPerformPerform + 293
	21  CoreFoundation                      0x00007fff8b10da01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x00007fff8b0ffb8d __CFRunLoopDoSources0 + 269
	23  CoreFoundation                      0x00007fff8b0ff1bf __CFRunLoopRun + 927
	24  CoreFoundation                      0x00007fff8b0febd8 CFRunLoopRunSpecific + 296
	25  java                                0x000000010b2a9463 CreateExecutionEnvironment + 871
	26  java                                0x000000010b2a51ac JLI_Launch + 1952
	27  java                                0x000000010b2ab4c0 main + 101
	28  java                                0x000000010b2a4a04 start + 52
	29  ???                                 0x0000000000000005 0x0 + 5
)
2015-09-11 13:04:39.144 java[1426:38457] *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
2015-09-11 13:04:39.146 java[1426:38457] (
	0   CoreFoundation                      0x00007fff8b1f103c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9721576e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8b09c329 -[__NSArrayM insertObject:atIndex:] + 1033
	3   AppKit                              0x00007fff8db49d12 -[NSMenu insertItem:atIndex:] + 487
	4   libawt_lwawt.dylib                  0x000000013356e5e7 addMenuItem + 185
	5   libawt_lwawt.dylib                  0x000000013356df54 -[ApplicationDelegate _updatePreferencesMenu:enabled:] + 211
	6   libawt_lwawt.dylib                  0x000000013356e179 __Java_com_apple_eawt__1AppMenuBarHandler_nativeSetMenuState_block_invoke_1 + 159
	7   JavaNativeFoundation                0x0000000122d46d3a +[JNFRunLoop _performCopiedBlock:] + 17
	8   Foundation                          0x00007fff8ad85dd0 __NSThreadPerformPerform + 293
	9   CoreFoundation                      0x00007fff8b10da01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	10  CoreFoundation                      0x00007fff8b0ffc5c __CFRunLoopDoSources0 + 476
	11  CoreFoundation                      0x00007fff8b0ff1bf __CFRunLoopRun + 927
	12  CoreFoundation                      0x00007fff8b0febd8 CFRunLoopRunSpecific + 296
	13  HIToolbox                           0x00007fff90d1256f RunCurrentEventLoopInMode + 235
	14  HIToolbox                           0x00007fff90d121ee ReceiveNextEventCommon + 179
	15  HIToolbox                           0x00007fff90d1212b _BlockUntilNextEventMatchingListInModeWithFilter + 71
	16  AppKit                              0x00007fff8db598ab _DPSNextEvent + 978
	17  AppKit                              0x00007fff8db58e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
	18  AppKit                              0x00007fff8db4eaf3 -[NSApplication run] + 594
	19  libglass.dylib                      0x000000012595b5ec -[GlassApplication runLoop:] + 1836
	20  Foundation                          0x00007fff8ad85dd0 __NSThreadPerformPerform + 293
	21  CoreFoundation                      0x00007fff8b10da01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x00007fff8b0ffb8d __CFRunLoopDoSources0 + 269
	23  CoreFoundation                      0x00007fff8b0ff1bf __CFRunLoopRun + 927
	24  CoreFoundation                      0x00007fff8b0febd8 CFRunLoopRunSpecific + 296
	25  java                                0x000000010b2a9463 CreateExecutionEnvironment + 871
	26  java                                0x000000010b2a51ac JLI_Launch + 1952
	27  java                                0x000000010b2ab4c0 main + 101
	28  java                                0x000000010b2a4a04 start + 52
	29  ???                                 0x0000000000000005 0x0 + 5
)
9834 [AWT-AppKit] DEBUG c.k.service.ui.FileBrowseService - Filesystem Tree relisted for /Users/cosyman 
9850 [pool-2-thread-5] DEBUG com.kodcu.service.FileWatchService - Watchservice started for: /Users/cosyman 
[Fatal Error] entities.ent:16:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] l10n.dtd:1:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] targetdatabase.dtd:4:3: The markup in the document preceding the root element must be well-formed.
```

**Comment by rahmanusta** [comment]
@cosyman Could you try changing main method in AppStarter class ?

 public static void main(String[] args) {
        java.awt.Toolkit.getDefaultToolkit();
        launch(args);
    }

**Comment by cosyman** [comment]
@rahmanusta I have tried your method，and the same error with same console output。

I have no good way to debug it

**Comment by rahmanusta** [comment]
@cosyman Can you try like that http://technical-links.blogspot.com.tr/2014/09/jrsappkitawt-markappisdaemon-process.html;

If it is not working again, we can file an issue to Open JFX.

**Comment by cosyman** [comment]
@rahmanusta In fact a few days ago I have tried that method. and just now that's still not work.

I will try to run it on other Mac on Monday.

**Comment by rahmanusta** [comment]
Hi @cosyman Could you try older versions of jdk than 1.8.0 u60 ? Also, which version is the newest  running version on your system?

**Comment by rahmanusta** [comment]
@cosyman Could you try v1.3.9 ?

**Comment by cosyman** [comment]
@rahmanusta  I have tried v1.3.9 on macosx10.11, jdk 1.8u60
I had also tried v1.3.8 on macosx10.10, jdk 1.8u45 serveral days ago。
the same error happened.

I‘m watiting new jdk version to try,and now I'm using windows for AsciidocFX

**Comment by rahmanusta** [comment]
@cosyman Thank you, I wonder, could you run application with -Djava.awt.headless=true jvm parameter? You can it in AsciidocFX.vmoptions file

**Comment by rahmanusta** [comment]
@cosyman a guy told me that this problem solved in v1.4.0, could you try v1.4.1 ?

**Comment by cosyman** [comment]
Actually，1.4.1 not work at my macbook osx 10.11.2

And Today I tried AsciidocFX 1.4.4, It's worked!  :laughing:

**Comment by rahmanusta** [comment]
:+1:  :+1:  :+1:  :)
