### ISSUE TITLE
Issue: lang attribute is not work after 1.37 RC1

### ISSUE THREAD

**Issue by simplelife201008** [asciidocfx/AsciidocFX#135]
`:lang: zh_tw`  is work when generate PDF or docbook at 1.37 RC1
`:lang: zh_tw`  is not work when generate PDF or docbook at 1.37 RC2 ~ RC5

I think  `src/main/resources/public/js/asciidoctor-docbook.js` may be have something wrong
lang function or attribute is wrong

**Comment by rahmanusta** [comment]
@simplelife201008 You need to change lang option in Settings page. But we will fix this problem.

**Comment by rahmanusta** [comment]
@simplelife201008 Can you try RC6 ? https://github.com/asciidocfx/AsciidocFX#how-to-install-asciidocfx
