### ISSUE TITLE
Vista not supported

### ISSUE THREAD

**Issue by PBastiani** [asciidocfx/AsciidocFX#136]
AsciidocFX cannot be launch under Vista OS.

**Comment by rahmanusta** [comment]
Which version of AsciidocFX are you using?
Is your OS x86 or x64?

**Comment by PBastiani** [comment]
Vitsa SP2 - x86
AsciidocFX-1.3.7

**Comment by rahmanusta** [comment]
Hello @PBastiani , yes all builds are x64 based.

Could you send a pull request for that?

Thanks.
