### ISSUE TITLE
Chinese characters are not displayed in exported PDF files

### ISSUE THREAD

**Issue by hefanbo** [asciidocfx/AsciidocFX#138]
Chinese characters are displayed as ### in exported PDF files.

**Comment by hefanbo** [comment]
@rahmanusta I'm using Windows.

**Comment by rahmanusta** [comment]
Sorry. Default used font for afx e
İs Arial and it is not changeable by user for now. I changed it to Arial Unicode  MS and chinese characters rendered correctly. In further release I we
İll push afx with unicoded arial font, but in future we need to give a way to users change fonts in user interface

**Comment by simplelife201008** [comment]
My Config  D:\TOOLS\AsciidocFX
_Copy Chinese TTF File_
    copy c:\windows\fonts\msjh.ttf D:\TOOLS\AsciidocFX\conf\docbook-config
    copy c:\windows\fonts\msjhbd.ttf D:\TOOLS\AsciidocFX\conf\docbook-config 


_Generate FOP ttf font xml_

    java -cp D:\TOOLS\AsciidocFX\lib\fop-1.1.jar;D:\TOOLS\AsciidocFX\lib\avalon-framework-api-4.3.1.jar;D:\TOOLS\AsciidocFX\lib\avalon-framework-impl-4.3.1.jar;D:\TOOLS\AsciidocFX\lib\xmlgraphics-commons-1.5.jar;D:\TOOLS\AsciidocFX\lib\commons-io-2.4.jar;D:\TOOLS\AsciidocFX\lib\commons-logging-1.0.4.jar org.apache.fop.fonts.apps.TTFReader D:\TOOLS\AsciidocFX\conf\docbook-config\msjh.ttf  D:\TOOLS\AsciidocFX\conf\docbook-config\msjh.xml

_Generate FOP ttf Bold font xml_

    java -cp D:\TOOLS\AsciidocFX\lib\fop-1.1.jar;D:\TOOLS\AsciidocFX\lib\avalon-framework-api-4.3.1.jar;D:\TOOLS\AsciidocFX\lib\avalon-framework-impl-4.3.1.jar;D:\TOOLS\AsciidocFX\lib\xmlgraphics-commons-1.5.jar;D:\TOOLS\AsciidocFX\lib\commons-io-2.4.jar;D:\TOOLS\AsciidocFX\lib\commons-logging-1.0.4.jar org.apache.fop.fonts.apps.TTFReader D:\TOOLS\AsciidocFX\conf\docbook-config\msjhbd.ttf  D:\TOOLS\AsciidocFX\conf\docbook-config\msjhbd.xml

_Modify D:\TOOLS\AsciidocFX\conf\docbook-config\fop.xconf_

      <renderers>
        <renderer mime="application\pdf">
      ...  
        <auto-detect\>         
     <font metrics-url="D:\TOOLS\AsciidocFX\conf\docbook-config\msjh.xml" kerning="yes" embed-url="D:\TOOLS\AsciidocFX\conf\docbook-config\msjh.ttf">  
          <font-triplet name="MicrosoftJhengHei" style="normal" weight="normal"\> 
          <font-triplet name="MicrosoftJhengHei" style="italic" weight="normal"\> 
        <\font>
     <font metrics-url="D:\TOOLS\AsciidocFX\conf\docbook-config\msjhbd.xml" kerning="yes" embed-url="D:\TOOLS\AsciidocFX\conf\docbook-config\msjhbd.ttf"> 
          <font-triplet name="MicrosoftJhengHei" style="normal" weight="bold"\> 
          <font-triplet name="MicrosoftJhengHei" style="italic" weight="bold"\> 
        <\font>
      <\fonts> 
      ...
    <\renderer>
    <renderer mime="application\x-afp">


modify D:\TOOLS\AsciidocFX\conf\docbook-config\fo-pdf.xsl

    
    
    
    <xsl:param name="body.font.family">MicrosoftJhengHei<\xsl:param>
    <xsl:param name="sans.font.family">MicrosoftJhengHei<\xsl:param>
    <xsl:param name="monospace.font.family">MicrosoftJhengHei<\xsl:param>
    <xsl:param name="dingbat.font.family">MicrosoftJhengHei<\xsl:param>
    <xsl:param name="symbol.font.family">MicrosoftJhengHei<\xsl:param>
    <xsl:param name="title.font.family">MicrosoftJhengHei<\xsl:param>

**Comment by simplelife201008** [comment]
my pdf can display chinese characters  OK

**Comment by hefanbo** [comment]
@simplelife201008 Your method works for me. But I have to do the following things when modifying xml files: 1) replace backslashes(\\) with slashes(/); 2) add 'file:///' before the paths.
However, I don't like the absolute paths.

**Comment by hefanbo** [comment]
@rahmanusta Could you tell me how to replace 'Arial' with 'Arial Unicode MS'?

**Comment by rahmanusta** [comment]
@hefanbo You can update fo-pdf like in master branch. https://github.com/asciidocfx/AsciidocFX/blob/master/conf/docbook-config/fo-pdf.xsl#L51-L69

@simplelife201008 Thanks for your detailed informations.

@hefanbo Thanks for your contribution. I didn't know the character issue for AsciidocFX for eastern font sets.

**Comment by hefanbo** [comment]
@rahmanusta Actually it's not working for me. Somehow the Chinese characters are associated with "symbol.font.family". My solution is to modify 'fo-pdf.xsl' file as follows.
1) Add some font that can display Chinese in `<xsl:template name="pickfont-symbol">`
2) Uncomment `<xsl:param name="symbol.font.family">`

Here is the patch.
```xml
diff -rupN a/fo-pdf.xsl b/fo-pdf.xsl
--- a/fo-pdf.xsl	Tue Aug 11 08:27:38 2015
+++ b/fo-pdf.xsl	Tue Sep  1 19:06:53 2015
@@ -65,7 +65,7 @@
     </xsl:template>
 
     <xsl:template name="pickfont-symbol">
-        <xsl:text>Symbol,ZapfDingbats</xsl:text>
+        <xsl:text>[some font that can display Chinese, such as SimSun, SimHei, KaiTi, Arial Unicode MS],Symbol,ZapfDingbats</xsl:text>
     </xsl:template>
 
     <!--
@@ -88,11 +88,11 @@
     <xsl:param name="dingbat.font.family">
       <xsl:call-template name="pickfont-dingbat"/>
     </xsl:param>
+    -->
 
     <xsl:param name="symbol.font.family">
       <xsl:call-template name="pickfont-symbol"/>
     </xsl:param>
-    -->
 
     <xsl:param name="title.font.family">
         <xsl:call-template name="pickfont-serif"/>
```

**Comment by rahmanusta** [comment]
Can you try RC6 ? https://github.com/asciidocfx/AsciidocFX#how-to-install-asciidocfx

**Comment by hefanbo** [comment]
It works now! Great work!
