### ISSUE TITLE
Suggestion: provide an offline version

### ISSUE THREAD

**Issue by hefanbo** [asciidocfx/AsciidocFX#139]
As MathJax are fetched from CDN, math equations cannot be displayed without internet connection. What about providing an offline version so that all features are available even if there is no internet connection?

**Comment by rahmanusta** [comment]
Cause Mathjax dependencies size is a few larger, I didnt embed it to afx directly. But, we can give an option for users to select local copy of Mathjax in their system. What do you think for that?

**Comment by hefanbo** [comment]
That would be great!

**Comment by rahmanusta** [comment]
We embedded Mathjax dependencies as local, can you try RC6 ? https://github.com/asciidocfx/AsciidocFX#how-to-install-asciidocfx

Also you can change Mathjax path if you need in Location Settings page (Press F4)

**Comment by hefanbo** [comment]
It works! Thank you!

**Comment by RoyiAvital** [comment]
Why isn't MathJax extension works in MarkDown?
