### ISSUE TITLE
Icons in PDF output stretched to page width

### ISSUE THREAD

**Issue by i-ghost** [asciidocfx/AsciidocFX#141]
Hi,

So I've been trying to get inline icons to behave with Asciidox FX. HTML output works fine, but PDF output leaves me with the following:

test.adoc:
```
= Lorem Ipsum
:doctype: article
:encoding: utf-8
:lang: en
:imagesdir: images
:icons: icons
// override font awesome icons with our own
// icon path becomes ./images/icons/

Donec a leo a dui eleifend condimentum. icon:pencil[] Praesent vulputate condimentum felis finibus congue. Nam blandit consectetur hendrerit.

Sed nec risus semper, accumsan magna facilisis, blandit lorem. icon:calendar[] Nullam eget dui a erat facilisis placerat. Vivamus at aliquam mi, et semper nisl.
```

test.pdf:
![lorem](https://cloud.githubusercontent.com/assets/2255046/9813894/755f5560-5881-11e5-8826-954e863f3ea8.png)

The icons are 16x16 PNG files.

![calendar](https://cloud.githubusercontent.com/assets/2255046/9814071/0100c288-5883-11e5-9b38-3c22751f0610.png)
![pencil](https://cloud.githubusercontent.com/assets/2255046/9814070/00fe0cf0-5883-11e5-8e87-e595c8f50c7e.png)

I noticed a similar problem in #119 however passing "scaledwidth" with a value has no effect here.

Interestingly, if I generate a Docbook using Asciidoc FX and then build the PDF using the `fopub` tool in https://github.com/asciidoctor/asciidoctor-fopub the icons are rendered at their correct size. Could there be a misconfiguration in the toolchain included in Asciidoc FX?

**Comment by rahmanusta** [comment]
Hi @i-ghost ;

Could you try adding :apply-image-size: attribute to your document or docbook settings page?

If it doesn't work, please ping me again

**Comment by i-ghost** [comment]
Hi @rahmanusta,

Adding the `:apply-image-size:` attribute made no difference in the generated PDF unfortunately. I did this:

test.adoc:
```
= Lorem Ipsum
:doctype: article
:encoding: utf-8
:lang: en
:imagesdir: images
:icons: icons
:apply-image-size:
// override font awesome icons with our own
// icon path becomes ./images/icons/

Donec a leo a dui eleifend condimentum. icon:pencil[scaledwidth=10%] Praesent vulputate condimentum felis finibus congue. Nam blandit consectetur hendrerit.

Sed nec risus semper, accumsan magna facilisis, blandit lorem. icon:calendar[scaledwidth=10%] Nullam eget dui a erat facilisis placerat. Vivamus at aliquam mi, et semper nisl.
```
 and this:

![capture](https://cloud.githubusercontent.com/assets/2255046/9814916/ebb62ce0-5889-11e5-98b2-77c2ccb4bd3a.PNG)

both with and without the "scaledwith=10%".

**Comment by rahmanusta** [comment]
@i-ghost Sorry, we didnt implemented image-size-info for icons yet, before next release you can use like that ? icon:adjust[height=16], What do you think for that?

**Comment by i-ghost** [comment]
Hi @rahmanusta,

Yes that seems to work fine, although it will force the icon to take most of the line spacing.

![capture](https://cloud.githubusercontent.com/assets/2255046/9817650/154db458-589c-11e5-90d9-68fba3f933d6.PNG)

However if it's something that will be addressed in the next release then I can wait. I'll consider this closed; thanks.

**Comment by rahmanusta** [comment]
What about line spacing in fopub @i-ghost  ? same or different?

**Comment by i-ghost** [comment]
As requested @rahmanusta, running Asciidoc FX's docbook XML through `fobub` with or without "height=16":

![capture](https://cloud.githubusercontent.com/assets/2255046/9817856/4e700d8e-589d-11e5-9d96-ccd60edac7f0.PNG)

The spacing and behaviour is correct.

**Comment by rahmanusta** [comment]
Thanks @i-ghost , we will solve this issue.

**Comment by rahmanusta** [comment]
@i-ghost Could you try v1.3.8 https://github.com/asciidocfx/AsciidocFX

**Comment by i-ghost** [comment]
@rahmanusta 

That fixed the issue. Thanks for the speedy fix. :)

test.adoc:
```
= Lorem Ipsum
:doctype: article
:encoding: utf-8
:lang: en
:imagesdir: images
:icons: icons
// override font awesome icons with our own
// icon path becomes ./images/icons/

Donec a leo a dui eleifend condimentum. icon:pencil[] Praesent vulputate condimentum felis finibus congue. Nam blandit consectetur hendrerit.

Sed nec risus semper, accumsan magna facilisis, blandit lorem. icon:calendar[] Nullam eget dui a erat facilisis placerat. Vivamus at aliquam mi, et semper nisl.
```

now produces this as expected:

![capture](https://cloud.githubusercontent.com/assets/2255046/9846863/1b0ebe36-5acd-11e5-81e3-35005e9bd6b1.PNG)
