### ISSUE TITLE
HTML: support for the :data-uri: attribute

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#143]
The :data-uri: attribute is currently not supported by AsciidocFX.

* http://asciidoctor.org/docs/render-documents/

```
 My First Experience with the Dangers of Documentation
:imagesdir: myimages
:data-uri:

In my world, we don't have to worry about mutant, script-injecting warlocks.
No.
We have something far worse.
We're plagued by Wolpertingers.

== Origins

[.left.text-center]
image::wolpertinger.jpg[Wolpertinger]
```

When saving a document as HTML using HTML menu option "Save" or "Save as, images cannot be embedded as Base64 encoded strings inside the HTML document.

Is support for the :data-uri: attribute planned?

**Comment by rafik777** [comment]
+1

**Comment by rahmanusta** [comment]
Could you please try version 1.4.5 ? https://github.com/asciidocfx/AsciidocFX/releases

@rafik777 @wfouche

**Comment by wfouche** [comment]
@rahmanusta 

All i can say is, wow! Thanks for implemeting the data-uri feature.

Other's might find the following useful. This is how the start of all my documents are defined for use with AsciidocFX 1.4.5.  :data-uri: to create a self-contained HTML file and :toc!: to ensure that Table Of Contents information is not displayed in tables in the document (workaround for bug in Asciidoctor 1.5.3-beta?).

````
= Document Title
:sectnums:
:toc: left
:toclevels: 3
:data-uri:

:toc!:

= Section 1

= Section 2
````
