### ISSUE TITLE
Chinese fonts in generated PDF

### ISSUE THREAD

**Issue by Alsan** [asciidocfx/AsciidocFX#146]
I'm a chinese user, and tried to conver a doc into pdf through this tool, but all chinese inside the doc becomes unreadable. So, what can I do?

**Comment by rahmanusta** [comment]
@Alsan Which version of AsciidocFX and OS are you using?

**Comment by LumenAstralis** [comment]
AsciidocFX v1.3.8, Win8.1, same issue.  All Chinese characters in PDF files appear as ####.  No problem in preview, HTML and browser.

**Comment by LumenAstralis** [comment]
Modifying conf/docbook-config/fo-pdf.xsl by adding to <xsl:template name="pickfont-symbol">
as outlined by hefanbo in issue #138 seems to work.  I use PMingLiU, but I imagine any other zh-tw/zh-cn fonts will work too.

**Comment by Alsan** [comment]
Sorry, I just forget about this thread.

Thanks @LumenAstralis, your solution works fine.
