### ISSUE TITLE
:imagesdir: not following relative paths in preview + other strange behaviour

### ISSUE THREAD

**Issue by i-ghost** [asciidocfx/AsciidocFX#147]
Hi,

I've discovered that Asciidoc FX will not display images in the preview pane if the `:imagesdir:` attribute is set to a relative path.

This is the structure: 

![example](https://cloud.githubusercontent.com/assets/2255046/9998447/0aa95b84-6089-11e5-8e0f-069bc575d694.png)

`chapter-01.adoc:`

```
=== Some header
:doctype: article
:encoding: utf-8
:imagesdir: ..\images

image::image.png[]
```

This will not render in the preview pane/browser if the images directory is stored one directory level above `chapter-01.adoc`. The actual document renders fine if using one of the export options or `asciidoctor`, so it seems the underlying tools respect the relative path.

However, if we do this
`chapter-01.adoc`

```
=== Some header
:doctype: article
:encoding: utf-8
:imagesdir: images

image::image.png[]
```

And then navigate Asciidoc FX to the root of the project _and_ make a change to the document to force the preview to reload, the image is rendered fine.

Is there some special setting I can set to enable the correct behaviour?

**Comment by rahmanusta** [comment]
@i-ghost Sure, that is an known issue for AsciidocFX. .. (parent) directive is not working now, but I'm working on that, and will be resolved in further release.

**Comment by i-ghost** [comment]
Thanks for the information! :)

**Comment by rahmanusta** [comment]
@i-ghost Could you try v1.3.9 ?

**Comment by i-ghost** [comment]
@rahmanusta It works fine in that release now, thanks!

**Comment by eshepelyuk** [comment]
It seems that in latest release `1.4.0` `imagesdir` attribute is not taking into account at all.
Preview window displays pictures only when full relative / absolute path is defined.

**Comment by rahmanusta** [comment]
@eshepelyuk I tried but it seems running, could you please give more detail for your tested document?

**Comment by rahmanusta** [comment]
Please try version 1.4.6 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.6
