### ISSUE TITLE
Disappearance problem with undo

### ISSUE THREAD

**Issue by hakdogan** [asciidocfx/AsciidocFX#148]
This issue arises during the process of undo(cmd+z) in saved file.  I hope this video help you to understand the issue: http://quick.as/dwyqtb1jw

AsciidocFX version: 1.3.8 (Actually, I encountered this problem in previous versions.)
OS: Yosemite 10.10.5

**Comment by rahmanusta** [comment]
This issue fixed in https://github.com/asciidocfx/AsciidocFX/commit/d2c1154b9b8435ee1468c86809dc51143995b4c8 , and will be available in further release. Before next release, you can use Command + Y after seeing empty editor. Thanks for the contribution!

**Comment by hakdogan** [comment]
You're welcome. I know the command(cmd + y) I just wanted to let the undo issue.

Thanks.

**Comment by rahmanusta** [comment]
:+1:

**Comment by rahmanusta** [comment]
@hakdogan This is solved in v1.3.9, please update to this version

**Comment by hakdogan** [comment]
Good news. 👍
