### ISSUE TITLE
Links opened in preview, not external browser

### ISSUE THREAD

**Issue by madmas** [asciidocfx/AsciidocFX#151]
If I have a link in my document and click on it in the preview pane, it is opened within the preview pane. I would've expected that it is opened in my browser so that I can contiue to use the preview pane for previews of my currently edited document ;-)
Using AsciiDocFx 1.3.8 on MacOSX 10.10.5

**Comment by rahmanusta** [comment]
Hey @madmas you can use Go back in preview pane to turn back, but if it is not enough for you, I can try to implement different behaviour for links.

**Comment by manueljordan** [comment]
HI @rahmanusta 

Interesting his request. But just curious if the tab page of the live preview can be open how a new window. It to let me move it to a secondary monitor or screen. Let me know if is possible, if not I would create an issue request for that.

Kind Regards...

**Comment by madmas** [comment]
@rahmanusta thank you for the fast response, and of course it works. but as it does not seem to be obvious to the user (I didn't check the context menu initially ;-) ), I think opening link in an external browser would improve the usability here....

**Comment by rahmanusta** [comment]
Thank you @madmas maybe I can try to show a tooltip for users when mouse over link.
