### ISSUE TITLE
AsciidocFX v1.3.8 Windows .exe installer does not install on Windows 8 64bits

### ISSUE THREAD

**Issue by manueljordan** [asciidocfx/AsciidocFX#152]
Hello 

I have

- Java 8 u 60
- Windows 8 64 bits

With the following installer:

- AsciidocFX_Windows.exe (v1.3.8)

In command (even without command):

```
D:\>AsciidocFX_Windows.exe

D:\>
```

Always shows this image (Even if I execute in C)

![one](https://cloud.githubusercontent.com/assets/2552795/10345470/7a43e104-6cef-11e5-802e-e8ee35a3b4f9.png)

I don´t get some kind of error stack trace.

I only can install using the .zip file version. I can´t use the .exe installer.

What is wrong?

**Comment by rahmanusta** [comment]
@manueljordan  Did you try to execute in Admin mode ?

**Comment by manueljordan** [comment]
No, I just have open the command window, and execute the .exe file. 

But I confirm it is due the lack of permissions just after to enter to the C:\Windows\Temp
when the OS show a warning window about it requires admin permission, after to say Yes. All works fine now.

**Comment by rahmanusta** [comment]
Thank you @manueljordan It may be about install4j settings, I will review its options.

**Comment by manueljordan** [comment]
No problem @rahmanusta . The error image was not clear. 

Therefore, for this case an error about lack of writing permissions would be better.
