### ISSUE TITLE
list markdown not rendered correctly

### ISSUE THREAD

**Issue by sibay** [asciidocfx/AsciidocFX#154]
When writing a list in markdown, the list doesnt 'end' in the preview pane and in the browser view. For example, if you write markdown like this:
```
dummy text

1. numbered item one
2. numbered item two

text after list still on same line with 'item two'
```

the text is displayed on the same line as the last list item.

**Comment by rahmanusta** [comment]
@sibay Seperate them with // or add :hardbreaks: attribute to document;

```
:hardbreaks: // this

dummy text

1. numbered item one
2. numbered item two

// this

text after list still on same line with 'item two'
```

We actually dont interest in Markdown, I can suggest to use AsciiDoc instead.

**Comment by sibay** [comment]
ok, thanks for the info. i will use AsciiDoc.
