### ISSUE TITLE
Mark selection on right column within asciidoc document

### ISSUE THREAD

**Issue by maybeec** [asciidocfx/AsciidocFX#16]
Thanks for your smooth and nicely usable editor. This is a feature request for improving usability:

I would be nice to easily find the position of some text read in the right column within the asciidoc code. I could imagine to select some text in the right column or simply click at a line and on the left column I would get the text or line highlighting, which contains the asciidoc of the current selection in the final document.

Would that be possible?

**Comment by rahmanusta** [comment]
@may-bee this feauture is now included

**Comment by may-bee** [comment]
Wow great job! Thanks, I will test it soon :)

**Comment by rahmanusta** [comment]
Actually, it was working from v1.3.9 :) I forgot to say it :)
