### ISSUE TITLE
shift-insert shortcut is not bound to "paste"

### ISSUE THREAD

**Issue by prof7bit** [asciidocfx/AsciidocFX#160]
when pressing shift-insert it should paste the clipboard contents, just like Ctrl-V.

Many people (like me for example) are used to the much more accessible shift-del and shift-ins keyboard shortcuts to control the clipboard instead of ctrl-c/x/v, simply because it does not require moving the hands across the keyboard and rearranging the fingers when already using left shift (left hand) and up/down/left/right/pos1/end (right hand) to move the cursor around the document and select portions of text.

Most text editors and word processors have bound these two clipboard functions to these two key combinations and now I have become so used to it that everytime I want to copy (or cut) a couple of lines in AsciidocFX I will cut them with shift-del and then 200 milliseconds later I realize I cannot insert them back again with shift-ins which forces me to rearrange my hands to a seldomly used (by me) position to execute a ctrl-v instead.

Please implement this keyboard shortcut. Shift-del is already working as expected, now all that is missing is its counterpart shift-insert.

**Comment by rahmanusta** [comment]
@prof7bit Yes, we should implement it.
