### ISSUE TITLE
Can't find pdf after conversion: New version bug?

### ISSUE THREAD

**Issue by Fjasmine** [asciidocfx/AsciidocFX#161]
Newbie here, thanks for your patience. I'm on Windows 10 and I've been using AsciidocFX to convert .adoc s to pdf s. Just now updated to newest version of AsciidocFX, and now, after I save as pdf and close the program, my pdf is nowhere to be found. It's listed in my recent files, but the link leads to a "can't find" error.
Could this be a bug with the new version? Any idea how I can get around it?
Thanks!

**Comment by rahmanusta** [comment]
@Fjasmine Do you have any error report while converting ?

**Comment by Fjasmine** [comment]
No. Just when I try to open the pdf listed in my "recent files." Then it says file can't be found. 
BTW, the pdf appears in my list of recenty-used files, but it does NOT appear in my file folders themselves.

**Comment by rahmanusta** [comment]
Are you seeing PDF conversation ended message in log list?

**Comment by Fjasmine** [comment]
ok, you got me there. Where would I find that log list? 
Is it the list of Recent Files in lower left of AsciidocFX screen?

**Comment by rahmanusta** [comment]
Log list is under the editor column.

![loglist](https://cloud.githubusercontent.com/assets/1158804/10837713/f8a4a93e-7e79-11e5-82ea-2dea5c041c7a.png)

**Comment by Fjasmine** [comment]
Tx. There IS an error message there:
"Please fix Docbook validation error LineNumber: 272, column: 37"
Then a bunch of code.

**Comment by rahmanusta** [comment]
Yes, follow the line number in docbook and find asciidoc section belong to it. There is a syntax error. If you can send the document, I can fix it also.

**Comment by Fjasmine** [comment]
We found the error in the asciidoc file and fixed it! 
it was here: <simpara><literal>grep -r <emphasis>searchterm</emphasis> .</literal></simpara>
wrong emphasis, took out  the code apostrophe.

thank you so much for all your time, patience, and insight!

**Comment by rahmanusta** [comment]
It is perfect!!
