### ISSUE TITLE
Reordering of outline items

### ISSUE THREAD

**Issue by aladagemre** [asciidocfx/AsciidocFX#163]
Scrivener app has a nice feature: You create subsections (displaying it individually) and then reorder them as you wish in the outline tree. Dragging and dropping items, creating new items/logical folders are possible.

When writing book or academic article, this feature becomes useful. You create an outline in a tree form with notes (sections) with titles in this outline. Then you fill in the subsections. You focus on one section at a time and you can display the whole section or document if you wish.

Such a feature could come handy if it's not too hard.

**Comment by rahmanusta** [comment]
Thank you @aladagemre for feature suggestion. I like it but didn't try this feature in any editor yet. We can impelement it if its turn to come.
