### ISSUE TITLE
Editor Name

### ISSUE THREAD

**Issue by cortix** [asciidocfx/AsciidocFX#164]
How can I add editor name to down below the author name??? Is there any option to add this?

**Comment by ozlerhakan** [comment]
Hi @cortix ,
Have you tried to add another name next to the author using semicolon like below? 

```
= Book Name
Author Name; Editor X Name
:doctype: book
:encoding: utf-8
:lang: en
.....
```
this approach should add another name down below the author name in a docbook, I hope that helps.

**Comment by gernotstarke** [comment]
You can define arbitrary variables between colons (:), like shown below for :author: and :editor:

    = Book Name
    :author: UnknownAuthor
    :editor: FamousEditor

    :email: gernot.starke@innoq.com
    :date: {docdate}
    
     {author}, {email}
     {editor}

     last change: {docdate}

renders as shown in the image below:
![asciidocfx_-__users_gstarke](https://cloud.githubusercontent.com/assets/1233990/12073905/71ac33b6-b137-11e5-913d-87895e536351.jpg)

**Comment by rahmanusta** [comment]
@cortix Do you think this issue is solved?

Thank you @gernotstarke
