### ISSUE TITLE
AsciidocFX takes over 100% of CPU under OS X 10.11.1

### ISSUE THREAD

**Issue by wildchildEric** [asciidocfx/AsciidocFX#165]
![2015-11-04 10 51 01](https://cloud.githubusercontent.com/assets/567213/10941514/c54f432e-8346-11e5-9302-22c92845d9e7.png)

**Comment by rahmanusta** [comment]
Could you test with a Java profiler where is the cost?

**Comment by rahmanusta** [comment]
@wildchildEric Could you test latest release?
