### ISSUE TITLE
Incompatibilities with some Java 8 updates

### ISSUE THREAD

**Issue by pjBooms** [asciidocfx/AsciidocFX#168]
I found that AsciidocFX runs well with the latest Java 8 microversion (Update 66) but has issues with some previous microversions:
- It simply does not run on Java 8 Update 20:

1913 [JavaFX Application Thread] ERROR o.s.boot.SpringApplication - Application startup failed 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springAppConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.kodcu.controller.ApplicationController com.kodcu.boot.SpringAppConfig.applicationController; nested exception is java.lang.NoClassDefFoundError: javafx/scene/control/TextInputDialog
.....
Caused by: java.lang.NoClassDefFoundError: javafx/scene/control/TextInputDialog
- throws exceptions with Java 8 Update 45:

netscape.javascript.JSException: netscape.javascript.JSException: RangeError: Maximum call stack size exceeded.
    at com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source)
    at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
    ... 29 more
java.lang.NullPointerException
    at com.sun.javafx.Utils.getScreen(Unknown Source)
    at com.sun.javafx.webkit.WebPageClientImpl.getScreenBounds(Unknown Source)
    at com.sun.webkit.WCWidget.fwkGetScreenRect(Unknown Source)
java.lang.NullPointerException
    at com.sun.javafx.Utils.getScreen(Unknown Source)
    at com.sun.javafx.webkit.WebPageClientImpl.getScreenBounds(Unknown Source)

**Comment by rahmanusta** [comment]
Hey @pjBooms I'm excited you tried AsciidocFX in Java Embedded. Did you try it on Raspberry PI ?

NoClassDefFoundError: javafx/scene/control/TextInputDialog

When we look at above line , TextInputDialog class is needed by application and this class is available after JDK 1.8U40 above.

So AsciidocFX depens on jdk1.8 update 40 +

**Comment by pjBooms** [comment]
Hum, why do you think that I tried it for Java Embedded?
Actually I work for Excelsior -- Excelsior JET makers. Exceslior JET is JVM with AOT compiler for desktop platforms. Now, I am developing Maven plugin for Excelsior JET -- https://github.com/excelsior-oss/excelsior-jet-maven-plugin (will be published to Maven Central soon).

So I've tested the plugin with your project. Generally, it just works with just copy&paste of 8 lines into your pom.xml (and commenting appassembler-maven-plugin as it produces huge jar that is not needed for running), however as Excelsior JET supports Java 8 Update 40 only for now it has the same problem as Oracle JRE 8 Update 40 (the same problem as I mentioned above for Java 8 Update 45 with netscape.javascript.JSException: netscape.javascript.JSException)

It is not problem as we are going to support Java 8 Update 65 soon.

The plugin will also need some tweaks to work well with your project such as copying of "conf" directory to the final package. I have also found that you look for "conf" directory in the upper directory of AsciidocFX.jar directory  (it is quite strange relying) that also does not work well with the plugin. Anyway, it is good test for the plugin anyway :).

**Comment by rahmanusta** [comment]
Hmm, What you mean with "microversions", I understand it as Java embedded :)

It is cool, I'm using install4j for multiplatform installer, I see your project is a bit like that. If your project support cross-compilation then I can use it.

Because we are accessing conf folder in filesystem not in jvm directly.

**Comment by rahmanusta** [comment]
Does your product give me performance improvement??

**Comment by pjBooms** [comment]
"microversion" is old notation for "update". 
Unfortunately, Excelsior JET does not support cross-compilation, you need to build the app for each platform separately.
We are going to support cross-compilation but it is not easy as we really compile Java bytecode to native code and link it with the target platform native libraries. It is possble to support but not easy.

You may expect performance improvements of course especially for UI stuff, and startup time improvements for sure.

 And the final native package can be smaller (by means of Java Runtime Slim Down technology -- http://www.excelsiorjet.com/solutions/java-download-size).

**Comment by rahmanusta** [comment]
I want to evaluate excelsior jet, but it has u40 profile, how can use different jdk for example u65 or u66 ?

**Comment by pjBooms** [comment]
Java Updates are supported in Maintanence Packs of Excelsior JET. Java Update 65 support is scheduled for the beginning of December.

**Comment by rahmanusta** [comment]
How can use Maintanence Packs of Excelsior JET ? Is it private yet ?

**Comment by pjBooms** [comment]
It is not issued yet :). Supporting of Java updates is a development process for us.

**Comment by rahmanusta** [comment]
Ok guy, I look forward to try it :)

**Comment by rahmanusta** [comment]
I tried jet with tag v1.3.6, it works with jdk 1.8 u40. But, I unfortunately didn't feel any performance differrence

**Comment by pjBooms** [comment]
What OS/CPU have you tried? I recommend to try Windows 32-bit and enable global optimizations there (SMART preset on Page Classpath of JET Control Panel).

**Comment by rahmanusta** [comment]
Windows 7 x64, i5 3210M . I will try again with jet's 32 bit version again with global optimizations.
