### ISSUE TITLE
Maven integration

### ISSUE THREAD

**Issue by pswvg** [asciidocfx/AsciidocFX#169]
I just took a look at asciidoc and how to integrate document generation to PDF/HTML via the asciidoctor maven plugin: http://asciidoctor.org/docs/asciidoctor-maven-plugin/.

Then I stumbled over asciidocfx and I'm impressed what powerful extensions it brings (charts, UML diagrams etc.). Of course now I'm wondering, whether any maven integration is planned for automatically generate different documentation from the asciidoc - including the extensions. It looks like asciidocfx has everything it needs for auto-generating the documentation.

**Comment by rahmanusta** [comment]
Thank you guy, yes we can write a maven-plugin for asciidocfx

**Comment by pswvg** [comment]
That would be awesome :)!

**Comment by sikron** [comment]
i second that! :-) 
:+1:

**Comment by mscookies** [comment]
:+1:

**Comment by manzke** [comment]
👍

**Comment by sbeaupre** [comment]
:thumbsup:

**Comment by AndyGee** [comment]
Think support for uml & plantuml already means that the existing plugins would work:

https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-diagram-example

eg. [uml,my.png] & [plantuml,my,png]

`<plugin>
          <groupId>org.asciidoctor</groupId>
          <artifactId>asciidoctor-maven-plugin</artifactId>
          <version>${asciidoctor.version}</version>
          <dependencies>
            <dependency>
              <groupId>org.asciidoctor</groupId>
              <artifactId>asciidoctorj-diagram</artifactId>
              <version>${asciidoctorj-diagram.version}</version>
            </dependency>
`
