### ISSUE TITLE
Cancel an Redo

### ISSUE THREAD

**Issue by fpinjava** [asciidocfx/AsciidocFX#170]
Hi,

Thanks for this great software. This is really a wonderful tool, although for me, it has several minor problems.

The most missing feature in my opinion is a Cancel command. (And redo would of course be fine to). But the main problem is that although not listed in the doc, Cmd + Z (on a Mac) shuts the current document without any confirmation being asked. (Fortunately, it saves the current state, although this could be unfortunate if this is not what is wanted.) More generally, AsciidocFX lacks the standard interface (menu bar and so on).

**Comment by rahmanusta** [comment]
Hi @fpinjava ;

Thanks for nice words and suggestions. I didn't know Cmd + Z shuts down the application. What kind of keyboard are you using ? AsciidocFX saves the documents automatically when closing the app or focusing-out the app. This behaviour comes from Intellij IDEA's saving strategy.

Actually we dont have a complex menubar. But, I'm open to all suggestions. What is the most menu actions you need and suggest for AsciidocFX ?

Thanks.

**Comment by fpinjava** [comment]
I am using a French keyboard with numeric pad. 

A menu bar is interesting because it is like a help system where you can find which commands are available. Anyway, this is much less important than having a an Undo command (I incorrectly called it Cancel).

I have other suggestions:

- I would prefer the Hide File Browser command to be similar to the button used to show the File browser, for example letting the button in place, making it a toggle control.

- It would be great to have the source pane scrolling when you scroll the preview pane.

- When pasting from LibreOffice, the html representation of the text is pasted. It should be raw text, or better, the asciidoc translation.

- Pasting from IntelliJ, on the other hand, is converted to asccidoc code bloc. This is ok when pasting into text, but not when pasting inside a code block, which results in nested code blocks.

- Numbering chapters don't work, but I suppose this is an asciidoc bug.

**Comment by rahmanusta** [comment]
Thank you @fpinjava ;

> I would prefer the Hide File Browser command to be similar to the button used to show the File browser, for example letting the button in place, making it a toggle control.

Yes, I'm working on new UI scheme for increasign flexibility

> It would be great to have the source pane scrolling when you scroll the preview pane.

When you click right side elements, editor will find related Asciidoc component, but we can improve this feature like you said.

> When pasting from LibreOffice, the html representation of the text is pasted. It should be raw text, or better, the asciidoc translation

For raw paste, you should use Ctrl+Shift+V

> Pasting from IntelliJ, on the other hand, is converted to asccidoc code bloc. This is ok when pasting into text, but not when pasting inside a code block, which results in nested code blocks.

Yes, we can fix it

> Numbering chapters don't work, but I suppose this is an asciidoc bug.

For numbering you should add :numbered: attribute to document header.
