### ISSUE TITLE
missing icons in AsciidocFX

### ISSUE THREAD

**Issue by DanielGrigoras** [asciidocfx/AsciidocFX#171]
Why are the [NOTE] icons missing/not shown in the document I work in, while they are present in the opened cheatsheet.adoc.

![missing icons in asciidocfx](https://cloud.githubusercontent.com/assets/15011993/11532431/67b9e832-990c-11e5-8104-b5edc485919f.png)

**Comment by rahmanusta** [comment]
Hi @DanielGrigoras , which version of AsciidocFX are you using? I tried but I see the icons, could you please share a snippet of document to test it ?

THanks

**Comment by DanielGrigoras** [comment]
Hi Rahmanust,

I'm using the latest version, i.e. 1.4.1 and I am totally new to Asciidoc and AsciidocFX.
I now saw that when I produce the PDF, an icon is indeed assigned for notes, despite it not being displayed by AsciidocFX (see bellow). However, as you can see bellow, a different icon is displayed for notes than the one displayed in the cheatsheet.
How could I use the FontAwesome icons and colours as in the cheatsheet?

Regards,
Daniel

![missing icons in asciidocfx 2](https://cloud.githubusercontent.com/assets/15011993/11538024/91c84b3e-9928-11e5-8a04-5adad3a3b341.png)

**Comment by DanielGrigoras** [comment]
Hm, quite interesting.
For some reason I now see that the blue FontAwesome icon is displayed for notes in AsciidocFX, unlike before. 
The only issue is that there is now WYSIWYG when producing the PDF, that is, the black pen and paper icon is used in the PDF instead of the white i in a blue circle.
Really weird.

**Comment by DanielGrigoras** [comment]
Aha, I found the cause.
In order to have AsciidocFX display icons for the notes I have to type ":icons: font" at the beginning of the document, instead of just ":icons:".

How could I get the title printed on a separate page, i.e. on the first page? I did not see any page brake options in asciidoc.

**Comment by rahmanusta** [comment]
You can replace the admonition images here https://github.com/asciidocfx/AsciidocFX/tree/master/conf/docbook/images

**Comment by DanielGrigoras** [comment]
That would mean changing the icons for all users, which is not right. One should be able to use what suits him best.
A good thing would be if I were to be able to tell AsciidocFX what icons to use for what from a font file like FontAwesome.

**Comment by rahmanusta** [comment]
You can use

:doctype: book

for producing title in first page.

You can change admonitions icons instead of using FontAwesome but not for PDF for now

**Comment by DanielGrigoras** [comment]
Thanks!
Hopefully in the next version of AsciidocFX one will be able to choose for the PDF version the icons one prefers from a font like FontAwesome.
