### ISSUE TITLE
TOC printed in appendix B without specifying this

### ISSUE THREAD

**Issue by DanielGrigoras** [asciidocfx/AsciidocFX#172]
I don't understand why in the PDF version a table of contents (TOC) is inserted in Appendix B, immediately after the title of Appendix B.

Additional information: this does not happen in Appendix A; appendix B has to subsections: B1 and B2.

**Comment by rahmanusta** [comment]
Could you share a sample adoc and pdf file to see and test it.

**Comment by wfouche** [comment]
I've seen a similar error with 1.4.2 when using the following document fragment:

```
= AsciidocFX 1.4.2
:toc:

[cols="1,5a"]
|===

| A | B

| A 
| 
* abc
* def

|===
```
 It is displayed as:

![adfx142_toc](https://cloud.githubusercontent.com/assets/13682850/11558344/e64f3e3c-99ba-11e5-9765-8f48fa7e2315.png)

**Comment by DanielGrigoras** [comment]
Hi Rahmanusta,

Please find attached an asciidoc test document, which is anonymized version of the document I am working on. The package also contains a source image and the PDF version. The file is a zip file, but I have changed the extension to .txt because it seems that github does not allow attaching zip files.

You will see on page 17 that a TOC is inserted right after the title of Appendix B.
Also, please note the empty pages inserted before and after the good TOC inserted on page iii.
Moreover, for some unknown reason another empty page is inserted right after page 3.
Furthermore, the image on page 5 is for some reason shrank inconveniently, despite specifying for it a width of 400 pixels in the asciidoc source file. Also, another empty page is inserted right after page 5.

I also would have liked to have the long list on page 11 placed on two or three columns, without the use of a table, but I could not see this being a feature of asciidoc.

Best wishes,
Daniel
[Test_document.zip.txt](https://github.com/asciidocfx/AsciidocFX/files/50721/Test_document.zip.txt)

**Comment by rahmanusta** [comment]
Please follow the link to see workaround asciidoctor/asciidoctor#1582
