### ISSUE TITLE
AsciidocFX 1.4.2 - "Table of Contents" appearing in table body.

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#173]
The following table is incorrectly rendered in AFX 1.4.2

```
= AsciidocFX 1.4.2
:toc:

[cols="1,5a"]
|===
| A | B

| A 
| 
* abc
* def

|===
```

as

![adfx142_toc](https://cloud.githubusercontent.com/assets/13682850/11560263/f4407e04-99c7-11e5-9bd4-9abec7957e86.png)

**Comment by rahmanusta** [comment]
I want to ask you this issue to Asciidoctor team. @mojavelinux @Mogztter Is it a bug ?

**Comment by wfouche** [comment]
The following table is correctly rendered in AFX 1.4.0
```
= AsciidocFX 1.4.0
:toc:

[cols="1,5a"]
|===
| A | B

| A 
| 
* abc
* def

|===
```
as

![adfx140_toc](https://cloud.githubusercontent.com/assets/13682850/11562554/4728cc84-99d7-11e5-896f-9a544f34aa23.png)

**Comment by Mogztter** [comment]
What is the difference between AsciidocFX 1.4.0 and 1.4.2 ?
Are you using Asciidoctor.js through Nashorn or Asciidoctorj ?

**Comment by rahmanusta** [comment]
@Mogztter I switched to Asciidoctor.js  v1.5.3-preview.4  in v1.4.1+ , I disabled the Nashorn extension for now, it works on WebWorker.

**Comment by mojavelinux** [comment]
This is a known issue with AsciiDoc table cells in 1.5.3 if the toc is
enabled. There's an open issue in core with a workaround.

**Comment by rahmanusta** [comment]
Thank you @Mogztter and @mojavelinux .

@wfouche Please follow the link to see workaround https://github.com/asciidoctor/asciidoctor/issues/1582

**Comment by wfouche** [comment]
Thanks for the workaround! Testing now with 1.4.3, works great.

**Comment by wfouche** [comment]
@rahmanusta 

The freshly released Asciidoctor 1.5.4 resolves this issue without requiring the :toc:! workaround.

https://github.com/asciidoctor/asciidoctor/commit/9d116e52e9caec9f49ff030e2e0f9e5a37c58c0e

![image](https://cloud.githubusercontent.com/assets/13682850/12114032/774ba4e4-b3af-11e5-9ab9-e1dbeaba9b8a.png)

Upgrading to Asciidoctor.js v1.5.4 would resolve this issue in AsciidocFX.

**Comment by mojavelinux** [comment]
:+1:

**Comment by rahmanusta** [comment]
Yes @wfouche , we will use it in next version :+1:

**Comment by mojavelinux** [comment]
We're working on the Asciidoctor.js 1.5.4 release now. @rahmanusta you might be interested to know that extension will now be able to resolve absolute file:/// paths, which should help with the chart extension.

**Comment by rahmanusta** [comment]
Thank you @mojavelinux for informing me , do we need it in csv loading ?

**Comment by mojavelinux** [comment]
Yes, it's what it needed to load the data for the chart block macro. It was
not resolving the file before.

**Comment by rahmanusta** [comment]
Thanks for this news :+1: AsciidocFX supports chart block (JavaFX charts) but there may be differences according to Asciidoctor (because of input model). But my goal is to adapt extensions fully-compatible with Asciidoctor.

**Comment by wfouche** [comment]
@rahmanusta 

Asciidoctor.js (1.5.4) was released just over a week ago. What are the steps required to incorporate it into AsciidocFX?

* https://github.com/asciidoctor/asciidoctor.js/releases/tag/v1.5.4

I've looked at the scripts in AsciidocFX's public/js folder but it does not seem to be just a copy of the files generated from the Asciidoctor.js build.

**Comment by wfouche** [comment]
Resolved in latest release.
