### ISSUE TITLE
[WORKAROUND] v 1.4.3 DMG will not successfully load on El Capitan after Upgrade

### ISSUE THREAD

**Issue by jaredmorgs** [asciidocfx/AsciidocFX#175]
I've updated in-app from v1.4.0 to v1.4.3 today, and the program will not open. It hangs after you click the icon from LaunchPad. 

To work aroud the issue, completely delete the DMG from your system and reinstall by downloading the DMG from https://github.com/asciidocfx/AsciidocFX/releases/download/v1.4.3/AsciidocFX_Mac.dmg

**Comment by rahmanusta** [comment]
Thank you @jaredmorgs :+1:
