### ISSUE TITLE
[suggestion] [v1.4.3] Include option to hide debug and terminal pane

### ISSUE THREAD

**Issue by jaredmorgs** [asciidocfx/AsciidocFX#176]
When I start AsciiDocFX, the terminal pane and debug pane displays, and takes up about half of the workspace. 

I have to try and find the frame border so I can hide the pane by dragging down.

This is particularly frustrating on Mac (El Capitan) because if you add AsciiDocFX to a workspace, it forgets your view settings and shows the pane again.

I'm happy not to see this pane when working on AsciiDoc content. 

Please allow us to enable or disable this pane from displaying, by adding a user-configurable setting.

**Comment by rahmanusta** [comment]
Hi Jared, 

After running AsciidocFx, is the bottom pane not minimized?

**Comment by jaredmorgs** [comment]
I've just managed to replicate the issue:

Have a monitor connected to your MacBook to replicate the environment.

   1. Start AsciidocFx. The app starts in non-workspace mode (standard
   windowed).
   2. Drag AsciidocFx from non-windowed, built-in display, to Monitor into
   a workspace.
   3. Observe results.

Actual Result

The debug pane displays when the app scales to workspace size.

Expected Result

The debug pane does not display.

On Tue, 8 Dec 2015 at 16:49 Rahman Usta <notifications@github.com> wrote:

> Hi Jared,
>
> After running AsciidocFx, is the bottom pane not minimized?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidocfx/AsciidocFX/issues/176#issuecomment-162792604>
> .
>
-- 

Sent from Mobile.

**Comment by rahmanusta** [comment]
I don't have a Mac sir :) Could you please record a short video to
understand the isseu better.

Thanks
9 Ara 2015 04:02 tarihinde "Jared Morgan" <notifications@github.com> yazdı:

> I've just managed to replicate the issue:
>
> Have a monitor connected to your MacBook to replicate the environment.
>
> 1. Start AsciidocFx. The app starts in non-workspace mode (standard
> windowed).
> 2. Drag AsciidocFx from non-windowed, built-in display, to Monitor into
> a workspace.
> 3. Observe results.
>
> Actual Result
>
> The debug pane displays when the app scales to workspace size.
>
> Expected Result
>
> The debug pane does not display.
>

**Comment by jaredmorgs** [comment]
No problem, I'll do one tomorrow for you.

On Wed, 9 Dec 2015, 17:16 Rahman Usta <notifications@github.com> wrote:

> I don't have a Mac sir :) Could you please record a short video to
> understand the isseu better.
>
> Thanks
> 9 Ara 2015 04:02 tarihinde "Jared Morgan" <notifications@github.com>
> yazdı:
>
> > I've just managed to replicate the issue:
> >
> > Have a monitor connected to your MacBook to replicate the environment.
> >
> > 1. Start AsciidocFx. The app starts in non-workspace mode (standard
> > windowed).
> > 2. Drag AsciidocFx from non-windowed, built-in display, to Monitor into
> > a workspace.
> > 3. Observe results.
> >
> > Actual Result
> >
> > The debug pane displays when the app scales to workspace size.
> >
> > Expected Result
> >
> > The debug pane does not display.
> >
> > On Tue, 8 Dec 2015 at 16:49 Rahman Usta <notifications@github.com>
> wrote:
> >
> > > Hi Jared,
> > >
> > > After running AsciidocFx, is the bottom pane not minimized?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/asciidocfx/AsciidocFX/issues/176#issuecomment-162792604
> > >
> > > .
> > >
> > --
> >
> > Sent from Mobile.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/asciidocfx/AsciidocFX/issues/176#issuecomment-163082505
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidocfx/AsciidocFX/issues/176#issuecomment-163137321>
> .
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
I think I might have worked out what's happening here.

When AsciidocFx is initially launched, it expects that the desktop size
will be no greater than 1080p.

If you pull the cascaded window into a workspace on Mac (where the app goes
full-screen), you get just a little bit more screen horizontal space, so
the debug pane shows only the tabs on the bottom of the screen.

https://youtu.be/bj-JiVcoXhs

On really large displays—like the Asus display I'm using to write documents
on—the normally hidden debug pane has all this extra screen real-estate to
use, and is therefore allowed to display in full.

https://youtu.be/GqvYGZyy_dA

Hope this clarifies the behaviour I'm seeing, and hopefully leads to a fix
for large-screen users. :D

On Wed, 9 Dec 2015 at 21:00 Jared Morgan <jaredleonmorgan@gmail.com> wrote:

> No problem, I'll do one tomorrow for you.
>
> On Wed, 9 Dec 2015, 17:16 Rahman Usta <notifications@github.com> wrote:
>
>> I don't have a Mac sir :) Could you please record a short video to
>> understand the isseu better.
>>
>> Thanks
>> 9 Ara 2015 04:02 tarihinde "Jared Morgan" <notifications@github.com>
>> yazdı:
>>
>> > I've just managed to replicate the issue:
>> >
>> > Have a monitor connected to your MacBook to replicate the environment.
>> >
>> > 1. Start AsciidocFx. The app starts in non-workspace mode (standard
>> > windowed).
>> > 2. Drag AsciidocFx from non-windowed, built-in display, to Monitor into
>> > a workspace.
>> > 3. Observe results.
>> >
>> > Actual Result
>> >
>> > The debug pane displays when the app scales to workspace size.
>> >
>> > Expected Result
>> >
>> > The debug pane does not display.
>> >
>> > On Tue, 8 Dec 2015 at 16:49 Rahman Usta <notifications@github.com>
>> wrote:
>> >
>> > > Hi Jared,
>> > >
>> > > After running AsciidocFx, is the bottom pane not minimized?
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> >
>> https://github.com/asciidocfx/AsciidocFX/issues/176#issuecomment-162792604
>> > >
>> > > .
>> > >
>> > --
>> >
>> > Sent from Mobile.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/asciidocfx/AsciidocFX/issues/176#issuecomment-163082505
>> >
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/asciidocfx/AsciidocFX/issues/176#issuecomment-163137321>
>> .
>>
> --
>
> Sent from Mobile.
>
-- 

Sent from Mobile.

**Comment by rahmanusta** [comment]
@jaredmorgs Thank you for the videos, I know this issue it is about JavaFX, when we change window's position/size it moves splitter's position. I will fix it in next version.

**Comment by jaredmorgs** [comment]
Nice one! Thanks Rahman.

On Sat, Dec 12, 2015, 20:30 Rahman Usta <notifications@github.com> wrote:

> @jaredmorgs <https://github.com/jaredmorgs> Thank you for the videos, I
> know this issue it is about JavaFX, when we change window's position/size
> it moves splitter's position. I will fix it in next version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidocfx/AsciidocFX/issues/176#issuecomment-164137899>
> .
>
-- 

Sent from Mobile.

**Comment by rahmanusta** [comment]
@jaredmorgs Can you try latest release ? Is it same what you say?

Thanks

**Comment by jaredmorgs** [comment]
Will try it out tomorrow. That was quick!

On Sun, 13 Dec 2015, 21:15 Rahman Usta <notifications@github.com> wrote:

> @jaredmorgs <https://github.com/jaredmorgs> Can you try latest release ?
> Is it same what you say?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidocfx/AsciidocFX/issues/176#issuecomment-164247761>
> .
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
The behaviour is still happening when I maximise the AsciidocFx window to
full-screen on the MacBook Pro built-in display.

I'll try it tomorrow on the large resolution display and see if the same
behaviour happens again.

On Sun, 13 Dec 2015 at 22:57 Jared Morgan <jaredleonmorgan@gmail.com> wrote:

> Will try it out tomorrow. That was quick!
>
> On Sun, 13 Dec 2015, 21:15 Rahman Usta <notifications@github.com> wrote:
>
>> @jaredmorgs <https://github.com/jaredmorgs> Can you try latest release ?
>> Is it same what you say?
>>
>> Thanks
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/asciidocfx/AsciidocFX/issues/176#issuecomment-164247761>
>> .
>>
> --
>
> Sent from Mobile.
>
-- 

Sent from Mobile.

**Comment by wfouche** [comment]
@rahmanusta  On Windows 7 (screen resolution:1920 x 1080) I experience a similar problem with or without taskbar set to "auto hide" when AsciidocFX *1.4.4* is started. By clicking on "Log" twice, the issue is resolved. I need to do this each time at startup. It also works if I click on "Terminal" twice. Did not experience this issue on *1.4.0* from which I've just upgraded.

![clipboard01](https://cloud.githubusercontent.com/assets/13682850/11789955/fe96e98c-a2a1-11e5-8c8b-0c607d48361e.png)

**Comment by jaredmorgs** [comment]
Hmm, it looks like the in-app updater isn't pulling in the latest 1.4.4
dmg. I've also tried to download the latest .dmg from the
http://asciidocfx.com/#truehow-to-install-asciidocfx link and it doesn't
give me 1.4.4.

Maybe the link needs an update?

On Mon, 14 Dec 2015 at 21:54 Jared Morgan <jaredleonmorgan@gmail.com> wrote:

> The behaviour is still happening when I maximise the AsciidocFx window to
> full-screen on the MacBook Pro built-in display.
>
>
> --

Sent from Mobile.

**Comment by rahmanusta** [comment]
I forgot to update site :) it is updated now. Also note that you can find all releases in https://github.com/asciidocfx/AsciidocFX/releases page

**Comment by jaredmorgs** [comment]
Confirmed fixed for me on 1.4.4 Mac (El Capitan). Thanks for getting this into the latest release so quickly @rahmanusta :+1:

**Comment by rahmanusta** [comment]
Thanks for checking it @jaredmorgs :+1: This release includes initial spell checker feature, what do you think for this ?

**Comment by jaredmorgs** [comment]
Ooh, I'll have to check that out.

On another subject, do you do release notes for new features like this?

On Tue, 15 Dec 2015 at 08:14 Rahman Usta <notifications@github.com> wrote:

> Thanks for checking it @jaredmorgs <https://github.com/jaredmorgs> [image:
> :+1:] This release includes initial spell checker feature, what do you
> think for this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidocfx/AsciidocFX/issues/176#issuecomment-164576793>
> .
>
-- 

Sent from Mobile.

**Comment by rahmanusta** [comment]
Yes :) Actually we need to update Change Log for every release but time time time :)

**Comment by jaredmorgs** [comment]
Can't you just auto-gen that from the bug fixes from GitHub? Maybe consider
https://github.com/skywinder/github-changelog-generator

On Tue, 15 Dec 2015 at 08:17 Rahman Usta <notifications@github.com> wrote:

> Yes :) Actually we need to update Change Log for every release but time
> time time :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidocfx/AsciidocFX/issues/176#issuecomment-164577559>
> .
>
-- 

Sent from Mobile.

**Comment by rahmanusta** [comment]
Seem good!

**Comment by jaredmorgs** [comment]
you just have to make sure that the Bug description is detailed enough.

For example, https://github.com/asciidocfx/AsciidocFX/issues/180 would need
to be edited from "Crash" before you commit the fix to something like
"Improve the way changes are saved in documents" (which is my summary of
what the issue seems to be about).

If you can get into the habit of doing that, you should be able to make a
pretty good changelog each release.

On Tue, 15 Dec 2015 at 08:24 Rahman Usta <notifications@github.com> wrote:

> Seem good!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidocfx/AsciidocFX/issues/176#issuecomment-164579132>
> .
>
-- 

Sent from Mobile.
