### ISSUE TITLE
[suggestion] General improvements

### ISSUE THREAD

**Issue by bodiam** [asciidocfx/AsciidocFX#178]
Hi all,

I'm the developer of the AsciiDoc plugin for IntelliJ, and yesterday, I was looking for a better AsciiDoc editor. In the process, I tried Atom, Brackets, AsciidocFX, and MacDown. MacDown is a Markdown editor, not an AsciiDoc one, but that one I like the most anyway.

I'll focus on my small experience with AsciidocFx, and my feedback on that, as a result from my conversation with Rahman (https://twitter.com/ustarahman/status/674341167887175680). I'm using a MacBook, just to be clear.

First, the website. Compare the AsciidocFX site with http://macdown.uranusjr.com/. I had a hard time finding the download button. Yes, I know it's there, but the website as a big asciidoc document, I don't know. Not a big +1 for usability. But I found it of course.

Then the download size. 70mb. For an editor to edit AsciiDoc... I know the JRE is bundled, that doesn't help, but it seems a lot. Well, it's a one time download anyway, so okay. 

The installation: first, I couldn't click on it, because you don't have a developers certificate. Right. Then I right click, do open, and I get into a wizard? Compare this to the Brackets installation:

![screen shot 2015-12-09 at 10 03 10](https://cloud.githubusercontent.com/assets/46468/11681514/a33e9454-9e5f-11e5-9ffb-5ccc97b7b2cc.png)

Just a drag and drop would be nice. 

Then the most important thing, the editor itself.

The menu bar, or lack thereof:

<img width="603" alt="screen shot 2015-12-09 at 10 30 38" src="https://cloud.githubusercontent.com/assets/46468/11681616/5a22a188-9e60-11e5-980f-9ac60f79a6a6.png">

The all, error, warn, info bar. This is not what I expect in a editor, and the purpose of that is unclear to me. Searching in logs... It's an editor, right, not an IDE? I'm looking at it from a perspective of a user, not as a developer. I'm looking for a simple AsciiDoc editor, and I'm not sure what I want to to be bothered with the internal errors of AsciiDocFX.

<img width="606" alt="screen shot 2015-12-09 at 10 30 45" src="https://cloud.githubusercontent.com/assets/46468/11681627/6722a6d0-9e60-11e5-9396-9e29a9325337.png">

Doctype?
<img width="121" alt="screen shot 2015-12-09 at 10 30 50" src="https://cloud.githubusercontent.com/assets/46468/11681679/aadb9de6-9e60-11e5-91a7-25dba21c306e.png">

Ah, yes, doctype! Of course!
<img width="140" alt="screen shot 2015-12-09 at 10 30 56" src="https://cloud.githubusercontent.com/assets/46468/11681979/91dd07b0-9e62-11e5-94d4-2b20343aec46.png">

Why is my filesystem on the left? I just want to write a simple AsciiDoc file...

<img width="1680" alt="screen shot 2015-12-09 at 10 31 06" src="https://cloud.githubusercontent.com/assets/46468/11681710/d59934bc-9e60-11e5-91e9-78c1b2f1ea96.png">

And what do these buttons mean? New directory, go up, refresh(?), dots...and a P. 

<img width="224" alt="screen shot 2015-12-09 at 10 31 07" src="https://cloud.githubusercontent.com/assets/46468/11681992/a8db6506-9e62-11e5-8431-94e79802dfb2.png">

No, it's not wha they mean: it means: open a popup with a filechooser, change directory, go up, refresh(?), and everything else. And a donate button, of course. 

If you would just use the native MacOS menu, you wouldn't need this unclear icons, and you could maybe limit it to go up or something, if you really want a file explorer. I don't want one.

Just the most simple document I could think of:

<img width="195" alt="screen shot 2015-12-09 at 10 31 25" src="https://cloud.githubusercontent.com/assets/46468/11681811/7c414570-9e61-11e5-9218-ae2f0d4a8bcc.png">

No syntax highlighting :(. With # I get highlighting, but = is not supported?

Epub export. Nice.
<img width="600" alt="screen shot 2015-12-09 at 10 33 04" src="https://cloud.githubusercontent.com/assets/46468/11681865/c9eead12-9e61-11e5-9974-e94664245538.png">

Oh, it does nothing.

<img width="1076" alt="screen shot 2015-12-09 at 10 35 30" src="https://cloud.githubusercontent.com/assets/46468/11681871/d8f948da-9e61-11e5-9cdd-3a2427cabfc2.png">

Luckily there's an error view ;-). It all makes sense now!! :)

Overal, my sarcasm aside, I think AsciiDocFX might be a really good for seriously editing books and technical documentation. However, I'm looking for a simple AsciiDoc editor, like notepad, or in my case, MacDown, in which you can start typing right away. AsciiDocFX is one of the few editors which allows doing that, (sublime, atom, brackets, IntelliJ, etc all require you to save to document first), and overal, I'm not a fan that is doesn't feel very native or Mac-y. It starts with the Windows installer, but it never ends this trip. 

Overal, the usability is just not very good, in my opinion. 
- I don't know what the shortcuts are, for example nor where I can find them. I tried CMD+B, and it worked. But if I want to insert a note? Or a table? Or a link? 
- Or open a document? CMD+O doesn't do anything. 
- Or If I want to have distraction free editing?
- Or a dark theme, which most editors support?
- Why is there an (extremely slow) sort-of-terminal thing, which you call a terminal, but which is not a terminal?

<img width="371" alt="screen shot 2015-12-09 at 10 58 05" src="https://cloud.githubusercontent.com/assets/46468/11682224/bfbb77ba-9e63-11e5-828d-d28280dc9ebe.png">

So, I think it's great that you are all spending time on this, just as I will continue spending time on the AsciiDoc IntelliJ plugin, but they all have their purpose, but for a simple editor, AsciiDoc is not the tool I'm looking for (and neither is the IntelliJ plugin :-)

**Comment by rahmanusta** [comment]
Thank you @bodiam , I gathered good feedbacks from you;

>First, the website. Compare the AsciidocFX site with http://macdown.uranusjr.com/. I had a hard time finding the download button. Yes, I know it's there, but the website as a big asciidoc document, I don't know. Not a big +1 for usability. But I found it of course.

:+1: 

>Then the download size. 70mb. For an editor to edit AsciiDoc... I know the JRE is bundled, that doesn't help, but it seems a lot. Well, it's a one time download anyway, so okay.

AFX is ~50MB for Mac, its size lower than Atom (70MB).

>The installation: first, I couldn't click on it, because you don't have a developers certificate. Right. Then I right click, do open, and I get into a wizard? Compare this to the Brackets installation:

I'm using Install4J to create cross-platform installer, surely If there is way to do that, I will do that. I didn't know the limitation caused by certificate, I will look at this also.

>The menu bar, or lack thereof:

I'm thinking to add menubar, JavaFX's menubar has native integration.

>Doctype?

If you want to change new (unsaved) document, you can change doctype, if saved you don't need to select Doctype.

>Why is my filesystem on the left? I just want to write a simple AsciiDoc file...

Hide it :) it is why Atom has.

>No syntax highlighting :(. With # I get highlighting, but = is not supported?

AsciidocFX has syntax higlighting, you can change Ace theme in Settings panel. Default is the xcode and it doesn't highlight titles, you can change it to any theme.

>Epub export. Nice.

You didn't save the document :) But, there is an issue to inform or help writer more at this situation.

>I don't know what the shortcuts are, for example nor where I can find them. I tried CMD+B, and it worked. But if I want to insert a note? Or a table? Or a link?

:+1: You are right but you can read the documentation. Asciidoc users are generally programmers.

>Or open a document? CMD+O doesn't do anything.

I will add it

>Or If I want to have distraction free editing?

After hiding left and right, can we think as it is distraction free editing?

>Or a dark theme, which most editors support?

:+1: In my mind

>Why is there an (extremely slow) sort-of-terminal thing, which you call a terminal, but which is not a terminal?

If it is extremely slow, we can improve it. It is an experimental terminal. It is not fully functional but it is easy to use it for simple commands.

Yes we can't say it is simple as MacDown, but there may be a port of AsciidocFX like MacDown for users like you.

Thanks for you valuable feedbacks!

**Comment by msgilligan** [comment]
I recommend looking at [NSMenuFX](https://github.com/codecentric/NSMenuFX) when implementing menus. It will help you implement standard menus for the MacOS platform.

**Comment by OndrejM** [comment]
I came across this issue, lot's of useful suggestions indeed. But first, I'd like to thank @rahmanusta for his work, AsciiDocFX is my asciidoc editor of choice and I'm glad to have it.

It's true that the usability can still be improved a lot (it's sometimes hard to navigate around even for a experienced programmer like me). The download size doesn't concern me, what matters more is startup speed and usage of resources when started. It's mostly OK, but I believe both can be improved. Overall, I like what I get for free and wish you @rahmanusta all the best!

**Comment by rahmanusta** [comment]
@OndrejM Thanks Ondrej for the kind words. I'm doing my best to improve AsciidocFX. It is nice to hear that you use AsciidocFX!

* About the startup speed, it mostly depends on the bootstrap time of embedded Undertow.
* About the resources, it mostly depends on JVM settings.
