### ISSUE TITLE
AsciidocFX - proposing Stable vs Fresh releases.

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#179]
Would be nice if we can have Stable and Fresh releases of AsciidocFX.

Most users would just want to stay on a Stable (say 1.4.0) release while several Fresh releases (1.4.1, 1.4.2, ...) are made till the next release that can be considered Stable.

This is similar to how LibreOffice is maintained with Stable releases (no worries, download install and run and be happy) and Fresh releases (bleeding edge, expect issues, not guaranteed to work in all scenarios, requires more testing).

**Comment by rahmanusta** [comment]
@wfouche This is good suggestion, but I don't think I can sustain like that.
