### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pysaumont** [asciidocfx/AsciidocFX#180]
Hello,

I found I could crash Asciidoc FX in a reproductible manner by just copying a few words and pasting them elsewhere. However, It "works" only with a specific document. What can I do to show you the problem?

**Comment by rahmanusta** [comment]
Could you please send me your copied document ? Which version are you using?

**Comment by pysaumont** [comment]
Sure. I hope you will experiment the problem. I am using AsciidocFX while writing a book for Manning. They found it (AsciidocFX) very good, and they said they will use it!

To reproduce the problem in the file, here are the manipulations:

Find the comment after « Exercise 11.3 » 

Copy « Recall the `foldInOrder` method » in the command

Select the sentence « Remember (or look at the code) the `foldInOrder` method » in the paragraph above and paste the text to apply the proposed change.



I noticed CMD + Z does no longer sut the current document which is good. But if you could implement cancel/redo (CMD + Z/CMD + SHIFT + Z, or CTRL + Z/CTRL + SHIFT + Z under Linux) That would be great!

Another usability problem is that if you make some edits to a file and then change your mind, you can’t abandon the changes, nor can you save it under a new name. This may be a problem for many users. (I am using git, so it is not a problem to cancel the changes afterward, but I am not sure that all users will do this.)

Regards,

Pierre-Yves

**Comment by rahmanusta** [comment]
Thanks @pysaumont , it is great you are a manning book author, I'm glad to hear that Manning thinks to use AsciidocFX, I'm ready to help them if needed.

I actually didn't understand the scenerio, if you want we can make a teamviewer session to see the issue in action ?

I will also try to fix cmd + z issue.

Do you need save as feature ?

**Comment by pysaumont** [comment]
Unfortunately, I can't use Teamviewer.

"Save as" would be nice. But the main problem is that changes may be saved without the user noticing it, for example by quitting the application. Saving automatically is good, but it should be done to a temporary file, so that changes might be abandoned. And when quitting, a dialog box should be displayed to ask the user if he wants to save.

More generally, I think it would be better to make the application compatible with what users are used to. (Commands, menu bars, dialog boxes, etc.)

**Comment by rahmanusta** [comment]
I got it, could you record a short video?

**Comment by pysaumont** [comment]
I’ll try, but not before one or two days

**Comment by rahmanusta** [comment]
Could you please try version 1.4.5 ? https://github.com/asciidocfx/AsciidocFX/releases

**Comment by rahmanusta** [comment]
Is the problem solved  ? @pysaumont

**Comment by pysaumont** [comment]
The problem seems to be solved. However, I could not reproduce it after a few days with the previous version, so I really do not know what to think.

**Comment by rahmanusta** [comment]
Thanks @pysaumont . I will close the issue, if you faced with this issue again, you can ping me again.
