### ISSUE TITLE
SVG images not rendered in the preview

### ISSUE THREAD

**Issue by ahnajmi** [asciidocfx/AsciidocFX#184]
The preview doesnot render the svg images properly in the preview[donot see borders], if I change from svg to png they are rendered properly, I can still see the images rendered properly in the browser.

<pre>
:imagesdir: output/images
:imagesoutdir: output/images
:uml: "plantuml"
:umlimg: "svg",align="center",width=580

:doctype: book
:encoding: utf-8
:lang: en
:numbered:

.State Diagram
[{uml},States,{umlimg}]
--
@startuml
scale 768 width
'left to right direction
state "INIT" as INIT <<Warning>>
state "Ready" as Ready <<HighLigth>>

[*] --> INIT : onInitialise
INIT --> [*] : onShutdown
INIT --> Ready : onReady
Ready : Ready for Transactions
Ready --> [*] : onShutdown
@enduml
--
</pre>

**Comment by rahmanusta** [comment]
@ahnajmi It is about JavaFX which has limited SVG support. For that reason, you may see svg output in preview section messy but you will see right output in PDF or external browser.

**Comment by ahnajmi** [comment]
only work around I do is I keep it in png till I am working on it then make it svg once design is done. 
<pre>
:umlimg: "svg",align="center",width=580
</pre>

**Comment by rahmanusta** [comment]
@ahnajmi Yes, you can use the workaround because it is related to JavaFX platform

**Comment by Koriit** [comment]
Hey, I don't know if it's just JavaFX's issue anymore. If I'm not wrong asciidoctor's plugin for IntelliJ uses JavaFX and is able to render SVG images in preview whereas AsciidocFX is still unable to do so. Just wanted to let you know.
