### ISSUE TITLE
Crashes while copying image from preview 

### ISSUE THREAD

**Issue by ahnajmi** [asciidocfx/AsciidocFX#185]
When I tried to copy the image to clipboard as above it crashed. using version 1.4.5

![image](https://cloud.githubusercontent.com/assets/5001607/11916979/9eaaa67e-a717-11e5-9f8c-305e8d36e13f.png)

**Comment by rahmanusta** [comment]
Thanks for report @ahnajmi , which OS are you using ?

**Comment by rahmanusta** [comment]
This is a JavaFX bug, I will open an issue for that.

**Comment by ahnajmi** [comment]
I am using it in Windows 10.

**Comment by rahmanusta** [comment]
@ahnajmi It is a JavaFX bug appears if you click "copy image to clipboard" for a svg image.
