### ISSUE TITLE
[Useability] AsciidocFX should remember last screen size

### ISSUE THREAD

**Issue by gernotstarke** [asciidocfx/AsciidocFX#186]
Currently (v 1.4.5) AsciidocFX always starts a new session in full screen mode (at least on MacOS).

If a user changes size/position, this setting is currently ignored upon next start.

**Comment by rahmanusta** [comment]
@gernotstarke Do you mean full screen mode as full editor area? Normally, AsciidocFX saves divider positions to user home. Do you see any error output in AsciidocFX log file ?

**Comment by gernotstarke** [comment]
I mean screen resolution, not divider setting.

That is:

* last window size (in case user has resized the app, which I personally do, as my 27’’ monitor is just tooo big for one editor window…)
* last x/y position on screen

hope that makes the issue a little clearer
Gernot

**Comment by rahmanusta** [comment]
Aha, yes I understand it. It is now clear for me. We can do that @gernotstarke

**Comment by rahmanusta** [comment]
@gernotstarke I implemented this feature after your suggestion, Could you please try it whether it is okay ?

**Comment by gernotstarke** [comment]
Rahman,

I’m impressed, but currently a little overloaded with other issues - I won’t manage to look at AsciidocFX for a couple of weeks,
very sorry indeed…

keep up your great work,
Gernot
