### ISSUE TITLE
useless "settings" menu item

### ISSUE THREAD

**Issue by gernotstarke** [asciidocfx/AsciidocFX#187]
![asciidocfx_-__users_gstarke_projects_htmlsanitycheck-all_htmlsanitycheck_src_docs](https://cloud.githubusercontent.com/assets/1233990/12073922/adc4290c-b138-11e5-8e8a-6696cc34ed19.jpg)

there's a settings tab on the right (ok), but the menu item does not do anything... 

imho either remove it or it shall open the settings tab...

**Comment by rahmanusta** [comment]
Yes @gernotstarke , it is now useless, will remove it next version

**Comment by rahmanusta** [comment]
Please try version 1.4.6 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.6

I now close this issue, if you think your issue is not fixed, please don't hesitate to reopen or comment the issue.
