### ISSUE TITLE
AsciidocFX 1.4.5 - ERROR => Problem occured while jumping from outline

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#188]
Hi @rahmanusta ,
When using the HTML "Save" option in AsciidocFX 1.4.5, the contents of the Outline window disappears.

![screenshot from 2016-01-02 12 33 12](https://cloud.githubusercontent.com/assets/13682850/12074158/349411ae-b14d-11e5-8a1a-b382ee301ebb.png)

```
ERROR => Problem occured while jumping from outline
```
![screenshot from 2016-01-02 12 33 47](https://cloud.githubusercontent.com/assets/13682850/12074159/41192b9e-b14d-11e5-922d-98c70f68525b.png)

**Comment by rahmanusta** [comment]
Thank you @wfouche , I will investigate it.

**Comment by wfouche** [comment]
@rahmanusta 

Finding it a bit difficult to use AFX 1.4.5 with this bug unresolved, as the outline keeps on disappearing. If you need help with this, please provide feedback on where in the Java code on should resolve this issue; and I'll try and fix it.

Thanks.

**Comment by rahmanusta** [comment]
Could you try clear outline if outlineList greater than 0 ?

https://github.com/asciidocfx/AsciidocFX/blob/c25648899c860daef56d9e66745d0e95f1bb70af/src/main/java/com/kodcu/controller/ApplicationController.java#L1630-L1632

**Comment by wfouche** [comment]
@rahmanusta  I submitted a pull request to resolve this issue. Please review the change. It works fine in my environment (Ubuntu Linux and Windows 7)

**Comment by rahmanusta** [comment]
Thank you @wfouche , it seems okay, many thanks!
