### ISSUE TITLE
Superscript only affecting a single word

### ISSUE THREAD

**Issue by thomas-crowe** [asciidocfx/AsciidocFX#189]
When I attempt to markup a string to be formatted as superscript using the '^' markup, it only seems to affect a single word at a time, not the entire string as delimited by the caret.

E.G.
* [line-through]#Install Glance# ^Covered^ ^in^ ^OSP^ ^Implementation^ 
renders as I want, with "Covered in OSP Implementation" being all superscript; however

* [line-through]#Install Glance# ^Covered in OSP Implementation^
renders with the literal carets appearing, without the string being formatted as superscript

Apologies in advance if this is a user error and not an asciidocFX issue.

![screen shot 2016-01-04 at 13 19 43](https://cloud.githubusercontent.com/assets/4438167/12096804/f7f199a2-b2e5-11e5-805c-f22556f1bdfd.png)

**Comment by rahmanusta** [comment]
You can use following workaround;

```asciidoc
:b: Covered in OSP Implementation

a^{b}^
```
