### ISSUE TITLE
Cannot turn off or configure spelling checker 

### ISSUE THREAD

**Issue by joswarmer** [asciidocfx/AsciidocFX#191]
In one of the last versions a spelling checker has been added.  This is turned on by default.  I try to find a way to configure the spelling checker, but I cannot find it anywhere. I would like to be able to turn off the spelling checker completely,  and to select the language used.

Is there a way that I did not find?

Jos Warmer

**Comment by rahmanusta** [comment]
@joswarmer You can configure spell-checker in editor context-menu (Right click to editor).
