### ISSUE TITLE
How do I create PDFs?

### ISSUE THREAD

**Issue by MarinaMichaels** [asciidocfx/AsciidocFX#192]
I would like to create PDFs using AsciiDoc FX. I'm using AsciiDoc FX version 1.4.4. I've searched the AsciiDoc FX documentation, but didn't find anything in there on what I need to do. I've watched the YouTube tutorial on writing books with AsciiDoc FX, and that showed a choice for creating PDFs. My version doesn't have that option.

What do I need to do to generate PDFs? Thanks!

**Comment by rahmanusta** [comment]
Hi @MarinaMichaels , you can use PDF save button to produce PDF output like below;

![image](https://cloud.githubusercontent.com/assets/1158804/12154586/0f42224a-b4c9-11e5-8d8d-d1c14aba65a5.png)

**Comment by MarinaMichaels** [comment]
I am embarrassed now. It was right there! Thank you.
