### ISSUE TITLE
Include parent path not working in preview for 1.4.5 was working in 1.3.8

### ISSUE THREAD

**Issue by jafin** [asciidocfx/AsciidocFX#193]
The following asciidoc segment doesn't work in asciidocFX 1.4.5 but does work in 1.3.8

```
include::..\App.base.config[]
```

Perhaps related to #147 ?

Anything to do with safe mode?

**Comment by rahmanusta** [comment]
Where the file located? Same dir or root dir?
11 Oca 2016 06:02 tarihinde "Jason Finch" <notifications@github.com> yazdı:

**Comment by jafin** [comment]
in a parent folder. (one level up from the referencing document).

**Comment by jafin** [comment]
[example.zip](https://github.com/asciidocfx/AsciidocFX/files/85395/example.zip)

**Comment by rahmanusta** [comment]
Yes, it is bug :)

**Comment by tjuchniewicz** [comment]
The same result is if we use absolute paths. It works on 1.3.8 but not in 1.4.5.

**Comment by rahmanusta** [comment]
I'll fix it, but I'm a bit busy nowadays. Thank for the patience.

**Comment by SomeStupid** [comment]
Anything new?
We need to include some central settings, but fail due to this bug.

**Comment by rahmanusta** [comment]
@SomeStupid I fixed the problem in local but I need more tested to push it. Nowadays unfortunately I'm a bit busy, you can use 1.3.8 until the next release.
