### ISSUE TITLE
Slide show not working after save from browser

### ISSUE THREAD

**Issue by ellipticview** [asciidocfx/AsciidocFX#195]
Scenario:
1. Create default slideshow
2. Use the Deck.js template
3. Display document in browser (I used Chrome). Navigation between slides works well here.
4. While still in the browser: Save document
5. Open saved document: Navigation between slides no longer works.

Note that this issue is on Chrome and Opera. Firefox can successfully open and navigate the saved file.

**Comment by rahmanusta** [comment]
Thank for the issue report @ellipticview
