### ISSUE TITLE
"Enter" key from numeric keypad does not work inside the editor

### ISSUE THREAD

**Issue by gastaldi** [asciidocfx/AsciidocFX#196]
If you press `<ENTER>` from the numeric keypad while editing a document, nothing happens. It should behave like a normal `<ENTER>` and perform a line break

**Comment by rahmanusta** [comment]
@gastaldi  Did you try like below ? 

```
Lorem ipsum +
dolar sit amet
```

**Comment by gastaldi** [comment]
What do you mean? I typed that and after pressing `<ENTER>` I didn't get the line break

**Comment by rahmanusta** [comment]
Ah soryy, I misunderstood it. You mean enter in numeric keypad doesn't behave like normal enter in keyboard. It may be related to JavaFX, what kind keyboard do you use ? in my keyboard it works correctly, but JavaFX has such a kind of issues, but I will try to fix it if I can do it.

**Comment by gastaldi** [comment]
Yes, that's correct. I use a Brazilian Portuguese Keyboard, like the one below:
![screenshot from 2016-01-18 15-58-37](https://cloud.githubusercontent.com/assets/54133/12398690/61c4565a-bdfc-11e5-9a1b-1a3c3c5b41ac.png)
