### ISSUE TITLE
Support to install throght SDKman.in

### ISSUE THREAD

**Issue by rajmahendra** [asciidocfx/AsciidocFX#197]
Now sdkman is used to install any java app.

If AsciidocFX integrated to install using sdkman then its just a command line away to install .

http://sdkman.io/

http://sdkman.io/vendors.html

**Comment by rahmanusta** [comment]
Hi @rajmahendra ;

Thanks for the informing us. I would be happy if you help us to support sdkman, how path we need to follow ?

**Comment by rajmahendra** [comment]
**Update:**
We have got a positive reoly from sdkman team to incorporate AsciidocFX  into there tool. 
As per @rahmanusta comment, we planning to provide this support from next release  :)

**Comment by rahmanusta** [comment]
:+1:  :+1:   :+1:

**Comment by rahmanusta** [comment]
Hey @rajmahendra , is the version 1.4.6 ready for this ?
