### ISSUE TITLE
PlantUML <img:...> Tag

### ISSUE THREAD

**Issue by rdmueller** [asciidocfx/AsciidocFX#198]
If you use the <img:...> tag within PlantUML like in the example below, PlantUML searches for the image within the AsciidocFX installation folder. It would be great if this folder would be configurable in some way...

```
object "inbound message" as m1
object "XML Splitter" as s1

m1 : <img:MessageIcon.gif>
s1 : <img:SplitterIcon.gif>
m2 : <img:MessageIcon.gif>

m1 -> s1
s1 -> m2
```

**Comment by rahmanusta** [comment]
Hi @rdmueller, I'm seeing there is a issue http://plantuml.sourceforge.net/qa/?qa=2044/image-paths-are-relative-application-path-working-directory about like you said. I will try to set workdir in plantuml.

**Comment by rdmueller** [comment]
@rahmanusta : I'm not sure if this is an "issue" in PlantUML. 
I already searched for the code in PlantUML which fetches the image - I think it is this line of code:
https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/graphic/Img.java#L115
It seems that the workdir can be set through the `FileSystem`-Class:
https://github.com/plantuml/plantuml/blob/703a77ee1c3d4b5763e58693492f3d885b01b64b/src/net/sourceforge/plantuml/FileSystem.java

It seems that the path also can be set through a property...

**Comment by rahmanusta** [comment]
@rdmueller  Thanks for investigating details, I will try to set https://github.com/plantuml/plantuml/blob/703a77ee1c3d4b5763e58693492f3d885b01b64b/src/net/sourceforge/plantuml/FileSystem.java#L57 current dir.

Nowadays, I am a bit busy, but I will solve this issue in following days. We can follow up this issue for the next version.

**Comment by arnaudroques** [comment]
You are 100% correct, you can use
FileSystem.getInstance().setCurrentDir(new File("/path/to/my/images/files"));
To set the current default directory.
Another option is so set the environment variable plantuml.include.path in your script. This variable is indeed used to define default folders for loading file.

**Comment by rahmanusta** [comment]
Thank you @arnaudroques , for giving the details to set current dir.

@rdmueller , Do you think it is enough to set workdir to current file dir ? Do you want another parameter to set workdir ?

**Comment by rdmueller** [comment]
@rahmanusta as far as I understand, we still need an option in the settings to set the current dir within asciidocfx, right? Then I guess this will be the solution...

**Comment by rahmanusta** [comment]
For example think that your asciidoc file is under /user/usta/deneme.adoc  and AsciidocFX can automatically set the plantuml root dir as /user/usta. Do you think it is enough for us?

**Comment by rdmueller** [comment]
@rahmanusta ok, I guess I should try and come up with the pull request which solves my problem, right? ;-) I'll give it a try and see what I can come up with...

**Comment by rdmueller** [comment]
yes, this would solve one use case - the one where you want to include local images.

Another one is where you want to reference an image library which is centrally stored on your local machine.

the setting for the first use-case could be "." and the second one "%USERPROFILE%\images\." on a windows machine.

That would be perfect. I will now try to dig into your code in order to find where plantUML is instantiated and where the settings are handled...

btw: there is no "project" and thus no project specific settings, right?

**Comment by rahmanusta** [comment]
It is here https://github.com/asciidocfx/AsciidocFX/commit/f20f1effdde90c55f7f196aaf98c03f9b5ab0f1c, Could you please test it ?

> btw: there is no "project" and thus no project specific settings, right?

What do you mean about the project settings ?

**Comment by rdmueller** [comment]
project settings: when I work on asciidoc documentation, I refer to it as "project". I guess it would sometimes make sense to have "global" settings and sometime in addition "project" settings which override the "global" ones...

**Comment by rdmueller** [comment]
thanx! f20f1ef works with some limitations. If you give me some time, I will try modify f20f1ef in order to come up with a version which fits more use cases...

**Comment by rahmanusta** [comment]
This is good! Sure, please improve it to be more good.

There is no project settings but we can use Asciidoc attributes to pass an spesific option to anywhere in the app.

**Comment by rdmueller** [comment]
Hm. Is it possible to access an asciidoc property from within the plantuml service?

**Comment by rdmueller** [comment]
@rahmanusta : regarding your code - why didn't you just inject the directoryService?

**Comment by rahmanusta** [comment]
I injected the directoryService but I actually didn't use it in code.

We can access asciidoc property but we need to pass it from JavaScript code.

**Comment by rdmueller** [comment]
I think we don't need an asciidoc property. We need something like a "project". A folder which you open and then work with the files and folders within this root-folder.

Currently the root folder changes whenever I select a sub-folder...

**Comment by rahmanusta** [comment]
Hmm, I'm not sure to implement a "project" approach.

**Comment by rdmueller** [comment]
I guess the change is very small:
- the "Change Workdir"-button changes the root of the treeview
- a clock on a folder does not change the root of the treeview but just adds to the treeview

I currently try to come up with an example, but I haven't worked with JavaFX yet...

**Comment by rahmanusta** [comment]
Let's see the code :) Also a simple figure may help to understand your suggestion more

**Comment by rdmueller** [comment]
imagine a folder structure for a book like this:

/myBook
    index.adoc
    /chapters
        chapter1.adoc
        chapter2.adoc

index.adoc includes the chapters...

I would like to open the /myBook folder and then work with all files without changing the root working dir. At least, that's the way I worked with AsciiDoc in the past.

**Comment by rahmanusta** [comment]
I get it, you want a directory tree structure. Is it right ?

**Comment by rdmueller** [comment]
yep. that's all.

**Comment by rahmanusta** [comment]
It is great, we need it. you can look at file browse service.

**Comment by rdmueller** [comment]
yeah, I already try to figure out how to add it without changing too much :-)

**Comment by rahmanusta** [comment]
Do you think this issue is fixed ?

**Comment by rdmueller** [comment]
Just tested it and it feels great!
Thanx for implementing it!

**Comment by rahmanusta** [comment]
Thank you Ralf!
