### ISSUE TITLE
[suggestion] AsciidocFX should be aware of when an opened file has changed.

### ISSUE THREAD

**Issue by eskwayrd** [asciidocfx/AsciidocFX#204]
When AsciidocFX opens a file for editing, it appears to read it entirely into memory. If the original file on disk is updated, say due to a version control operation outside of AsciidocFX, the editor appears to be unaware of the change. This means that when the AsciidocFX file is saved, it is potentially overwriting desirable/necessary changes.

Please add a feature where original file changes are noticed. A simple OK/Reload file dialog would work, but a diff view might help indicate if there are conflicts. Any such improvements would help non-technical authors from overwriting important work.

**Comment by rahmanusta** [comment]
@eskwayrd AsciidocFX has already that feature, but only watch workdir file changes for now.

**Comment by eskwayrd** [comment]
That feature should apply to all files opened in the editor. Or, AsciidocFX should potentially/configurably refuse to open/edit files outside the workdir. Losing work really sucks.

**Comment by rahmanusta** [comment]
You are right, we should implement it

**Comment by rahmanusta** [comment]
Could you please try the latest release of AsciidocFX ( v1.4.7  )?
