### ISSUE TITLE
[suggestion] Enhance wrap mode to insert line-breaks.

### ISSUE THREAD

**Issue by eskwayrd** [asciidocfx/AsciidocFX#205]
When authoring text files, we prefer that our authors wrap the source text to 80 columns (where possible) to assist with code review/diff tools. AsciidocFX's wrap mode helps authors see long lines, but it doesn't help authors maintain source line lengths.

Please add an option to Wrap mode to enforce line lengths when word-wrapping on whitespace is possible.

**Comment by rahmanusta** [comment]
@eskwayrd AsciidocFX has setting wrap mode feature. You can change it in "Settings" tab. Do you think it fits with your need?

**Comment by eskwayrd** [comment]
The current "Wrap Mode" merely wraps the display of long lines within the editor. It does nothing to make long lines fit the specified column width when the file is saved. Long lines, as might be found in documentation where entire paragraphs appear on a single line within the source file make comparing diffs of the changes difficult to parse.

So a "Physical Wrap" instead of just a visual wrap would be preferable.

**Comment by rahmanusta** [comment]
We use Ace editor in AsciidocFX but it has no feature for hard wrapping yet https://github.com/ajaxorg/ace/issues/2865
