### ISSUE TITLE
Unable to find Graphviz.

### ISSUE THREAD

**Issue by syaifulnizamyahya** [asciidocfx/AsciidocFX#207]
From graphviz.org

> As of version 2.31, the Visual Studio package no longer alters the PATH variable or accesses the registry at all. If you wish to use the command-line interface to Graphviz or are using some other program that calls a Graphviz program, you will need to set the PATH variable yourself.

Apparently this has become a problem to not so savvy users. There is also the possibilities that the user installed Graphviz in different folder than the default folder. 

From plantuml page http://plantuml.com/graphvizdot.html

> Another option is to use the -graphvizdot flag in the command line:
> java -jar plantuml.jar -graphvizdot "d:/dummy/dot.exe" file1 "c:/directory2"

Would it be possible to include a portable version of Graphviz in AsciidocFX? And AsciidocFX set the path for plantuml? Or option to set plantuml path(for people that already have graphviz istalled)?

Thanks for excellent work!

**Comment by syaifulnizamyahya** [comment]
I solve this problem by creating a new batch file that temporarily create the required path and execute the AsciidotFX. My path directs to drive D, so of your path is in drive C, make the necessary changes.

Here are the contents of my AsciidocFX.bat

> SET GRAPHVIZ_DOT=D:\Program Files (x86)\Graphviz2.38\bin\dot.exe
REM java -jar "D:\Program Files\AsciidocFX\lib\plantuml-8033.jar" -testdot
AsciidocFX.exe

**Comment by rahmanusta** [comment]
Hi @syaifulnizamyahya It is easy to add dot executable to PATH variable or set GRAPHVIZ_DOT environment variable like you write above.

**Comment by syaifulnizamyahya** [comment]
@rahmanusta While it is true that it is easy to set path manually, for some people (management people, marketing people) who are not programmer or casual pc user, it is baffling. For some people, if it doesnt work the first time, it isnt worth their time. While the solution is easy, it still took me couple of hours to figure out how to get it right(never use graphvix before). Some people doesnt have the time luxury that I have.

By embedding graphviz and automatically set path, this eliminates a barrier for newbie to jumpstart asciidocfx. And I would like to introduce asciidocfx to my colleagues. 

Anyway, that is just my suggestion. Asciidocfx is gold. Keep up the good work.
