### ISSUE TITLE
Open Source license key for install4j.

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#209]
@rahmanusta 

I've downloaded the .deb package for install4j and installed it on Linux Mint with command:

```
sudo dpkg -i install4j_linux_6_0_4.deb
```
The default install folder is /opt/install4j6, so the change below is required to the the pom.xml file.
```
        <install4j.home>/opt/install4j6</install4j.home>
        <install4j.licenseKey>${env.CI_LICENSE_KEY}</install4j.licenseKey>
```

Did you apply for a free Open Source license for install4j? If so, can you please share the license key.

Without a valid license key command ```mvn package``` fails.

**Comment by rahmanusta** [comment]
@wfouche Yes we use open source license of install4j but It cannot be shared publicly. What is your final goal, I can help you for that.

**Comment by wfouche** [comment]
@rahmanusta  My goal is to be able to build packaged versions of AsciidocFX (with and without JREs) in order to be able to fully test changes made to AsciidocFX before official releases are made available.

**Comment by rahmanusta** [comment]
When you build the project with `mvn clean install` this will produce an output in /target/appassebler dir. You can use directly .bat or .sh files to test it. But this feature doesn't include JRE.

**Comment by wfouche** [comment]
@rahmanusta  Can you share your license key with me in a secure (private) way or would I need to apply for my own open source license key for install4j?

**Comment by rahmanusta** [comment]
Yes I can share it with you @wfouche , Could you please email me for that ? rahmanusta(at)kodcu(dot)com

**Comment by rahmanusta** [comment]
@wfouche I wait your email

**Comment by wfouche** [comment]
Email sent. Thanks!

**Comment by rahmanusta** [comment]
:+1:

**Comment by wfouche** [comment]
Thanks again! I was able to successfully build AsciidocFX. See output below.

```
-rw-r--r-- 1 wfouche wfouche  51329015 Feb 21 14:02 AsciidocFX_Linux_No_JRE.tar.gz
-rw-r--r-- 1 wfouche wfouche 122838933 Feb 21 14:02 AsciidocFX_Linux.tar.gz
-rw-r--r-- 1 wfouche wfouche  59302023 Feb 21 14:01 AsciidocFX_Mac.dmg
-rw-r--r-- 1 wfouche wfouche  59722240 Feb 21 14:00 AsciidocFX_Windows.exe
-rw-r--r-- 1 wfouche wfouche  21858816 Feb 21 14:02 AsciidocFX_Windows_No_JRE.exe
-rw-r--r-- 1 wfouche wfouche  52550161 Feb 21 14:02 AsciidocFX_Windows_No_JRE.zip
-rw-r--r-- 1 wfouche wfouche  90458104 Feb 21 14:01 AsciidocFX_Windows.zip
```

**Comment by khalidtijani** [comment]
@rahmanusta Can you share your license key with me open source license key for install4j?  i need it to generate the installer for this open source app https://github.com/senbox-org/snap-installer

**Comment by rahmanusta** [comment]
Hi @khalidtijani. The license key can be used only for AsciidocFX but you can request free license for your open source software.

Details: https://www.ej-technologies.com/buy/install4j/openSource

**Comment by bibali1980** [comment]
Hi @rahmanusta can you share with me the install4j open source license please , i want just to use it for this open source software , http://sallyprayertimes.com/ , https://github.com/SallyPrayerTimes , my email is : bibali1980@gmail.com , thank you so much

**Comment by nbznzhzbz-lgtm** [comment]
# [for install4j Download Link](https://activatesetup.pro/)
