### ISSUE TITLE
Does AsciidocFX support output of PDF/X-1a or X3 compliant Print Ready PDF's ?

### ISSUE THREAD

**Issue by IbnSaeed** [asciidocfx/AsciidocFX#210]
Does AsciidocFX support output of PDF/X-1a or X3 compliant Print Ready PDF's ?

here is some information on PDF/X

### PDF/X

- http://en.wikipedia.org/wiki/PDF/X
- http://www.prepressure.com/pdf/basics/pdfx-1a

**Comment by IbnSaeed** [comment]
Thanks for the information.

So it means that it does not support PDF/X-1a ?

**Comment by rahmanusta** [comment]
Yes it seems https://github.com/pellcorp/fop/blob/master/src/java/org/apache/fop/pdf/PDFProfile.java#L62 that it supports only PDF/X-3:2003 for xish.

**Comment by rahmanusta** [comment]
Is PDF/X-3:2003 enough for you ?
