### ISSUE TITLE
mathjax extention should be able to generate images with same font size

### ISSUE THREAD

**Issue by shawn11ZX** [asciidocfx/AsciidocFX#212]
If I have multiple math blocks, whose rendered size is different. After render, their font size is different, which is very ugly.

```text

.Fomula 1
[math,file="images/program.png"]
--

\begin{align}
    t &= texture_{color} [ uv_{color} ] \\
    color_{out}.xyz &= t.xyz \\
    color_{out}.w &= t.w * alpha
\end{align}

--


.Fomula 2
[math,file="images/vexterColorProgram.png"]
--
\scriptsize
\begin{align}
    color_{out.xyz} & = color_{constant.xyz} \\
    color_{out.w} & = color_{constant.w} * texture_{alpha} [ uv_{alpha} ] 
\end{align}
--


.Fomula 3
[math,file="images/opacityProgram.png"]
--

\begin{align}
    t &= texture_{color} [ uv_{color} ] \\
    color_{out}.xyz &= t.xyz \\
    color_{out}.w &= t.w * texture_{opacity} [ uv_{opacity} ] * alpha
\end{align}

--

```

![math](https://cloud.githubusercontent.com/assets/12724185/13455784/6b5292e8-e09a-11e5-9f4d-2b3339da6c28.png)

**Comment by rahmanusta** [comment]
Hi @shawn11ZX , you are right. You can simply give width manually to resize mathjax output. 

```
.Fomula 1

[math,file="images/program.png",width=400]

-- 

\begin{align} 

    t &= texture_{color} [ uv_{colorxy} ] \\

    color_{out}.xyz &= t.xyz \\

    color_{out}.w &= t.w * alpha

\end{align} 

--    
```

Surely we can look at the code to increase comfort about the formula's size.

**Comment by shawn11ZX** [comment]
Thanks Rahman, I get you idea. But it's too difficult to be used to write a book heavily related mathematics.

**Comment by rahmanusta** [comment]
@shawn11ZX New version will solve this issue

**Comment by rahmanusta** [comment]
Please try version 1.4.6 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.6

I now close this issue, if you think your issue is not fixed, please don't hesitate to reopen or comment the issue.
