### ISSUE TITLE
Feature request for configurable delayed preview

### ISSUE THREAD

**Issue by shawn11ZX** [asciidocfx/AsciidocFX#213]
As I was using AsciidocFx to write documents, I found it very useful to use the preview function.

But as the document gets a little larger, e.g. having some Math formulas or sequence flow diagrams, it practically impossible to type anymore if preview is on. 

The problem seems that AsciidocFx will render the preview panel for every keystroke, and it's really slow.

I don't won't to close the preview function, because i have to see the rendering result once in a while.

If rendering performance can't be improved, three possible solutions are:
- update rendering until AsciidocFx haven't received any new input for, say, 5 seconds. Would be better if time is configurable.
- update rendering if 'saved'
- Disable realtime rendering, but provide key short cut to update it.

**Comment by rahmanusta** [comment]
Hi @shawn11ZX , you suggestions sounds good. You currently stop and resume rendering by right clicking to the preview panel.

**Comment by rahmanusta** [comment]
@shawn11ZX Do you think current stop rendering feature is enough for us ?

**Comment by shawn11ZX** [comment]
Honestly speaking, I don't think it is very convenient... I hope it can be more intuitive, because I was nearly using it everyday...

And sometimes it's buggy, e.g. Sometimes when I start to realize it's too slow to have rendering turned on, I will stop it. But AsciidocFx is still slow... Maybe because there are too many graphs in my doc:(
