### ISSUE TITLE
Plantuml preview and plantumldir for external puml files

### ISSUE THREAD

**Issue by mrumpf** [asciidocfx/AsciidocFX#214]
When I put my plantuml files, similar to the "images" into a "plantuml" sub-folder there is no way to specify a pantumldir variable so that puml files are found in this sub-folder.

```
plantuml::plantuml/apiversion.puml[format=svg, alt="Versions", width=300, height=200]
```

The preview for external puml files in this sub-folder does not work.
When I embed the PlantUml code into the adoc file, I see the preview. When I use the plantuml macro to externalize the code it does not work.

**Comment by rahmanusta** [comment]
@mrumpf We should implement it. For now, you can use it like below;

````
[plantuml,file=""]
----
include::plantuml/apiversion.puml[]
----
````

**Comment by mrumpf** [comment]
It is still rendered into the final document, but still no preview in AsciidocFX 1.4.5.

**Comment by rahmanusta** [comment]
Please try version 1.4.6 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.6

P.s. format=svg will not work now, it will generate png. If it is important for you, we can implement it.
