### ISSUE TITLE
how to let asciidocfx don't add "Chapter xx" in front of each chapter in epub?

### ISSUE THREAD

**Issue by flyisland** [asciidocfx/AsciidocFX#215]
right now, asciidocfx will add "Chapter xx" in front of each chapter in epub, for exampe, 

>  == My Chapter Title

will be converted  to 

> Chapter 1. My Chapter Title

I just want to keep the title unmodified.

**Comment by rahmanusta** [comment]
You can use :doctype: article for the simplicity or you should edit your docbook xsl.

**Comment by flyisland** [comment]
@rahmanusta actually, i do want to build a "book". Where can I find more information about this "doctype" attribute, thanks.

**Comment by flyisland** [comment]
btw, 'asciidoc-epub' would not generate such "chapter xx" things with same ":doctype:" attribute.

**Comment by rahmanusta** [comment]
@flyisland docbook settings located in docbook dir in AsciidocFX installation folder. Unfortunately my docbook knowledge is not so good.
