### ISSUE TITLE
Text Disappers in pdf

### ISSUE THREAD

**Issue by thebavarian** [asciidocfx/AsciidocFX#216]
Hi everyone,

if i try to change my color in my Asciidoc. i get a problem. 
i use the command: [blue]# here the text.#
:doctype: article
my version is the 1.4.5

and if i generate now a pdf document, the text disappers(the same with red, white and so on).
I have no error or warning in the consol.

is it possible that i forget a command?

hope somebody can help me :)

**Comment by chen56** [comment]
same error .
1.4.5 windows 10 chinese

**Comment by rahmanusta** [comment]
@ozlerhakan Can you help me for this?

**Comment by ozlerhakan** [comment]
sure @rahmanusta , I will look at this issue.

**Comment by ozlerhakan** [comment]
the current master fixes this issue @rahmanusta @thebavarian @chen56

**Comment by rahmanusta** [comment]
Thank you @ozlerhakan ! It works great

**Comment by rahmanusta** [comment]
Please try version 1.4.6 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.6

I now close this issue, if you think your issue is not fixed, please don't hesitate to reopen or comment the issue.
