### ISSUE TITLE
AsciidocFX JavaApplicationStub (OS X) crashes on waking from sleep

### ISSUE THREAD

**Issue by pemcg** [asciidocfx/AsciidocFX#217]
I'm seeing quite a few AsciidocFX JavaApplicationStub (OS X) crashes on waking my MacBook from sleep lately. 

This is with the JRE-bundled version of AsciidocFX: 
JavaApplicationStub
0x1000c5000 - 0x1000cffff +com.oracle.java.8u66.jdk (1.0 - 1.8.0_66) <842B8566-51A8-3842-9307-96BEC9966B8C> /Applications/AsciidocFX.app/Contents/PlugIns/jre.bundle/Contents/

Logs are attached.
[JavaApplicationStub_crash_logs.zip](https://github.com/asciidocfx/AsciidocFX/files/214622/JavaApplicationStub_crash_logs.zip)

**Comment by rahmanusta** [comment]
I don't know it is fixed but,
you can try version 1.4.6 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.6
