### ISSUE TITLE
Preview processes include:: only as link

### ISSUE THREAD

**Issue by norman-knott** [asciidocfx/AsciidocFX#220]
If include:: is used the preview only displays links to these files. It's nice that the file is opened in the editor pane on a click. But an option to display the content in the preview would be nice, too.

I found a config file in "conf/asciidoctor_preview.json" where the property "safe" is set. Tought it is the Asciidoctor "safe" option. But setting it to unsafe or server does not change the pahavior of the preview.

**Comment by norman-knott** [comment]
This behavior only apply if the including doc is of type "book". If it is an "article", the preview processes the included structure.

**Comment by rahmanusta** [comment]
Hello @norman-knott , can you try :force-include: parameter?

**Comment by norman-knott** [comment]
Hello @rahmanusta , thank you for the response.
I tried :force-include: as attribute in my main document and in the Preview Settings. Without a value and with the value of true.
This does not affect the Preview.

**Comment by rahmanusta** [comment]
Hi @norman-knott, sorry no hyphen, it is just :forceinclude:

**Comment by norman-knott** [comment]
Thank you @rahmanusta . In the Preview Settings it has no effect again, but set in the main document, it does what I need.
Is this an Asciidoctor attribute or a general asciidoc attribute?

**Comment by rahmanusta** [comment]
Hi @norman-knott, it is AsciidocFX spesific

**Comment by norman-knott** [comment]
Would be nice to have this as setting for the Preview.

**Comment by rahmanusta** [comment]
I don't understand what you mean "for the preview"?

**Comment by norman-knott** [comment]
Hi @rahmanusta,

sorry, for my late response.

It would be nice to have this attribute as setting for the AsciidocFX-preview function, too. So that I do not need to include this attribute in my document. For example in the panel of the screenshot below.

![asciidocfx_previewsettings](https://cloud.githubusercontent.com/assets/18596176/15648393/950d2cc2-266a-11e6-8e70-cd8f9cce2d81.png)

**Comment by rahmanusta** [comment]
Hi @norman-knott You can add any attribute to this list with Add button.

**Comment by norman-knott** [comment]
Adding forceinclude with a value of true has no effect, even after a restart. Without a value the attribute is gone after a restart.

**Comment by norman-knott** [comment]
@rahmanusta Any hint on my last comments?

**Comment by rahmanusta** [comment]
@norman-knott  You are right, for now the forceinclude attribute must be on top of root document, instead of the attributes table

**Comment by norman-knott** [comment]
@rahmanusta K, so should this issue be closed?
