### ISSUE TITLE
The context menu keyboard button does not work.

### ISSUE THREAD

**Issue by joanma747** [asciidocfx/AsciidocFX#221]
I almost use the context menu keyboard button for one thing but is very useful for me: spell check.

If I have a misspelled word marked in the screen I go there with the cursors and press the context menu and correct it easily without having to  move my hands out of the keyboard and use the mouse. This is far much faster.

It seems that the context menu keyboard button does not have any effect in asciidocfx. Can you add this functionality?. 

Thanks

**Comment by rahmanusta** [comment]
Yes, We can do that. Thanks

**Comment by rahmanusta** [comment]
Please try version 1.4.6 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.6

I now close this issue, if you think your issue is not fixed, please don't hesitate to reopen or comment the issue.

**Comment by joanma747** [comment]
Works nicely. Thanks,

 

Joan

 

De: Rahman Usta [mailto:notifications@github.com] 
Enviado el: jueves, 23 de junio de 2016 12:42
Para: asciidocfx/AsciidocFX
CC: Joan Masó; Author
Asunto: Re: [asciidocfx/AsciidocFX] The context menu keyboard button does not work. (#221)

 

Please try version 1.4.6 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.6

I now close this issue, if you think your issue is not fixed, please don't hesitate to reopen or comment the issue.
