### ISSUE TITLE
Slides with speaker notes: notes are always shown

### ISSUE THREAD

**Issue by convoi** [asciidocfx/AsciidocFX#222]
the expected syntax to use speaker notes on a slide is this

```
== Slide 1

Some text visible to the audience

[NOTE.speaker]
--
some note only visible to the speaker
--
```

However this results in the notes being shown to the audience.
It seems to me, that the jade template is not working correctly. It renders

```
<div id="" class="admonitionblock note data-line-16">
  <table>
    <tr>
      <td class="icon"><i title="Note" class="icon-note"></i>
<div id="" class="paragraph data-line-17">
  <p>some note only visible to the speaker</p>
</div>
      </td>
    </tr>
  </table>
</div>
```

But should render something like

```
<aside class="notes">some note only visible to the speaker</aside>
```

**Comment by rahmanusta** [comment]
Hi @convoi, can you update it on jade template ?

https://github.com/asciidocfx/AsciidocFX/blob/master/conf/slide/templates/revealjs/admonition.jade

Thanks for reporting.

**Comment by convoi** [comment]
I cannot find a difference to the admonition.jade that comes with ascidocFx 1.4.5.

**Comment by rahmanusta** [comment]
Yes, it is same, I mean you can override the default template.

**Comment by convoi** [comment]
i gave it a little try, but my knowledge about jade is none. seems like the node['$has_role?']('speaker') is always false. at least all my experiments with different ways of assigning a role failed.

is that small example i posted originally working for you?

**Comment by marcdexet** [comment]
I got the same in 1.5.5 version. 
How can I help ?
