### ISSUE TITLE
Generic disappear when pasting Java code

### ISSUE THREAD

**Issue by pysaumont** [asciidocfx/AsciidocFX#224]
Hi,

I am using AsciidocFx to write books and articles about Java, and I often need to past Java code snippets comming from IntelliJ. When doing so, type parameters simply disappear, which means that:

List<String > list = new ArrayList<>();

becomes:

List list = new ArrayList();

A minor problem is that pasting (from Intellij) inside a block of code adds  a full block, with delimiters. So adding a method in a class gives:
## [source,java]

public class MyClass {
## [source,java]

   public String addedMethod() {
## }

Even less important (but still annoying) is that a blank line is added at the end of the inserted code.

The workaround is to first paste to get the delimiters and then select the code and past raw, or to insert the delimiters by using the corresponding button and then paste raw. But it would be better if it worked just by pasting.

Thanks

Pierre-Yves

**Comment by rahmanusta** [comment]
Thank you @pysaumont for the reporting
