### ISSUE TITLE
Numbered Lines in Code Blocks

### ISSUE THREAD

**Issue by romulomourao** [asciidocfx/AsciidocFX#226]
Hi, I just started using AsciidocFX to write some documentation for my codes.
Now I'm trying to show the line numbers in the code blocks. It doesn't seem to work
I read at Asciidoc's documentation something like that:
```
[source, java, numbered]
---
//Some Java code
---

```
Then the output shows the line numbers of the code.
I don't know if I'm doing wrong. Is it possible to do that?

Thanks

**Comment by rahmanusta** [comment]
Hi, Asciidoctor.js and AsciidocFX use highlightjs, and it doesn't support line numbering.

**Comment by rahmanusta** [comment]
Highlight.js still has no support for line-numbering, but http://prismjs.com/ has it. @mojavelinux what do you think to support prism.js ?

**Comment by mojavelinux** [comment]
I recommend using prettify, which is integrated into core and supports line numbers.

**Comment by rahmanusta** [comment]
Woow, it is good, thank you @mojavelinux

**Comment by mojavelinux** [comment]
:+1: 

Of all the syntax highlighters, I think prettify is one of the best. It doesn't support as many languages, but the languages it does support it supports very accurately because it's a real parser, not just a regexp matcher.

**Comment by rahmanusta** [comment]
That's great! :+1: 

@romulomourao You can use this feature in new release.

**Comment by romulomourao** [comment]
oh..that's awesome 
thks @rahmanusta and @mojavelinux 
:+1:

**Comment by rahmanusta** [comment]
Please try version 1.4.6 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.6

You should use prettify.js like below

```
:source-highlighter: prettify
 
[source,java,numbered]
----
public class Hello{ 


}
----
```

I now close this issue, if you think your issue is not fixed, please don't hesitate to reopen or comment the issue.

**Comment by carun** [comment]
I would like to use `okaidia` style with prettify and not the default. Is this possible?
