### ISSUE TITLE
Include Content from a URI

### ISSUE THREAD

**Issue by ellipticview** [asciidocfx/AsciidocFX#228]
I'm trying to include from a URL, e.g.:

include::https://raw.githubusercontent.com/progit/progit2/master/README.asc[]

This is not working, I get error message:
Unresolved directive in <stdin> - include::https://raw.githubusercontent.com/progit/progit2/master/README.asc[]

Presumably this is because the allow-uri-read attribute needs to be set. See http://asciidoctor.org/docs/user-manual/#include-uri

How can this option be set in asciidocfx?

**Comment by rahmanusta** [comment]
Please try version 1.4.6 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.6

I now close this issue, if you think your issue is not fixed, please don't hesitate to reopen or comment the issue.
