### ISSUE TITLE
AFX 1.4.6 - generated HTML and line numbering

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#229]
The line numbering support in AFX 1.4.6 produce inconsistent results depending on how the output is generated.

Result 1 - viewed in the Editor - **correct**

![image](https://cloud.githubusercontent.com/assets/13682850/16314824/f8676b5c-397f-11e6-8de3-70193d11f8ac.png)

Result 2 - viewed using "Browser" option of AFX - **correct**

![image](https://cloud.githubusercontent.com/assets/13682850/16314782/d7269d50-397f-11e6-8b44-35e72c3575fc.png)

Result 3 - saved using "HTML" Save option - **incorrect** - only every 5th line is numbered.

![image](https://cloud.githubusercontent.com/assets/13682850/16314870/286e192c-3980-11e6-9c52-77a96ba2bb9a.png)

**Comment by rahmanusta** [comment]
Thank you @wfouche for reporting. I asked a question to Asciidoctor project. Here it is https://github.com/asciidoctor/asciidoctor/issues/640

**Comment by rahmanusta** [comment]
Unfortunately it seems the issue didn't fixed yet in Asciidoctor project. I'm using a CSS hack for this issue in preview. In HTML output you need to use custom css to Asciidoctor.css like below https://github.com/asciidocfx/AsciidocFX/blob/master/conf/public/css/asciidoctor-default-overrides.css#L70-L92

**Comment by wfouche** [comment]
Dropped.
