### ISSUE TITLE
Mixed line endings in version 1.4.6

### ISSUE THREAD

**Issue by jfabianmeier** [asciidocfx/AsciidocFX#230]
After updating to version 1.4.6, my HTML files have mixed line endings, i.e. some are Windows style, some are Unix style. I am using AsciidocFX on Windows 7. 

These line endings break my svn commits, so that I have to downgrade to 1.4.5.

Thanks in advance for repairing this.

Fabian Meier

**Comment by rahmanusta** [comment]
Hi @jfabianmeier, I'm sorry for  causing this issue. How can I help to solve this issue?

Thanks.

**Comment by jfabianmeier** [comment]
There must have been some change in the generation of HTML output from 1.4.5 to 1.4.6. My old HTML files are perfectly fine, but in my new files, the line endings are different between different lines (see attached screenshot). 

![mixedlineendings](https://cloud.githubusercontent.com/assets/14122518/16338087/9cc5bb32-3a1a-11e6-83ba-f3b0fad5f832.png)

I do not care whether the HTML file has Windows or Unix line endings, but there should not be a mixture of both.

**Comment by rahmanusta** [comment]
I opened an issue on Asciidoctor project https://github.com/asciidoctor/asciidoctor/issues/1804

**Comment by rahmanusta** [comment]
Hi @jfabianmeier , Can you reinstall the v1.4.6 again ?

Thanks
