### ISSUE TITLE
Can not input punctuation of Chinese

### ISSUE THREAD

**Issue by wgzhao** [asciidocfx/AsciidocFX#231]
I very like the Asciidoc editor. But I got a little trouble . I write in Chinese, so i hope get punctuation of Chinese . but it does not work.

e.g , at situation of Chinese IME，I enter '.' ，I want to get '。’, but I get '.' 。

**Comment by rahmanusta** [comment]
Hello, do you have any key for 。? Thanks

**Comment by wgzhao** [comment]
In any text editor with Chinese IME,when you enter '.' key, it will produce chinese punctuation "。".
