### ISSUE TITLE
Checklist does not render in html

### ISSUE THREAD

**Issue by seriouslyEnter** [asciidocfx/AsciidocFX#232]
Checklist does not render in html file.
But it does render in AsciidocFX Preview.

Could not test for pdf.

- [*] checked
- [x] also checked
- [ ] not checked
-     normal list

**Comment by rahmanusta** [comment]
Hi @seriouslyEnter;

Which version do you use? It renders correctly in version 1.4.6

![image](https://cloud.githubusercontent.com/assets/1158804/16452278/4cc9ed3e-3e10-11e6-8ee7-4630a08d9d27.png)

**Comment by seriouslyEnter** [comment]
I used: v1.4.5 AsciidocFX_Windows.zip
Checket with new v1.4.6 AsciidocFX_Windows.zip

It does render now.
Could not reproduce after old files were deleted and recreated with 1.4.6
But it did reproduce as long as I used files generated with v1.4.5
Seems fixed now.

**Comment by rahmanusta** [comment]
Thanks @seriouslyEnter.

Btw, this feature is HTML only, it is not supported in PDF or any other backends.
