### ISSUE TITLE
Main UI not correctly displayed on OSX

### ISSUE THREAD

**Issue by twasyl** [asciidocfx/AsciidocFX#233]
Given AsciidocFX 1.4.7 installed on OSX 10.11.5
When I start AsciidocFX
Then main UI is not displayed correctly (see the screenshot below)

![screenshot](https://cloud.githubusercontent.com/assets/2143048/16715337/e9c355f6-46dc-11e6-8a10-7b144ce0b834.png)

**Comment by rahmanusta** [comment]
It is very interesting :) is it reproducible ?

Thanks for reporting

**Comment by twasyl** [comment]
The issue seems to appears only at the first start of the application. Should I test it again by removing the configuration folder of the application? Will it make sense?

Cheers

**Comment by johnblommers** [comment]
I can confirm that this is a first-time launch problem on OS X. You just have to resize the window and the GUI will fix itself from that point on, and stay fixed every time you launch the app after that..

**Comment by rahmanusta** [comment]
Yes, I have seen the issue on Mac. It will be fixed in next version. Thanks

**Comment by twasyl** [comment]
Indeed, it is only a first start issue. Even by removing the configuration folder and restart the application, the UI is correctly displayed.

Thanks to all.

**Comment by rahmanusta** [comment]
@twasyl I suppose this issue fixed in latest releases ?

**Comment by twasyl** [comment]
I've tested again with the latest release and everything is working fine. Thanks
