### ISSUE TITLE
AFX 1.4.7 - document not rendered when AFX is launched.

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#234]
This bug is in both the initial 1.4.7 release as well as the re-released version (over the weekend). 

Reproducing the bug:
1. AFX is not running (close it if it is active).
2. From Windows Explorer, click on an .adoc file say test01.adoc
3. AFX is started and the adoc text of test1 is displayed, but the document output is not rendered.
4. From Windows Explorer, click on another .adoc file say test02.adoc
5. The second document's output is correctly rendered.
6. Now switch back to the first document. It is now also correctly rendered.

Summary of bug: An adoc file is not rendered when AFX is launched from Windows by clicking on an .adoc filename.

Workaround: 
1. Click on the .adoc file. AFX is started and the .adoc file is displayed.
2. Right-click on the window tab displaying the filename of the .adoc file and select "Go to Workdir" - magic, the .adoc is rendered and correctly displayed.

Could it be that the working directory is not correctly set at startup when opending a .adoc file at the same time?

**Comment by rahmanusta** [comment]
Thank you @wfouche for reporting. I will test it.

**Comment by wfouche** [comment]
Resolved in AFX 1.5.4
