### ISSUE TITLE
AFX 1.4.7 - syntax highlighting not working for CMD/BAT files.

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#235]
The following test document is rendered in AsciidocFX 1.4.7
````
= Test Document

== Test CMD Scripts

[source,cmd]
----
set MY_JARS=.;*.class
set CLASSPATH=%CLASSPATH%;%MY_JARS%
del *$py.class
call jython testcase_client.py --app_name="JavaTest1"
----
````

correctly using the *Browser* option as:

![image](https://cloud.githubusercontent.com/assets/13682850/16800437/96525898-48f5-11e6-87a6-a95318deca77.png)

However when saved to HTML using "HTML / Save" the output is incorrect (syntax highlighting is not working for CMD/BAT files):

![image](https://cloud.githubusercontent.com/assets/13682850/16800476/d0a97da0-48f5-11e6-8d24-2d5e328541f0.png)

**Comment by rahmanusta** [comment]
Hi @wfouche , Asciidoctor project adds highlight.js script from CDN and it has only 22 most used code highlighter. At this point, if you want to support others than 22, you should set your own highlightjs location with :highlightjsdir: attribute.
