### ISSUE TITLE
Justified text

### ISSUE THREAD

**Issue by teodorkasap** [asciidocfx/AsciidocFX#236]
hi,
I could not make the text justified along the line... Is there a way to achieve this?

**Comment by rahmanusta** [comment]
Dear @teodorkasap , What kind of text justify you mean?

**Comment by teodorkasap** [comment]
hi @rahmanusta ,

I mean the text alignment of a paragraph:
- align left
- center
- align right
- justified (evenly distributed along the line)

**Comment by rahmanusta** [comment]
For HTML output, you can write your own CSS. This issue may help you https://github.com/asciidoctor/asciidoctor-reveal.js/issues/33

**Comment by buelbr** [comment]
Use [.text-justify] just before the paragraph.
