### ISSUE TITLE
I have in the latest version a very weird behaviour

### ISSUE THREAD

**Issue by rahmanusta** [asciidocfx/AsciidocFX#237]
This issue came over gitter.

Ingo Simonis @ingosimonis 12:21

I have in the latest version a very weird behaviour: When typing a single character, say W, it shows up W. But when typing the next character, say h, I get "Wh" and a new line showing W. After a while, i have a down facing pyramid with the first character at the bottom, then lots of lines, each with one more character and the top lines shows the full text. Any ideas?

**Comment by msgilligan** [comment]
I just opened #239 and it may be a duplicate. I did attach a screenshot there.

**Comment by rahmanusta** [comment]
I don't totally know but it seems installer doesn't delete old installation files and old script causes this issue. If you remove installation dir manually, it will solve this issue.

**Comment by briandominick** [comment]
@rahmanusta Your advice above solved this problem for me, on El Capitan v10.11.5, AsciidocFX v1.4.7. Thanks!

**Comment by rahmanusta** [comment]
Great @briandominick
