### ISSUE TITLE
Crazy keyboard: many more (scrambled) characters appear than were typed.

### ISSUE THREAD

**Issue by msgilligan** [asciidocfx/AsciidocFX#239]
When I try to type in a new file I get unexpected results. After typing:

```
= Hello World
```

I see:

![screen shot 2016-07-14 at 6 06 45 pm](https://cloud.githubusercontent.com/assets/61612/16860530/e9f0060a-49ed-11e6-98cd-6aa9c49e2410.png)

This is on Mac OS X 10.10.5.

**Comment by rahmanusta** [comment]
Hi @msgilligan , When did you install the latest release?

**Comment by msgilligan** [comment]
I downloaded the latest download (1.4.5, I believe) and then run the updated to get 1.4.7 -- all on the same day that I reported the bug.

**Comment by msgilligan** [comment]
I looks like the updater copied in new versions of JARs but didn't remove the old ones.

![screen shot 2016-07-17 at 4 05 21 pm](https://cloud.githubusercontent.com/assets/61612/16903628/6f40d536-4c38-11e6-9f87-d245acb01d55.png)

**Comment by msgilligan** [comment]
I deleted my copy of the app and downloaded the latest DMG and re-installed and everything seems to be working now. Will the same problem happen when there is a new version and the updated runs?
