### ISSUE TITLE
Chinese anchor meaningless

### ISSUE THREAD

**Issue by gudaoxuri** [asciidocfx/AsciidocFX#241]
Hi,
Like this : http://gudaoxuri.github.io/bd-lab/#true--2 , This url is [1.1. 课程概要] section , It doesn't make any sense.

**Comment by rahmanusta** [comment]
Hi @gudaoxuri, how can we convert chinese characters to hash parameters? Do you have any opinion for that to propose to Asciidoctor team?

**Comment by gudaoxuri** [comment]
Using URLEncoding is better ?
