### ISSUE TITLE
Write books via AsciidocFX (and a possible Book Template project)

### ISSUE THREAD

**Issue by JordanMartinez** [asciidocfx/AsciidocFX#243]
I want to write actual books, not software documentation, via AsciidocFX. This is similar to [what has already been done and linked to in the ReadMe](https://github.com/asciidocfx/AsciidocFX#books-written-with-asciidocfx). 

To do this, I'm thinking of using these three tools: 
- Gradle
  - check and warn about broken links/references via HTMLSanityCheck
  - automatically build all the backends and store them in one folder
  - update the book's revision date / number programmatically
  - and other things that are better automated...
- IntelliJ Idea
  - for GUI Git integration as an immediate workaround to #206 
  - for editing the build.gradle file as needed
- AsciidocFX
  - for actually writing and immediately seeing the result

First, do you know of any reasons why this might not work? If the IDE and AsciidocFX are both watching/modifying the same file, will that lead to problems?

Second, and assuming this does work, I thought it would be wise to create a book template that others can fork and then build upon. The current examples in [asciidoc-gradle-examples](https://github.com/asciidoctor/asciidoctor-gradle-examples) all apply the java plugin because they assume it's being used for software documentation. However, in my case, this isn't necessary. 
So, my current implementation of this template idea is [asciidoc-gradle-book-template](https://github.com/JordanMartinez/asciidoc-gradle-book-template). I'd appreciate any help in getting this template properly configured and set up. Once it's done, perhaps we could link to this template project in the ReadMe.

**Comment by rahmanusta** [comment]
Hello @JordanMartinez , what does not work ? AsciidocFX brings a comfortable writing experiences for developers and authors. It has an book sample menu, did you try it ? If you have any idea for this, I'm open for it.

**Comment by JordanMartinez** [comment]
>  It has an book sample menu, did you try it ?

Yes, I've tried it and it works quite well. However, I'm looking for more features than just what AsciidocFX currently offers: Git integration & automated testing of links. The VCS integration isn't supported but will be in the future I'm sure. I'm not so sure about the automated testing.

Additionally, I've noticed that there is a small but still noticeable lag when I'm using AsciidocFX to write asciidoc as opposed to my IDE. I'm not sure if this could be fixed if I changed a JVM argument. So, that's why I'm currently using my IDE and a few plugins instead of this project.

**Comment by damko** [comment]
I also experience some small but annoying lag when I'm writing, even when the preview is disabled.

**Comment by rahmanusta** [comment]
@damko Can you please share more details?

**Comment by damko** [comment]
@rahmanusta with pleasure, what shall I provide exactly?

I have openJDK8 installed. I tried to tweak a  little the option file but there is no change. Everything works perfectly and the application is very good but it feels like _rusted_

If you had the change to work with remote terminals on poor connections, you can totally understand which kind of lags I'm experiencing: everything feels delayed by some 0.1 to 0.8 seconds (approximately).

No other editor I use has this issue but it's true that this is the only java based editor I have.

Maybe I should try Eclipse and see if it behaves differently?

**Comment by rahmanusta** [comment]
Can you check https://bugs.openjdk.java.net/browse/JDK-8096192, and try using ` -Dprism.forceGPU=true` JVM parameter in .vmoptions file in AsciidocFX installation directory?
