### ISSUE TITLE
[ENHANCEMENT] Correct keyboard binding

### ISSUE THREAD

**Issue by twasyl** [asciidocfx/AsciidocFX#244]
Hi,

I was reading the README and saw you have an issue regarding the keyboard binding on OSX where JavaFX relies on the 'QWERTY' map. I had the exactly same problem I solved in SlideshowFX so I point you out my solution if you want.

I created the [KeyEventUtils ](https://github.com/twasyl/SlideshowFX/blob/master/SlideshowFX-utils/src/main/java/com/twasyl/slideshowfx/utils/keys/KeyEventUtils.java)class where you can find an example of usage [here](https://github.com/twasyl/SlideshowFX/blob/master/SlideshowFX-app/src/main/java/com/twasyl/slideshowfx/controls/SlideContentEditor.java#L43).

Hope it helps.

Cheers

**Comment by rahmanusta** [comment]
Dear @twasyl, thank you for sharing KeyEventUtils class. In latest versions of AsciidocFX, I had developed two helper class to manager KeyBoard events seamlessly.

https://github.com/asciidocfx/AsciidocFX/tree/master/src/main/java/com/kodcu/keyboard

These helpers are now good.
