### ISSUE TITLE
Strange text in header and footer in pdf documents

### ISSUE THREAD

**Issue by QueJo** [asciidocfx/AsciidocFX#245]
Hi, 
Recent installed version 1.4.8, when exporting documents to pdf  "Java EE WebSocket" text appears in header, next to the page number, and "Papatya Yayıncılık Eğitim" appears in footer, to the right.
Only in odd pages.
Previous versions didn't has the issue.

**Comment by rahmanusta** [comment]
Hahaha :) sorry, I pushed my last book's style and it has static texts.

I will revert changes today, and push in a new version.

**Comment by rahmanusta** [comment]
Apart from this issue, which pdf style is better, this one or better one?

**Comment by QueJo** [comment]
Personally,
I like new format, table and image footers fit better, I prefer new quotes style too. And i like new chapter cover. However I prefer former font, sans serif,  probably because I make teaching materials and a sans serif font seems better projected.
I liked the two horizontal rules separating footer and header from the old style.
With the new style is difficult to see the frame in code blocks in non professional printed documents.

Thanks for the response.

**Comment by rahmanusta** [comment]
@QueJo Update to latest please https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.4.9
