### ISSUE TITLE
Community Group

### ISSUE THREAD

**Issue by rajmahendra** [asciidocfx/AsciidocFX#25]
Create a group for the community to discuss new ideas etc before creating issue/features. 

Like
asciidocfx-dev - for core developers/contributors
asciidocfx-users  - for end user related discussions.

**Comment by GeekMustHave** [comment]
I'm doing a YouTube series on Easier Tech Writing focusing on ASCIIDoc.  Some of the comments from my viewers indicate they want a Windows method with no "Terminal" usage required.

I have used ASCIIDocFX for some time and stopped a while back as I was having some issues.  Just started again and I think this is a great tool for the technical writer.

I'm going to write a separate video in the series just for ASCIIDocFX.  If there is anything you think I should include outside of what is in the regular documentation could you let me know?

What is the minimum version of Java Windows required for ASCIIDocFX?

Is there a portable version of ASCIIDocFX?
