### ISSUE TITLE
Fail to launch app when upgrading to version 1.5

### ISSUE THREAD

**Issue by drmn68** [asciidocfx/AsciidocFX#253]
H/W: Macbook Pro mid-2012
S/W: MacOS 10.12
JDK version: 1.8.0_40

After installation and launch app, there is no window show and I am not able to exit the app. Have to kill the process from Activity Monitor.

When I roll back to 1.4.9, everyone is ok.

**Comment by rahmanusta** [comment]
Could you remove manually installation dir and reinstall the v1.5.0 again?

**Comment by drmn68** [comment]
yes, manually remove old release and re-install v1.5.0 did work.
Thanks for quick help
