### ISSUE TITLE
Generated pdf does not containt symbols with diacritics

### ISSUE THREAD

**Issue by mmucha-redhat** [asciidocfx/AsciidocFX#257]
Instead of for example:
Angličtina 5.ročník ZŠ
is this printed:
Angli#tina 5.ro#ník ZŠ

Notice upper case Š — it seems that maybe only invalid font is used, but I did not succeed in changing it. I found notice, that RC6 might fix this, but failed to locate this version...
——
no errors during pdf build:
DEBUG => Docbook successfully validated
DEBUG => PDF conversion started
DEBUG => target-resolution set to: 300.0dpi (px2mm=0.08466666)
DEBUG => User configuration found for MIME type application/pdf
DEBUG => User configuration found for MIME type application/pdf
DEBUG => PDF conversion ended

**Comment by rahmanusta** [comment]
Hello Dear @mmucha-redhat, 

Do you have microsoft core fonts in your system ?

````
Ubuntu/Debian

sudo apt-get install ttf-mscorefonts-installer
````

**Comment by rahmanusta** [comment]
Hi @mmucha-redhat, did it help you?

**Comment by mmucha-redhat** [comment]
Hi @rahmanusta.
Big apologies for late reply. Yes it did help me, thank you very much.

M.

**Comment by rahmanusta** [comment]
You are welcome @mmucha-redhat
