### ISSUE TITLE
Cheatsheet contains multiple languages

### ISSUE THREAD

**Issue by sluedecke** [asciidocfx/AsciidocFX#258]
The cheatsheet provided with AsciidocFX contains text in multiple languages.  Can you please harmonize it, for example to be english only?

**Comment by rahmanusta** [comment]
You are right @sluedecke, if you know enough Asciidoc language, could you please send a pull request for it?

**Comment by dclar43** [comment]
I was going to use this cheatsheet in a documentation presentation at work but the random switch to Turkish(?) part way through makes that a no-go. Just commenting to show there's still interest in an English-only version. (Sorry, I don't know enough Turkish to help out here)

**Comment by KlugB** [comment]
This seems still to be an issue. Any chance this will be solved?

**Comment by Ayowel** [comment]
@KlugB Funny you should ask at the time I decided to give it a go. If you see any typo, do let me know or propose a PR to fix it.
