### ISSUE TITLE
Does not save Ace Theme change

### ISSUE THREAD

**Issue by seriouslyEnter** [asciidocfx/AsciidocFX#260]
New Bug for v1.5.4
Change in Settings for Ace Theme will not be saved.
Always changes back to "tomorrow_night" Theme after restart.

**Comment by rahmanusta** [comment]
Thank @seriouslyEnter, I have tested it and it is like you report.

**Comment by rahmanusta** [comment]
Could you please test v1.5.5?

**Comment by seriouslyEnter** [comment]
tried v1.5.5
Theme change gets saved after restart!
So far everything is good now.

But it does get saved even if I don't klick the save button!
Not sure this was intended or not?
But in this case an improvement would be a "reset" or "reset to previous" Button in settings.

**Comment by rahmanusta** [comment]
AsciidocFX saves automatically but you can immediately save settings. I agree with you, It could be good to have reset functionalty
