### ISSUE TITLE
Distribution without JRE does not start on linux

### ISSUE THREAD

**Issue by pkeller** [asciidocfx/AsciidocFX#261]
I get a window with a `NoClassDefFoundError`:
![screenshot-startup error](https://cloud.githubusercontent.com/assets/1384842/20096070/218c392c-a5a0-11e6-96af-77299efcf4db.png)

This happens with both versions 1.5.2 and 1.5.4. The distributions with an included JRE start up OK.

I had a look at the startup script, but I can't really follow what is going on, sorry. I am running openSUSE Leap 42.1, and the following Java version:

```
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (IcedTea 3.1.0) (suse-15.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)
```

**Comment by rahmanusta** [comment]
Hi @pkeller, it means OpenJFX didn't installed on your system.

**Comment by rahmanusta** [comment]
You can install Oracle JDK, or install OpenJFX on your system. Because, OpenJDK doesn't include OpenJFX by default. I don't know whether Suse provide OpenJFX packages but you can build OpenJFX by instructions. https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX

**Comment by pkeller** [comment]
Thanks: starting with Oracle JRE works (do I really need the JDK to run AsciidocFX? Might I hit problems if I use the JRE?).

OpenSUSE don't provide OpenJFX as a standard package, and someone else [asking about it on their forums](https://www.opensuse-forum.de/thread/37039-openjfx/) got the same advice: use Oracle's, or build it yourself.

Perhaps this could be mentioned explicitly in the [linux AsciidocFX installation instructions](http://asciidocfx.com/#trueinstall-on-linux)? (By the way, the download links there are out of date: they get version 1.5.2)

**Comment by rahmanusta** [comment]
Yes @pkeller, JRE and JavaFX Runtime are required to run AsciidocFX, not JDK.

Could you please make a pull request on installation instructions ?

**Comment by pkeller** [comment]
OK - I'll do that. Thanks for your help.

**Comment by pkeller** [comment]
Actually don't think that I can create a pull request for the links that are wrong, because they are on asciidocfx.com, here: http://asciidocfx.com/#truehow-to-install-asciidocfx

The links in [index.adoc](https://github.com/asciidocfx/AsciidocFX/blob/d3878ab7413edc200d3cbb683d70c2b20fa6cb9b/index.adoc) in this repo are correct.

**Comment by rahmanusta** [comment]
You are right, I have update it manually.
