### ISSUE TITLE
AFX 1.5.4 - PlantUML diagrams wrong size.

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#264]
Hi @rahmanusta,

A PlantUML diagram that I used successfully in an older version of AFX is rendered as a much larger image in AFX 1.5.4.

```
[plantuml, network-diagram, png]
----
@startdot
digraph G {
    node [shape=box]
	subgraph cluster_0 {
		node [style=filled];
		WIN_11 -> WIN_12 -> WIN_13;
		label = "WIN - Site 1";
		color = purple
	}

	subgraph cluster_1 {
		node [style=filled];
		WIN_21 -> WIN_22 -> WIN_23;
		label = "WIN - Site 2";
		color = purple
	}
	start -> WIN_11;
	start -> WIN_21;
	WIN_13 -> end;
	WIN_23 -> end;
    
    users [shape=Mdiamond]
    users -> start
    start [label="WIN_00", shape=invhouse]
	end [label="Peer-to-Peer\nReplication", shape=Msquare];
}
@enddot
----
```
appears as 

![network-diagram-1-4-7-](https://cloud.githubusercontent.com/assets/13682850/20304955/ac5148c2-ab3b-11e6-9b1b-252a0e278362.png)

when rendered using AFX 1.4.7, but appears much bigger when rendered using AFX 1.5.4 as shown below.

![network-diagram](https://cloud.githubusercontent.com/assets/13682850/20304979/c648df60-ab3b-11e6-8b6a-8ed55f9b7137.png)

Do you know what could be causing this discrepancy?

Thanks,

Werner

**Comment by rahmanusta** [comment]
It depends on image scale, zoom and it is dpi for plantuml. I had increased default dpi to get better quality in AsciidocFX.

So, You can give height to images or you can change dpi in Settings > Extension Settings in version 1.5.5

**Comment by wfouche** [comment]
> Settings > Extension Settings in version 1.5.5

Thanks. Workaround confirmed for 1.5.5 by setting DPI to 100.
