### ISSUE TITLE
Is there a Find and replace shortcut in AsciidocFX?

### ISSUE THREAD

**Issue by sengopal** [asciidocfx/AsciidocFX#269]
I use AsciidocFX for writing technical documentation and sometimes need to replace certain text. I am unable to find the replace command or shortcut. Tried the mac `Cmd + H` and and `Cmd+Opt+H` and few others, but with no luck. 

Update: Checked the documentation and found http://asciidocfx.com/#truesome-shortcuts and https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts from there. The `Command-Option-F` does not work on 1.5.4 version on Mac.

Any suggestions please?

**Comment by rahmanusta** [comment]
Hello @sengopal, could you please try to push Command-F twice ?

**Comment by rahmanusta** [comment]
Does it work for you @sengopal  ?

**Comment by sengopal** [comment]
@rahmanusta Thanks so much. It worked.  Could we please add it to the shortcut list. It would really help for searchers like me :)

**Comment by rahmanusta** [comment]
You are welcome @sengopal, could you please edit Readme.adoc file for that?

Thanks

**Comment by sengopal** [comment]
Of course :) Raised https://github.com/asciidocfx/AsciidocFX/pull/273 to add this to the Readme.adoc.

**Comment by rahmanusta** [comment]
Thank you dear :)
