### ISSUE TITLE
`=== title` export to pdf will be `x.y. ####`

### ISSUE THREAD

**Issue by TomeOkin** [asciidocfx/AsciidocFX#276]
`=== title` when export to pdf, expire `x.y. title`, but the facts is `x.y. ####`. Catalog display correctly.

**Comment by rahmanusta** [comment]
Hello @TomeOkin, I didn't understand your question. Could you please clarify it for me?

**Comment by TomeOkin** [comment]
```
== title

=== 标题
```

save as pdf

```
title
1. title
1.1. ##
```

**Comment by rahmanusta** [comment]
https://github.com/asciidocfx/AsciidocFX/blob/master/README.adoc#known-issues

**Comment by TomeOkin** [comment]
I using window.

**Comment by rahmanusta** [comment]
Hmm, you are missing fonts on your Windows. You can change default fonts here  https://github.com/asciidocfx/AsciidocFX/blob/master/conf/docbook-config/fo-pdf.xsl

**Comment by TomeOkin** [comment]
thanks

**Comment by vvhh2002** [comment]
how about macOS ？
