### ISSUE TITLE
Allow read from uri

### ISSUE THREAD

**Issue by seinecle** [asciidocfx/AsciidocFX#283]
Hi,

I need to read an image from an uri. This is currently blocked because of:
http://asciidoctor.org/docs/user-manual/#include-uri

I am a newbie to AsciidocFX, and I don't know where I should change the attributes (allow-uri-read and the safe mode to SAFE) in the GUI?

Thanks!

**Comment by rahmanusta** [comment]
Hi @seinecle ,

If you want to include content from anywhere you can use :forceinclude: in AsciidocFX.

**Comment by seinecle** [comment]
Thanks ! Just this ":forceinclude:" ?
Is there a doc (even Javadoc) which explains a bit more?

**Comment by seinecle** [comment]
I added it like this, but with no effect?

Beginning of my AsciiDoc:

```
= Authoring open, web-friendly courses and tutorials
:forceinclude:

by Clément Levallois (http://www.twitter.com/seinecle[@seinecle]), first version 27/12/2016
```

**Comment by rahmanusta** [comment]
Attributes should be at top of documents.

**Comment by rahmanusta** [comment]
@sbaechler did it help you? ":forceinclude:" is AsciidocFX special (not documented yet), normally AsciidocFX doesn't use :allow-uri-read: attribute.
