### ISSUE TITLE
Feature request: ASCII Math

### ISSUE THREAD

**Issue by mlopezgva** [asciidocfx/AsciidocFX#286]
Hi!

I'm very surprised the a project name **ASCII**DocFX doesn't support **[ASCIIMath](http://asciimath.org)**!

[***MathJax*** already supports it](http://docs.mathjax.org/en/latest/asciimath.html), and it looks very "asciidoc/markdown" like. Could be a good feature, because it integrates better with AsciiDoc than LaTeX and alike. Using LaTeX for anything is always a PITA... that's why **ASCIIDoc** or **MarkDown** exist, in fact. :) so, mathematical expressions should also be easier to type. And looking around, from **MathJax** thanks to **_StackEdit_**, I found **AsciiMath**.

Just to make a point, see the difference between TeX-like and asciiMath with these examples:

- Cauchy-Schwarz Inequality, this is terrific:
  - TeX:
    `\[ \left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right) \]`
  - asciiMath:
    `(sum_(k=1)^n a_kb_k)^2 <= (sum_(k=1)^n a_k^2) (sum_(k=1)^n b_k^2)`

![captura de pantalla de 2016-07-14 17 01 13](https://cloud.githubusercontent.com/assets/996070/16855241/d0114eae-49ea-11e6-8336-41c1a189cc66.png)
- Lorenz:
  - TeX:
    `\dot{x} = \sigma(y-x) \\ \dot{y} = \rho x - y - xz \\ \dot{z} = -\beta z + xy`
  - asciiMath
    `dotx = sigma(y-x)`
    `\doty = rho x-y - xz`
    `\dotz = -beta z + xy`
- Probability:
  - TeX:
    `\[P(E)   = {n \choose k} p^k (1-p)^{ n-k } \]`
  - asciiMath:
    `P(E) = ((n),(k)) p^k (1-p)^(n-k)`

![captura de pantalla de 2016-07-14 17 18 59](https://cloud.githubusercontent.com/assets/996070/16855268/fa423bb6-49ea-11e6-9642-b78d58a108bf.png)
- And, of course, the quadratic formula:
  - TeX:
    `-b \pm \sqrt{b^2 - 4ac} \over 2a`
  - asciiMath
    `x=-b+- sqrt(b^2-4ac)/2a`

![captura de pantalla de 2016-07-14 17 18 33](https://cloud.githubusercontent.com/assets/996070/16855277/02ed5e62-49eb-11e6-887b-61325ceb70b3.png)

Some more examples comparing the same formulas in Markdown Plus help:

1) 
![image](https://cloud.githubusercontent.com/assets/996070/18685185/53077b34-7f4d-11e6-804d-2a5801320653.png)
2) 
![image](https://cloud.githubusercontent.com/assets/996070/18685194/61924742-7f4d-11e6-859a-71d5d5f994c5.png)
3) 
![image](https://cloud.githubusercontent.com/assets/996070/18685199/68b639c0-7f4d-11e6-8693-7681d7a274d5.png)
4) 
![image](https://cloud.githubusercontent.com/assets/996070/18685211/74573a36-7f4d-11e6-82f6-abd23acfc712.png)
5) 
![image](https://cloud.githubusercontent.com/assets/996070/18685221/7c129d56-7f4d-11e6-9b89-b094c8472ff2.png)

| Núm. | LaTeX | length | ASCII Math | length |
| --: | --- | --: | --- | --: |
| 1 | `\dfrac{ \tfrac{1}{2}[1-(\tfrac{1}{2})^n] }{ 1-\tfrac{1}{2} } = s_n` | 66 | `(1/2[1-(1/2)^n])/(1-(1/2))=8_n` | **30** |
| 2 | `\oint_C x^3\, dx + 4y^2\, dy` | 28 | `oint_Cx^3 dx+4y^2 dy` | 21 |
| 3 | `2 = \left( \frac{\left(3-x\right) \times 2}{3-x} \right)` | 57 | `2=(((3-x)xx2)/(3-x))` | **20** |
| 4 | `\sum_{m=1}^\infty\sum_{n=1}^\infty\frac{m^2\,n} {3^m\left(m\,3^n+n\,3^m\right)}` | 80 | `sum_(m=1)^oosum_(n=1)^oo(m^2 n)/(3^m(m3^n+n3^m)` | **48** |

And the last one is so big (169 characters), I must put it as a code block...

```
phi_n(\kappa) =
 \frac{1}{4\pi^2\kappa^2} \int_0^\infty
 \frac{\sin(\kappa R)}{\kappa R}
 \frac{\partial}{\partial R}
 \left[R^2\frac{\partial D_n(R)}{\partial R}\right]\,dR
```

And, ASCIImath version:

```
phi_n(kappa) = 1/(4pi^2 kappa^2)
 int_0^oo (sin(kappa R))/(kappa R)
 del/(del R)
[R^2 (del D_n (R))/(del R)] del R
```

Its not so long (112 characters, including spaces, I could've put it in a single line:

`phi_n(kappa) = 1/(4pi^2 kappa^2)  int_0^oo (sin(kappa R))/(kappa R)  del/(del R) [R^2 (del D_n (R))/(del R)] del R`

See the difference? And there's another one: I had only peeked at the docs to see the _token_ of the `oint`. **Everything else** I was able to type it without help, it's "natural" (something **LaTeX** is definitely not ;)).

**Comment by rahmanusta** [comment]
Hello @mlopezgva thanks for the detailed explanation. AsciidocFX supports AsciiMath syntax. But the documentation wasn't updated :) 

![image](https://cloud.githubusercontent.com/assets/1158804/21671641/657ea72a-d325-11e6-9f07-febe37483df6.png)

**Comment by mlopezgva** [comment]
Oh... OK.
Thank you.

Feel free to use some of my eamples to update the docs. :-D

**Comment by rafa2000** [comment]
Yes but the display is too big compared with the sorrouding text. Any way to fix that? The same problem, of too large display, happens when rendering laTeX. Using [svg] output, instead of [png], erases de output.

**Comment by rahmanusta** [comment]
You can play with width/ height.
