### ISSUE TITLE
Level2,3....title display chinese as "#" while saveing as pdf 

### ISSUE THREAD

**Issue by wilfredvon** [asciidocfx/AsciidocFX#287]
asciidoc 
= 测试 level 0 =

== 测试 level 1 ==

=== 测试 leve 2 ===

to pdf:

测试 level 0

1. 测试 level 1

1.1.##level 2

env: windows 7 + asciidocfx 1.5.5

**Comment by rahmanusta** [comment]
There should be at least 2 lines or text between headers.

**Comment by wilfredvon** [comment]
@rahmanusta  I Have added towe more lines between header. Chinese still be displayed as "#" in tiltle.

here is the asciidoc:
![image](https://cloud.githubusercontent.com/assets/25024557/21836192/19ef273e-d7fe-11e6-93c9-681d3e7f7b06.png)


The PDF content:

![image](https://cloud.githubusercontent.com/assets/25024557/21836167/ead165f2-d7fd-11e6-8b5c-948025d2aada.png)

**Comment by wilfredvon** [comment]
fop  can't support Chinese both bold and italic.  modify  "AsciidocFX\conf\docbook-config\fo-pdf.xsl". replace:
<xsl:attribute-set name="section.title.level1.properties">
        <xsl:attribute name="font-size">12pt</xsl:attribute>
        <xsl:attribute name="font-weight">bold</xsl:attribute>
    </xsl:attribute-set>

    <xsl:attribute-set name="section.title.level2.properties">
        <xsl:attribute name="font-size">12pt</xsl:attribute>
        <xsl:attribute name="font-style">italic</xsl:attribute>
        <xsl:attribute name="font-weight">bold</xsl:attribute>
    </xsl:attribute-set>

    <xsl:attribute-set name="section.title.level3.properties">
        <xsl:attribute name="font-size">12pt</xsl:attribute>
        <xsl:attribute name="font-style">italic</xsl:attribute>
        <xsl:attribute name="font-weight">bold</xsl:attribute>
    </xsl:attribute-set>

    <xsl:attribute-set name="section.title.level4.properties">
        <xsl:attribute name="font-size">12pt</xsl:attribute>
        <xsl:attribute name="font-style">italic</xsl:attribute>
        <xsl:attribute name="font-weight">bold</xsl:attribute>
    </xsl:attribute-set>

    <xsl:attribute-set name="section.title.level5.properties">
        <xsl:attribute name="font-size">12pt</xsl:attribute>
        <xsl:attribute name="font-style">italic</xsl:attribute>
        <xsl:attribute name="font-weight">bold</xsl:attribute>
    </xsl:attribute-set>

    <xsl:attribute-set name="section.title.level6.properties">
        <xsl:attribute name="font-size">12pt</xsl:attribute>
        <xsl:attribute name="font-style">italic</xsl:attribute>
        <xsl:attribute name="font-weight">bold</xsl:attribute>
    </xsl:attribute-set>


with:

<xsl:attribute-set name="section.title.level1.properties">
        <xsl:attribute name="font-size">12pt</xsl:attribute>
        <xsl:attribute name="font-weight">bold</xsl:attribute>
    </xsl:attribute-set>

    <xsl:attribute-set name="section.title.level2.properties">
        <xsl:attribute name="font-size">12pt</xsl:attribute>
        
        <xsl:attribute name="font-weight">bold</xsl:attribute>
    </xsl:attribute-set>

    <xsl:attribute-set name="section.title.level3.properties">
        <xsl:attribute name="font-size">12pt</xsl:attribute>
        
        <xsl:attribute name="font-weight">bold</xsl:attribute>
    </xsl:attribute-set>

    <xsl:attribute-set name="section.title.level4.properties">
        <xsl:attribute name="font-size">12pt</xsl:attribute>
        
        <xsl:attribute name="font-weight">bold</xsl:attribute>
    </xsl:attribute-set>

    <xsl:attribute-set name="section.title.level5.properties">
        <xsl:attribute name="font-size">12pt</xsl:attribute>
        
        <xsl:attribute name="font-weight">bold</xsl:attribute>
    </xsl:attribute-set>

    <xsl:attribute-set name="section.title.level6.properties">
        <xsl:attribute name="font-size">12pt</xsl:attribute>
        
        <xsl:attribute name="font-weight">bold</xsl:attribute>
    </xsl:attribute-set>
