### ISSUE TITLE
Project support for JBake

### ISSUE THREAD

**Issue by rajmahendra** [asciidocfx/AsciidocFX#29]
[JBake](http://jbake.org)  is "Jekyll of the JVM" it also supports Asciidoc files support. If we can some how create project structure through AsciidocFX than many it help people to create static website throught the application.

If internally generate the website and who the full website in the preview.

(this issue may be out of scope but still we can make it a "help wanted" tag)

**Comment by lefou** [comment]
Creating the initial file layout for a new JBake project is already very simple, just run `jbake -i` and you already have a starting point. Also, many JBake users use JBake through a build tool like Maven or Gradle.

I one uses AsciiDoc files with JBake, you can already edit them with AsciidocFX. So what is needed in this ticket to make sense are some concrete idea/wishes how both projects could integrate more.

One concrete integration point I can see it the support of the `jbake.properties` file. That file hosts the JBake configuration, but you can also define your own properties there. JBake allows you to access those properties from the template files (e.g. Freemarker), but if you use AsciiDoc files, you can also access them via AsciiDoc atrributes. So, you could add support to lookup some attributes from a properties files and make them available, e.g. when rendering the file. That way, the rendered preview could contain the correct values.

**Comment by rajmahendra** [comment]
@lefou Ya i can understand your point my idea is if AFX can have project creation and running jbake project internally (As AFX having internal server) it can help any JBake+Asciidoc project into AFX.  Ya the rendering idea also can be implement internally to show full page update internally it also helps both project exist side by side ! This also gives way to use any other tool which uses asciidoc.  Its just a thought. May be not in scope !
