### ISSUE TITLE
PlantUML Salt compatibility with Asciidoctor

### ISSUE THREAD

**Issue by ellipticview** [asciidocfx/AsciidocFX#296]
This is an example of including a salt diagram in AsciiDocFX:

```
[uml,file="abc.png"]
----
@startsalt
{
{T
 + index.adoc
 ++ America
 +++ Canada
 +++ USA
 ++++ New York
 ++++ Boston
 +++ Mexico
 ++ Europe
 +++ Italy
 +++ Germany
 ++++ Berlin
 ++ Africa
}
}
@endsalt
----
```

In Asciidoctor, a different attribute list is required:
```
[salt, "abc" png]
```

This gives issues when using both tools.

**Comment by rahmanusta** [comment]
Hello, you can even use the following; Isn't it same with Asciidoctor's syntax ?

```
[uml,abc,png]
----
@startsalt
{
{T
 + index.adoc
 ++ America
 +++ Canada
 +++ USA
 ++++ New York
 ++++ Boston
 +++ Mexico
 ++ Europe
 +++ Italy
 +++ Germany
 ++++ Berlin
 ++ Africa
}
}
@endsalt
----
```

**Comment by rahmanusta** [comment]
I didn't know the salt block, it can be included in AsciidocFX

**Comment by ellipticview** [comment]
```
[uml,abc,png]
```

The above syntax in Asciidoctor gives this message:
```
WARNING: tree.adoc: line 19: invalid style for listing block: uml
```

**Comment by rahmanusta** [comment]
Hmm, what is the correct syntax for Asciidoctor ?

**Comment by ellipticview** [comment]
There seem to be 2 variations. See:

- http://discuss.asciidoctor.org/Using-asciidoc-diagramm-with-plantuml-salt-syntax-td2850.html
- https://github.com/asciidoctor/asciidoctor-diagram/issues/66

I think the preferred syntax is this:
```
[plantuml, basefilename, svg]
----
@startsalt
{
{T
+ A
++ a
+ B
++ b
}
}
@endsalt
----
```

**Comment by rahmanusta** [comment]
You can use this in AsciidocFx

**Comment by ellipticview** [comment]
Correct. Further syntax differences tracked in #295.

**Comment by WyxXu** [comment]
> There seem to be 2 variations. See:
> 
> * http://discuss.asciidoctor.org/Using-asciidoc-diagramm-with-plantuml-salt-syntax-td2850.html
> * [Enable "salt" sketches in plantuml diagrams  asciidoctor/asciidoctor-diagram#66](https://github.com/asciidoctor/asciidoctor-diagram/issues/66)
> 
> I think the preferred syntax is this:
> 
> ```
> [plantuml, basefilename, svg]
> ----
> @startsalt
> {
> {T
> + A
> ++ a
> + B
> ++ b
> }
> }
> @endsalt
> ----
> ```

 this is helpfull, still work in 2023
