### ISSUE TITLE
Portuguese language in spell checker

### ISSUE THREAD

**Issue by fsmunoz** [asciidocfx/AsciidocFX#301]
Hello,

I'm not sure on the exact solution the spellchecker is based on so perhaps this is something that can be enabled by the end user, but if so I was unable to find much information. I use AsciiDocFX with several teams and one thing that has been noted is the absence of Portuguese language spell-checking (either for Portugal or Brazil). I'm currently reviewing them in other editors but the integration would be nice.

If there is anything I can do to help I'm available.

**Comment by rahmanusta** [comment]
Hello @fsmunoz 

This is for you https://github.com/asciidocfx/AsciidocFX/wiki/Add-new-language-to-AsciidocFX-Spell-Checker

**Comment by fsmunoz** [comment]
Thank you @rahmanusta , I'll give it a go!

**Comment by rahmanusta** [comment]
You can now use the new AsciidocFX version 1.5.6 

https://github.com/asciidocfx/AsciidocFX/releases
