### ISSUE TITLE
How do I create a UML diagram within AsciidocFX?

### ISSUE THREAD

**Issue by Jemerson1224** [asciidocfx/AsciidocFX#314]
Hello All,
I recently installed AsciidocFX with PlantUMl on my Windows computer. I need to create UML diagrams 
within AsciidocFX when I enter a piece of JavaScript code that shows class to class extensions. 

How do I display a UML diagram for the code in the AsciidocFX Preview area?

Thanks
Jim Emerson

**Comment by rahmanusta** [comment]
You can do it like below;

```
[uml]
----
Elma -> Armut
----
```

**or**

```
[uml,blabla.png]
----
Elma -> Armut
----
```

**Comment by Jemerson1224** [comment]
Hi Rahman,

Thanks. I'll try it.
Jim

**Comment by rahmanusta** [comment]
@Jemerson1224 Did it work for you?
