### ISSUE TITLE
Paste plain text as default

### ISSUE THREAD

**Issue by pintergreg** [asciidocfx/AsciidocFX#317]
When rich text is copied from a website for example and I want to paste it (CTRL+V or use right click paste menu) into the editor it results some meaningless characters. If I press CTRL+SHIFT+V which is normally the paste plain text, it works as expected.
As asciidoc is a plaintext format I think the latter behavior (CTRL+SHIFT+V) should be the default.

The GitHub new issue warning "Before you submit an issue, please review the guidelines for contributing to this repository." results "ÿþB" pressing CTRL+V.

I'm using Arch linux, AsciidocFX is installed from AUR, version is 1.5.5-1

**Comment by shawngiese** [comment]
That would be nice.  For now I just open a text editor and paste there first if I really need plain text.

**Comment by rahmanusta** [comment]
You can now use the new AsciidocFX version 1.5.6 

https://github.com/asciidocfx/AsciidocFX/releases
