### ISSUE TITLE
AFX 1.5.6 - hide hidden files and folders on Linux.

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#323]
Files start with a . (dot) is displayed by AsciidocFX when listing the contents of a folder. See image below.

![image](https://user-images.githubusercontent.com/13682850/31044437-b771bd88-a5cf-11e7-9c5f-b84011f958a2.png)

Requesting that these files not be displayed (should remain hidden).

**Comment by rahmanusta** [comment]
@wfouche It is an approach. I actually like to see hidden files and directories in the file view.

**Comment by manthanrtilva** [comment]
@rahmanusta To address this request, can we add additional setting where user can configure whether they want to list hidden file/folder or not?

**Comment by rahmanusta** [comment]
@manthanrtilva sure it is a good suggestion

**Comment by rahmanusta** [comment]
This feature has been added https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.6.0
