### ISSUE TITLE
ditaa diagram making asciidocFX unresponsive [mac osx high sierra]

### ISSUE THREAD

**Issue by gearboxscott** [asciidocfx/AsciidocFX#331]
I have been having to comment out ditaa diagrams in my .adoc because it's causing the program to become unresponsive.   If I leave it commented out, then comment it back in to publish on the command line it works fine:

Here is the snippet of code:

```
.{short} Lifecycle Environment
[ditaa,file="images/lifecycle.png"]
--
              +-------------+            +-------------+
              |             |            +             +
              |             |--Promote-->+ NON-PROD    +
              |             |            + Lifecycle   +
              |             |            + Environment +
              | Library     |            +             +
   --Pubish-->| Lifecycle   |            +-------------+
              | Environment |
              |             |            +-------------+
              |             |--Promote-->+             +
              |             |            + PROD        +
              +-------------+            + Lifecycle   +
                                         + Environment +
                                         +             +
                                         +-------------+

--
```

I have it commented out for now so I can get my writing done.  Here are some details about the installation and the OS:

AsciidocFX version 1.5.7 (that was fixed for High Sierra)
OS: MacOS 11.13.1
rvm: 1.29.3
java version: 9.0.1
asciidoctor-diagram: 1.5.6
asciidoctor: 1.5.6.1
ruby: 2.4.1p111

I do this compile the doc: asciidoctor-pdf -r asciidoctor-diagram  $*.adoc

That works fine, using vim to uncomment the ditaa part prior to uncommenting it.

Scott

**Comment by rahmanusta** [comment]
I tried it now with v1.5.8. Do you still face with this issue?

![image](https://user-images.githubusercontent.com/1158804/34464557-c22a7686-ee84-11e7-9e7d-2e1eb23c9fd5.png)
