### ISSUE TITLE
AsciidocFx 1.5.6 truncated my adoc file

### ISSUE THREAD

**Issue by mikes222** [asciidocfx/AsciidocFX#334]
I am working with a notebook and constantly changing wlan and drives going from one location to another. Although the adoc file is located at the local hard drive AsciidocFX somehow truncated this file to 0 bytes. I had a hard time to recover most changes :-(

Please always make sure that you do store the file to a separate filename and rename the file after successful write. 

I am always doing something like this in my projects:

        FileOutputStream fos = new FileOutputStream(filename + ".filepart");
        int done = 0;
        while (content.length - done > 0) {
            if (content.length - done > MAXBLOCKSIZE) {
                fos.write(content, done, MAXBLOCKSIZE);
                done += MAXBLOCKSIZE;
            } else {
                fos.write(content, done, content.length - done);
                done += content.length;
            }
        }
        fos.close();
        File file = new File(filename + ".filepart");
        boolean ok = new File(filename).delete(); // alternatively rename to ".backup"
        ok = file.renameTo(new File(filename));
        if (!ok) {
            throw new RuntimeException("FileSaveFailed");
        }

It may be cool if the user could specify to always create a backup copy of the previous file in the configuration

**Comment by rahmanusta** [comment]
Hi @mikes222 , sad to hear that. Can you tell me how it truncated the file?

**Comment by mikes222** [comment]
Unfortunately not. I was just puzzled today when I opened the file and AsciidocFX showed - nothing. When I checked for the reason I saw that the file had 0 byte (before I closed AsciidocFx again). Nothing special in any logfiles. 
I have no clue how this happened. I just can say that I kept the program open the whole time (several days). Maybe AsciidocFx lost the filedescriptor somehow?

**Comment by rahmanusta** [comment]
I have never lost any data with AsciidocFX. AsciidocFX doesn't touch any file descriptor.

**Comment by mikes222** [comment]
This issue never occured again here. Despite the fact that it would be nice to optionally create a backup copy of the adoc you can close this issue.
