### ISSUE TITLE
How to switch to a custom docbook-xsl configuration.

### ISSUE THREAD

**Issue by marcdexet-cnrs** [asciidocfx/AsciidocFX#336]
According to _asciidoc-fopub_, to get a customized rendering to PDF, you have to point fopub to a different docbook.xsl directory. 

How to switch to a custom docbook-xsl configuration with AsciidocFX ?

**Comment by rahmanusta** [comment]
You should edit docbook files. They are located at user home directory like .AsciidocFX-x.y.z

**Comment by marcdexet-cnrs** [comment]
I'm very sorry, but there's docbook location settings in to the .AsciidocFX-x.y.z files  (find all search over all the directories with atom) . 
The only one docbook configuration I found is into the Asciidoc's installation conf directory :/
This is the only one according to https://github.com/asciidocfx/AsciidocFX/blob/master/src/main/java/com/kodedu/service/convert/pdf/PdfBookConverter.java#L91 after configPath resolution.

**Comment by rahmanusta** [comment]
I'm sorry, it is located at INSTALL_DIR/AsciidocFX/conf
