### ISSUE TITLE
MATLAB code renders badly in HTML export

### ISSUE THREAD

**Issue by cokelid** [asciidocfx/AsciidocFX#338]
The following asciidoc renders fine in the preview browser. However when using HTML->Save, the resulting MALTAB source code is badly formatted with the first line being indented.

Using AsciidocFX 1.5.6 (.exe installer with JRE) on Windows 7.

Asciidoc source:
```
= MATLAB Test

Blah blah

[source,matlab]
----
function out = myfunc(in)
    out = 123; % This is a comment
end
----
```

Looks good in preview:
![image](https://user-images.githubusercontent.com/13600966/34415697-011c84dc-ebe8-11e7-8a08-cd3e4f6710f6.png)

Bad when exported to HTML, the first line gets an extra indent. (Note I added yellow highlighting to show different indents). Same rendering in IE 11.0 and Chrome 60.0:
![image](https://user-images.githubusercontent.com/13600966/34415841-a9c030b6-ebe8-11e7-905a-2c7ebbbdd6e7.png)

Nothing shows in the log except "HTML conversion started" and "HTML conversion ended".

**Comment by rahmanusta** [comment]
You should include highlight.js manually
