### ISSUE TITLE
Cannot add custom footer to html (neither with docinfo, or custom template)

### ISSUE THREAD

**Issue by joeyphant** [asciidocfx/AsciidocFX#340]
I can't find a way to add a custom footer to my html document using Version 1.5.8 under Windows.

What I tried so far:

- Defining a `docinfo-footer.html` and setting `:docinfo: shared` and also `:docinfo: shared-footer` (with and without setting the docinfodir)
  - this results in an Exception:
    > ERROR => {"name":"SecurityError","message":"Jail is not an absolute path: ."}
  - I tried this with an absolute and a relative path for docinfodir
- Defining a `test-docinfo-footer.html` (file is named `test.adoc`) and setting `:docinfo: private-footer` (also setting the docinfodir)
  - this just had no effect

- Defining a custom template and setting the template-dir(s)
  - custom template was tested directly with asciidoctor CLI (under windows) and worked as intended
  - added template-dir and template-dirs parameters at multiple locations (e.g. the asciidoctor_html.json, the attribute list (in the settings of asciidocFX), as attribute in the document header)
  - this also had no effect

Could someone provide a working example for me? Did I miss some necessary configuration?

If it's of any importance:
Generated html shows `<meta name="generator" content="Asciidoctor 1.5.5.dev">`

**Comment by rahmanusta** [comment]
Hi @joeyphant,
I didn't test this feature in AsciidocFX. I'm not sure whether it is supported in Asciidoctor.js

**Comment by joeyphant** [comment]
Hi @rahmanusta,
Thanks for the quick reply.
While I'm also not sure about the support for templates, docinfo should work. I just found a comment by mojavelinux:
> You almost always want to set the safe mode. When you get errors about the jail, it means you are using the default safe mode. The recommended safe mode is either safe or unsafe.

I'll give `:docinfo:` another try as soon as possible while also defining the safe-mode...

**Comment by joeyphant** [comment]
For anyone who is interested:
`:docinfo: shared-footer` does yield the above error ("Jail is not an absolute Path") when `safe-mode` is set to `safe` or `server`. If `safe-mode` is set to `secure` it will not result in an error but will also not include the custom footer (or content of the `docinfo-footer.html`). If `safe-mode` is set to `unsafe`, then it will work as intended (e.g. use the `docinfodir` and the `docinfo file`).

Thanks again @rahmanusta, I will close this issue.

**Comment by rahmanusta** [comment]
Thanks @joeyphant
