### ISSUE TITLE
Installer detected as malware, false positive?

### ISSUE THREAD

**Issue by jmiserez** [asciidocfx/AsciidocFX#347]
The Windows installer is detected by as ransomware/malware during install. Usually I'd just assume it to be a false positive, but the reason given is strange: The install/uninstall writes encrypted data to a file "TmEncryptTemp.000". I got the installer from https://github.com/asciidocfx/AsciidocFX/releases/download/v1.5.9/AsciidocFX_Windows.exe (via https://www.asciidocfx.com, effectively downloaded file was served from https://github-production-release-asset-2e65be.s3.amazonaws.com)

What is the role of the file TmEncryptTemp.000 during the installation process?

EDIT: Other Install4J-based installers (SoapUI) don't write such a file.

**Comment by rahmanusta** [comment]
Hi @jmiserez, the installer is generated by install4j but I didn't get the message before as you said. Which software analyzer gives this message? What is inside of this data? @ingokegel do you have any information about it?

**Comment by ingokegel** [comment]
The installer would not write to a file `TmEncryptTemp.000` unless you have such file names in your distribution tree.

**Comment by jmiserez** [comment]
This was detected on Windows 7 by TrendMicro, which has some sort of anti-ransomware heuristic. It triggered both during the install and the uninstall and killed the program. The TmEncryptTemp.000 was actually there in the AsciidocFX install directory (C:\Program Files\AsciidocFX\). I opened it in Notepad++ and it seemed to contain only random binary data.

I’ll try to run the installer in a safe Windows VM to see what happens and report back.

**Comment by jmiserez** [comment]
After some more googling, I think it's probably a false positive. TrendMicro (the virus scanner) encrypts all files it quarantines, and it names them TmEncryptTemp (Tm as in TrendMicro?). I don't know what sets TrendMicros "anti-ransomware heuristic" off, but it may just be the unzipping/unpacking during install.

If it installs clean on your machines, I think we can close this issue.
