### ISSUE TITLE
Add a Changelog to releases

### ISSUE THREAD

**Issue by lefou** [asciidocfx/AsciidocFX#35]
Would really be great! For every piece of software, actually.

**Comment by lefou** [comment]
Any decission since then? Lots up releases lately but no hints what changed (beside the git).

**Comment by ozlerhakan** [comment]
Hi @lefou ,

Thanks for the reminder us of that, we will strictly apply the changelog approach as of the next release. (perhaps, we may mention the preceding changes as well)

**Comment by lefou** [comment]
Great! Much appreciated.

**Comment by lefou** [comment]
Since v1.3.2, you can find the changelog here: https://github.com/asciidocfx/AsciidocFX/blob/master/CHANGELOG.asc
