### ISSUE TITLE
Detaching realtime preview to a separate window

### ISSUE THREAD

**Issue by unfa** [asciidocfx/AsciidocFX#355]
I work with a dual-monitor setup.
I'd love to be able to detach the realtime preview to a separate window so I can put it on a separate display.
Is it possible now?

**Comment by rahmanusta** [comment]
I would like bring this feature but I'm currently cant spare time to do that.

**Comment by manthanrtilva** [comment]
@rahmanusta I would like to work on this feature. Can you share what is in your mind? otherwise I can propose as per my understanding.

**Comment by rahmanusta** [comment]
Hi @manthanrtilva, you can add right click context-menu item 'Detach Preview', and the detached preview closed it can reattach it back.

**Comment by manthanrtilva** [comment]
@rahmanusta From which branch I take code?
Should I create separate branch or work on same branch?

**Comment by rahmanusta** [comment]
You can create a branch from master. So, feature branch model.

**Comment by manthanrtilva** [comment]
@rahmanusta I made necessary changes. How can I push code?

**Comment by rahmanusta** [comment]
That's great! First fork the repository, apply your changes and push your changes to your forked repository. After, on the forked repository click 'Pull request' button, it will send your changes to me to review/approve/merge. This is the general contribution approach in github. More details: https://help.github.com/articles/creating-a-pull-request/

However, im okay also if you send your changes as a VCS patch.

**Comment by rahmanusta** [comment]
This feature has been added https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.6.0
