### ISSUE TITLE
AsciidocFX not displaying window on Windows 10

### ISSUE THREAD

**Issue by ellipticview** [asciidocfx/AsciidocFX#361]
Version 1.5.9

Start Asciidocfx, the program starts, the icon is visible in the taskbar and the program is visible in the Task Manager. However, a window does not open. I can select the program using Alt-Tab, try to maximize the window using Win ^, but still no window visible.

The log file in directory C:\Users\USERNAME\.AsciidocFX-1.5.9 is empty.
Tried uninstall and new install. Does not fix it.

**Comment by rahmanusta** [comment]
Do you use jre included version?

**Comment by ellipticview** [comment]
No, without JRE. My version of Java is:
JAVA_HOME=C:\Program Files\Java\jre1.8.0_161

**Comment by rahmanusta** [comment]
Can you please try with jre bundled version, so we can be sure whether it is about used jre or not.

**Comment by ellipticview** [comment]
Uninstalled first.
Downloaded https://github.com/asciidocfx/AsciidocFX/releases/download/v1.5.9/AsciidocFX_Windows.exe
Installed it.
Same behavior.

**Comment by rahmanusta** [comment]
Can you try to run AsciidocFx without installer ?

https://github.com/asciidocfx/AsciidocFX/releases/download/v1.5.9/asciidocfx-1.5.9.zip

What do you see in console output?

**Comment by ellipticview** [comment]
#                 #   #      #                #####  #   #
  # #    ####   ###          ####   ###    ###   #       # #
 #   #  ###    #     #   #  #   #  #   #  #      ####     #
 #####    ###  #     #   #  #   #  #   #  #      #       # #
 #   #  ####    ###  #   #   ####   ###    ###   #      #   #
 ============================================================
 :: Asciidoc FX ::     (v1.5.9)

 Website: http://asciidocfx.com

[Fatal Error] autoidx-kimber.xsl:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] autoidx-kosek.xsl:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] common.xsl:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] entities.ent:16:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] l10n.dtd:1:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] l10n.xml:2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[Fatal Error] targetdatabase.dtd:4:3: The markup in the document preceding the root element must be well-formed.
9800 [JavaFX Application Thread] INFO  c.k.service.ui.FileBrowseService - File browser relisted for C:\Users\USERNAME

**Comment by rahmanusta** [comment]
It is strange, no error in logs (don't count docbook errors)

**Comment by ellipticview** [comment]
Downloaded 1.6.1 with JRE
Installed (imported config from a previous version)
Started from Start menu => Success! AsciiDocFX opens.
I put a few characters in the new document, clicked on preview to see the preview. All looking OK!!
I then exited AsciidocFX without saving.
Invoked AsciidocFX again from the start menu => No window displays.

Deleted the ".AsciidocFX-1.6.1" directory.
Started AsciidocFX again => Now it starts. And keeps working.

Conclusion: there was something in the  ".AsciidocFX-1.6.1" directory that prevented the application from starting. Perhaps a reference to a directory or file that no longer exists?

**Comment by ellipticview** [comment]
More investigation shows that this issue is in file editor_config.json
In particular, these 4 lines: 
```
    "screenX": -32000.0,
    "screenY": -32000.0,
    "screenWidth": 160.0,
    "screenHeight": 28.0,
```
In the 1.6.1 clean install, these values are all zero (0.0). Note that if I change only the screenX and screenY to 0.0, and then invoke the application, it sets the values back to -32000.0

**Comment by rahmanusta** [comment]
Ops. How many screens do you use?

**Comment by ellipticview** [comment]
Two monitors usually: laptop internal screen and an external monitor. Sometimes I disconnect the external monitor and use one screen. The results above were with 2 screens.

**Comment by rahmanusta** [comment]
I don't know the reason why it sets to -32000, but this commit https://github.com/asciidocfx/AsciidocFX/commit/7912cbcaa9e9423add1f0a08efa4b480ed50956b will be kept main stage visible if it is not visible in any screen.

**Comment by rahmanusta** [comment]
I guess from the v1.6.3, we will not have this kind of visibility issue. Can you please check it?

**Comment by ellipticview** [comment]
Confirmed.
