### ISSUE TITLE
[Feature Request] Provide a Flatpak as software package — for Linux systems

### ISSUE THREAD

**Issue by x80486** [asciidocfx/AsciidocFX#364]
[Flatpak](http://docs.flatpak.org/en/latest/introduction.html) is a technology for building, distributing, installing and running applications – primarily targeted at the Linux desktop and desktop applications.

**Comment by rahmanusta** [comment]
If you have experience can you package asciidocfx as flatpak? Im open for contribution

**Comment by rico-chet** [comment]
I've issues running AsciidocFX on a newly upgraded Debian and I don't feel like debugging Java launchers, so I created a [prototypic flatpak manifest](https://github.com/rico-chet/flathub/blob/AsciidocFX/com.asciidocfx.AsciidocFX.yaml). Feel free to bring it on as per 
[flatpak submission docs](https://github.com/flathub/flathub/wiki/App-Submission).
 I am not the owner, so I'm not entitled to do so myself.
