### ISSUE TITLE
Bir {app-name} içerisinde 2 farklı element tanımlanması

### ISSUE THREAD

**Issue by safaktaskin** [asciidocfx/AsciidocFX#365]
Merhaba,

 Elimde birden çok Asciidoc ile oluşturulmuş doküman mevcut. Bir application name(app-name) içerisine 2 farklı element tanımlanmasını istiyorum.

Örneğin: 
:app-name: pass:q [Örnek1, Örnek2]

 Sitemde Örnek1 uzantısına giriş yapıldığında doküman içerisinde {app-name} yazan her yerin "Örnek1" olarak görünmesini ve yine sitemde "Örnek2" uzantısına tıklandığında tüm dokümanda bulunan {app-name} alanının Örnek2 olması mümkün müdür? 
 Aynı doküman içerisinde farklı app-name tanımlamamın başka bir yolu var mı?

![ascii](https://user-images.githubusercontent.com/32701951/42515428-6ae50be0-8464-11e8-8594-ef1c271c3114.png)

Bu konuda bana yardımcı olabilirseniz çok sevinirim.
Saygılarımla...

**Comment by safaktaskin** [comment]
Rahman Bey aslında tam olarak demek istediğim konu bu değil. 2 tane uygulamam da bir çok adoc uzantılı dokümanım mevcut. Örneğin Çevre konusu ile ilgili bir dokümanım var. Bu hazırlamış olduğum cevre.adoc her iki uygulamamda da ortak ve tek bir klasörde kullanılmaya devam edecek. Ancak her bir adoc dokümanının en üstünde yer alan {app-name} parametresinin parametrik hale getirmek istiyoruz. Yani kullanıcı "Örnek1" uygulamasını kullanırken bu dokümanı açmış ise {app-name} olarak Örnek1 atansın istiyoruz. Bu işlemi de parametre geçirerek yapmak istemiyoruz. Nasıl her 2 uygulamanın da env-shared dokümanı var ise ve oradan bazı parametreleri okuyorsa adoc larda bunu yapsın istiyoruz. 

Yani belirleyeceğimiz bir adresteki veya klasördeki dosyayı okuyarak veya klasör/Dosya ismini okuyarak bir karar versin istiyoruz. Bu okuduğu değişkene göre {app-name} olarak "Örnek1" mi yoksa "Örnek2" mi göstereceğine karar vermeli.

**Comment by rahmanusta** [comment]
Cevre. adoc
```
Cevre {app-name}
```

Ornek1. adoc
```
:app-name: Ornek1

Ornek 1

include::Cevre.adoc[]
```

Ornek2. adoc
```
:app-name: Ornek1

Ornek 2

include::Cevre.adoc[]
```

**Comment by safaktaskin** [comment]
İlginiz ve yardımlarınız için gerçekten çok teşekkür ederim =) 

İyi çalışmalar dilerim...
