### ISSUE TITLE
How can I change the font of  'Preview Setting'  

### ISSUE THREAD

**Issue by DrTF** [asciidocfx/AsciidocFX#367]
- Win 10 ，has installed font "Microsoft JhengHei UI".
- But I do like this, it doesn't change..
 - 
![image](https://user-images.githubusercontent.com/11496772/43301163-0798de9c-9196-11e8-8ffb-4fee9178d649.png)

 - 
![image](https://user-images.githubusercontent.com/11496772/43301094-8f6f46cc-9195-11e8-9396-604a9ed0e410.png)

- "font" doesn't change, and "font-size" isn't 20.

**Comment by rahmanusta** [comment]
Settings -> Location Settings -> There are two stylesheet files. Edit Style Sheet or Style Sheet overrides files according to your needs. Overrides file is only used in preview.

**Comment by rahmanusta** [comment]
I'm closing this issue, please let me know if it is not working.

**Comment by DrTF** [comment]
Ah, it had work well.  sorry...
