### ISSUE TITLE
mailing list archives

### ISSUE THREAD

**Issue by nancym** [asciidocfx/AsciidocFX#368]
I'm getting started with AsciidocFX and I'd like to read the [mailing list](https://asciidocfx.com/#truesupport) archives, and possibly join the mailing list, but I do not have a Gmail account and I do not want to give Google my birthday and phone number, which they now require to create an account. Are the mailing list archives available anywhere on the web? Is it possible to join the mailing list without a Gmail account?

Thank you.

**Comment by rahmanusta** [comment]
You can access it publicly here https://groups.google.com/d/forum/asciidocfx-discuss . Also, you can read discussions on gitter.
