### ISSUE TITLE
Cmd-S (save) keyboard command does not work (on Mac OS)

### ISSUE THREAD

**Issue by gernotstarke** [asciidocfx/AsciidocFX#37]
on Mac OS, the standard keyboard shortcut to save files is Cmd-s.

Too bad AsciidocFX does not handle that - so I am forced to use the mouse to save a modified file.

**Comment by rahmanusta** [comment]
Hi Dr.

I've updated the accelarators to work with Ctrl in Windows and Cmd in Mac. Can you try Cmd-s with latest v1.2.9 build?

**Comment by gernotstarke** [comment]
closed with version 1.2.9, 20mins after filing the bug... that's what I call top-level-support...

awesome, thanx.
(btw - I'm currently writing some asciidoctor stuff - please expect some more issue-reports...)
