### ISSUE TITLE
How to lower memory usage?

### ISSUE THREAD

**Issue by shawngiese** [asciidocfx/AsciidocFX#370]
AsciidocFX seems to use a lot of RAM. When I first open it my Windows Task Manager says it is taking about 650MB. Then I open an AsciiDoc file (about 25 page PDF length) and it goes to 760MB. If I close that file the memory goes up again to 780MB. I'm worried how it will do with larger documents. 

Picked up _JAVA_OPTIONS: -Xmx512M
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

Windows 10

AsciidocFX 1.6.2

**Comment by rahmanusta** [comment]
It is JVM. If max heap size is 512 MB, total memory may goes up 780 MB. What is your expectation?

**Comment by shawngiese** [comment]
I just feel it is a lot of memory to use for editing my text files
(especially a single file) and may be why it takes a little bit to start up
or the occasional (few) crash... I mean the same file opened in Brackets
with preview is only 210MB. The same file in Sublime with 10 other files
open  is only 70MB. I previously would use Sublime scripts to run the
AsciiDoc through my own FOP/HTML/ transformations but I love the extensions
you have added.

**Comment by rahmanusta** [comment]
Unfortunately we can't have this lower mem size on JVM.

**Comment by rahmanusta** [comment]
However, if we can switch to GraalVM, we can have some benefits on mem size and bootstrap time. Let's chase it.
