### ISSUE TITLE
Ditaa options do not work

### ISSUE THREAD

**Issue by coschtl** [asciidocfx/AsciidocFX#371]
Hi,
I tried to use the dita-options, but it seems that they are ignored (version 1.6.3). The following lines should render a pink rectangle directly inside a blue one (see:) but they get separated:

[ditaa, options='no-separation']
--
+---------+
| cBLU    |
|         |
|    +----+
|    |cPNK|
|    |    |
+----+----+
--

**Comment by coschtl** [comment]
Sorry, I forgot to add the pre-Tags:

<pre>
[ditaa, options='no-separation']
--
+---------+
| cBLU    |
|         |
|    +----+
|    |cPNK|
|    |    |
+----+----+
--
</pre>

**Comment by rahmanusta** [comment]
Thanks for reporting. Let me check it

**Comment by rahmanusta** [comment]
Where `[ditaa, options='no-separation']` is supported? I didn't see it asciidoctor-diagram.

**Comment by coschtl** [comment]
Seems to be an outdated version of setting the options. But also the new syntax described at https://github.com/asciidoctor/asciidoctor-diagram/issues/69#issuecomment-89584825 doesn't seem to work in ascidocfx.
Shouldn't this work here also?

**Comment by rahmanusta** [comment]
This can be implemented. I just were not aware of it.

**Comment by rahmanusta** [comment]
Feature has been implemented. Please check the latest version.

**Comment by rahmanusta** [comment]
![image](https://user-images.githubusercontent.com/1158804/43903224-9f88eb3a-9bf4-11e8-963e-4fe28a252b4a.png)

**Comment by coschtl** [comment]
Works like a charm!
Thans for implementing that so fast.

**Comment by rahmanusta** [comment]
You are welcome. Thanks for reporting ;)
