### ISSUE TITLE
PlantUML Diagrams are not generated anymore with update to 1.6.5

### ISSUE THREAD

**Issue by ali-gs** [asciidocfx/AsciidocFX#372]
PlantUML Diagrams are not generated anymore with update to 1.6.5 earlier in 1.6.0 it was working fine. I get the below warning.

WARN => File not found or is not exist C:\Program Files\AsciidocFX\conf\public\xxxx\yyy\output\images\blockdiagram1.png

I am using windows 10.

**Comment by rahmanusta** [comment]
Can you please share an example doc to test?

**Comment by rahmanusta** [comment]
There was a defect in 1.6.5, you can try 16.6. However, both 1.6.0 and upper doesn't accept the following, so remove this part.

```
state "INIT" as INIT <>
state "Ready" as Ready <>
```

**Comment by ali-gs** [comment]
Thanks its working now.
