### ISSUE TITLE
symbol font width handling

### ISSUE THREAD

**Issue by masashinogawa** [asciidocfx/AsciidocFX#376]
Please help on unicode symbol font handling on v1.6.7.

#1 Starting from v1.6.3 or v1.6.4, the new (looking) editor can't handle symbol font width correctly.
  In this screenshot, I selected (by mouse) the multiplication sign but the editor can't recognize it's double-width font.  The saved file is confirmed that it's UTF8 encoding.

![utf8 symbol test](https://user-images.githubusercontent.com/37952014/44541624-2b05aa00-a6d0-11e8-9244-ea81f5baaecf.JPG)

#2 When I open my documents written by v1.5.9 with unicode symbol fonts, some fonts are not recognized correctly.  Just like above #1, the editor seems like treat it as ascii (single width) code.  This problem is also starting from v1.6.3 or v1.6.4.  In this screenshot, I have an unicode multiplication sign "32 x 32" (I edit this screenshot to mask privacy contents).

![ws000029](https://user-images.githubusercontent.com/37952014/44542195-b92e6000-a6d1-11e8-8453-23eb6b441b6b.JPG)

**Comment by rahmanusta** [comment]
Can you share a document sample? Does it happen in new created files in v1.6.7?

**Comment by masashinogawa** [comment]
I'm using windows version of v1.6.7 with JRE, freshly downloaded, on windows 10 Pro with latest windows updates.

Here's my simple code.
[167.txt](https://github.com/asciidocfx/AsciidocFX/files/2316057/167.txt)

While making this file, I notice that following procedure makes another symptom on my windows 10.
a) open this 167.txt file by other editors (I checked VIM, notepad).
b) copy & paste the 167.txt contents into new file on v1.6.7 editor.
c) we see the font changed.
Here, I confirmed several windows applications can receive correct text from the clipboard at step b). 
It seems like only Asciidocfx alters the unicode symbol font.

Please help!

**Comment by rahmanusta** [comment]
I tried but I'm not able to reproduce the issue on my local env.

**Comment by rahmanusta** [comment]
Can you try the latest version? It should handle this symbols well.

**Comment by rahmanusta** [comment]
Great! Thanks for reporting.
