### ISSUE TITLE
Strange sort-order in file-tree...

### ISSUE THREAD

**Issue by gernotstarke** [asciidocfx/AsciidocFX#38]
first the UPPERCASE files, alpha-sorted...
then the lowercase files, alpha-sorted...

no real problem, but strange :-)

**Comment by rahmanusta** [comment]
Hmm :) Which behaviour do you want Dr. :) ?

**Comment by gernotstarke** [comment]
strictly alpha, regardless of upper- or lowercase, as depicted in the screenshot...
(which I took on my Mac)
![_users_gstarke](https://cloud.githubusercontent.com/assets/1233990/5613427/5ea44850-94e4-11e4-87ed-35593418d865.jpg)

thanx!

**Comment by lefou** [comment]
I guess, the "expected" behaviour depends on the platform you are using. Under Linux, it is very common to have all uppercases sorted before the lowercase letters.

**Comment by lefou** [comment]
To move this forward here is a (maybe controversial) suggestion. Always sort alphanumerically, but case-sensitive (all uppercases before lowercases) for Linux/Unix and case-insensitive for all other platforms (Mac, Windows). Or are there Linux desktops around sorting case-insensitive?

**Comment by rahmanusta** [comment]
Implementation is easy, but, we need to aggrement on that issue :) @lefou your suggestion is OK for me, Mr. @gernotstarke  what do you think?

**Comment by gernotstarke** [comment]
Imho sort order needs to be platform-specific - to avoid surprises to users. 

Writing from a Mac I'd like case-insensitive sort-order - and support @lefou suggestion for Linux/Unix.

**Comment by ozlerhakan** [comment]
I am also OK with that, the enchancement label will be suitable now :)

**Comment by rahmanusta** [comment]
Should we sort files with grouped order?

For example;

Firstly, Order Asciidoc files group,
Secondly, PDF,
3. HTML ,
4. Epub,
5. Mobi,
6 ...

Or should we sort without gruoped?

@lefou @ozlerhakan @gernotstarke

**Comment by gernotstarke** [comment]
alpha sorting, others would imho violate the "no-surprises" principle

Rahman Usta schrieb:

**Comment by ozlerhakan** [comment]
I have checked all my directories including adoc files so, by default, in windows, one of my directories has this order already: all ( .asc), (...txt), (...pdf), (...html), (...epub), (...mobi) and (... xml) files. I liked this way if you trace files by looking their extensions but we can test this suggestion also, np.

**Comment by lefou** [comment]
I'm with @gernotstarke here, no surprises, thus I'm for plain alphanumeric sorting. 

Of course, you could add the sorting by extension as separate feature which must be enabled/selected explicit, e.g. via context menu. But I don't see the need. Having nice icons by filetype would be nice though.

**Comment by rahmanusta** [comment]
Do you think it is OK @lefou @gernotstarke

**Comment by gernotstarke** [comment]
+1, thx
