### ISSUE TITLE
Outline out of order and missing sections

### ISSUE THREAD

**Issue by brownts** [asciidocfx/AsciidocFX#382]
I'm new to AsciidocFX, but from what I can tell, the outline appears to be misbehaving when I include files from a top level document.

I've created an example where the top level document includes two chapter documents, each with 3 sections of their own.  For some reason, sections of chapter 2 appear to be missing, and the 1 section that is present, is out of order (i.e., the one visible section from chapter 2 appears before the same section in chapter 1).  As can be seen from the preview (see screen capture attachment), this renders properly, but the outline doesn't seem to accurately reflect the document structure.

It seems that the section from chapter 2 that does appear in the outline is dependent upon whether there is any text in the parent section or not (i.e., there is currently no text before the child section).  Adding text to this parent section, makes the child section disappear from the outline as well, leaving only the sections from chapter 1 in the outline.

I've tried this on **Linux 1.6.6** and **Windows 1.6.8** versions (both versions using the included JRE) and both exhibit this behavior.

Note that for each individual chapter file, the outline appears correct, it's only when viewing the outline from the top-level document that it appears incorrect.

As more of an investigation into this, I've also tried in-lining chapter 1 into the top-level document and leaving chapter 2 as an include.  When I do this, the outline will then show all sections of both chapters, but chapter 2 (and it's sections) are shown in the outline before chapter 1 (and it's sections).

[test.zip](https://github.com/asciidocfx/AsciidocFX/files/2384225/test.zip)

![asciidocfx_screenshot](https://user-images.githubusercontent.com/17529295/45564529-bc26f700-b81e-11e8-8b51-9e7be9be34f3.png)

**Comment by rahmanusta** [comment]
I fixed this issue here https://github.com/asciidocfx/AsciidocFX/commit/922181011f27259fe460af4f25aa90770754ac8f . It will be available in next release. However, when you click outline item, it will not able to position line in any included file.

**Comment by rahmanusta** [comment]
I'm closing this issue, please let me know if it is not working.
