### ISSUE TITLE
Update 1.6.8 --> 1.6.9 dosen't work

### ISSUE THREAD

**Issue by CodingVampyre** [asciidocfx/AsciidocFX#386]
When I try to update it with the automatic updater, the update runs smoothly. But afterwards, not only the version is still 1.6.8 but the updater starts yet again, promting me to update to 1.6.9. @

**Comment by rahmanusta** [comment]
Sorry for this experience @NachtmahrEDM, I'll check it. My preliminary suggestion for you is to download 1.6.9 directly from this link https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.6.9

**Comment by rahmanusta** [comment]
I couldn't reproduce the issue. You can uninstall and install v1.6.9 manually.

**Comment by rahmanusta** [comment]
Can you please try v1.7.0 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.0 ?

**Comment by rahmanusta** [comment]
Hi, could you please reinstall https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.4 and check?
