### ISSUE TITLE
create "real" MacOS Application

### ISSUE THREAD

**Issue by gernotstarke** [asciidocfx/AsciidocFX#39]
Currently I have to start AsciidocFX from the command line...
fine for me, but if you want to increase your userbase, a "real" app
would be nicer, imho.

You could use the following maven plugin:
http://mojo.codehaus.org/osxappbundle-maven-plugin/

Or have a look at the Griffon-framework, they can create multiple different
target formats (windows, mac, linux) via Gradle plugins... 

(thx and sorry, currently I'm too busy to contribute on my own )

**Comment by rahmanusta** [comment]
Thanks Dr. I was thinking it. I tried install4j to produce multiplatform installer. Its goog working. It is free for open-source projects. Now, im waiting licence keys, after i will integrate it to asciidocfx project.

**Comment by rahmanusta** [comment]
Can you try it Dr. ?

**Comment by gernotstarke** [comment]
only if you skip the Dr. and begin calling me Gernot :-)

yes - will try, maybe not today...

**Comment by rahmanusta** [comment]
Hehe :) Ok Gernot, thanks.

**Comment by gernotstarke** [comment]
"mvn clean install" after checking out upstream-commit 5e905c8...:

does NOT build any dmg or app... or am I missing the right maven goal?

**Comment by rahmanusta** [comment]
For built we are using Travis CI, you can see the build flow  [travis.yml](https://github.com/asciidocfx/AsciidocFX/blob/master/.travis.yml) in project. Build produced from install4j, if you want to build native installers on your local, you need to install it.

After run the ```mvn clean install -Pinstall-runtime``` . Before run it, you need to provide install4j home to ```install4j.home``` in pom.xml.

**Comment by rahmanusta** [comment]
You can download the release from https://github.com/asciidocfx/AsciidocFX/releases

**Comment by gernotstarke** [comment]
whow - awesome (apart from now becoming 200MB "fat"... which really doesn't matter these days)

the installer works like a charm - and creates an app with a logo (that was missing in 1.2.9...)
THANX!

![_applications](https://cloud.githubusercontent.com/assets/1233990/5630843/b30f2332-95c1-11e4-98ec-9dd6a0a599db.jpg)
![_volumes_asciidocfx](https://cloud.githubusercontent.com/assets/1233990/5630846/baab6f74-95c1-11e4-8eff-385557d49cb0.jpg)

**Comment by rahmanusta** [comment]
Thanks Gernot :)

**Comment by rahmanusta** [comment]
If you have java 8 already installed. You can remove the jre lib in installed app. i will decrease size. FYI.
