### ISSUE TITLE
Upgrading to v1.5.9 of Asciidoctor.js 

### ISSUE THREAD

**Issue by wfouche** [asciidocfx/AsciidocFX#398]
Would be great to get a new release of AsciidocFX for the upcoming holiday season with support for Asciidoctor.js  **v1.5.9**  -  https://github.com/asciidoctor/asciidoctor.js/commit/eb5d9e45e2a039c760cbaf6b3c53035c45014931

**Comment by rahmanusta** [comment]
Can you please try v1.7.0 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.0 ?

**Comment by wfouche** [comment]
Closed.
