### ISSUE TITLE
No zip file built now to have an installable system

### ISSUE THREAD

**Issue by russel** [asciidocfx/AsciidocFX#40]
WIth the change from 1.2 to 1.3, the zip that was the installable system is no longer created. The README however doesn't give an altered installation procedure. Is there a new install process?

**Comment by rahmanusta** [comment]
Hi russel. We are working on build native installers for operating systems. .zip distribution will be released also. 1.3 is not released yet.

**Comment by russel** [comment]
So what is the official way of using master/head as an alpha tester?

**Comment by rahmanusta** [comment]
We've released 1.3.0 build with native support for OSes. Integration to install4j seems like completed. I will update the .

**Comment by rahmanusta** [comment]
Hi @russel , Can i close this issue ? Have you any question?

**Comment by russel** [comment]
I just do "mvn clean package appassembler:assemble" and run from target/appassembler. Maybe I should just switch to downloading and installing the release.

**Comment by rahmanusta** [comment]
You can use mvn clean install to build project in old way. In new style, we integrated Asciidocfx with install4j plugin. It builds AsciidocFX for platforms seperately. Both of ways OK. In new style, there is autoupdate feature also and JRE comes with out-of-box.
