### ISSUE TITLE
Cannot change font size for Main UI (hidpi display) on linux

### ISSUE THREAD

**Issue by mxrenkin** [asciidocfx/AsciidocFX#401]
I am using a Notebook with hi-dpi display (2560x1440), OS: Kubuntu 18.04 and 18.10. The Main UI is rather inconvenient to use because of very small font size of tab titles, tool tips etc. I don't see a way to change that - only Editor, Terminal, etc. can be set.
Is there a way to change that by editing a CSS file or such like?
Many thanks in advance!

**Comment by rahmanusta** [comment]
Hi,

Edit this file in AsciidocFX's installation directory.

- AsciidocFX/conf/themes/Shared.css 

```
.root {
    -fx-font-size: 1.5em;
}
```
-  Remove *.bss files in AsciidocFX/conf/themes/dark and AsciidocFX/conf/themes/default, or compile css files with scrict in bat file shared in same directory

**Comment by mxrenkin** [comment]
Hi,
a big THANKS for fast and working suggestion! The bat file is working as valid linux script too.
