### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by ellipticview** [asciidocfx/AsciidocFX#410]
Version 1.6.9

On startup AsciiDocFX displays the following in the log:
DEBUG => C:\Program Files\AsciidocFX\conf\public\css (Access is denied)

As a result, the preview window has no styling.
From Windows Explorer and the command prompt I can access this directory (and the files in it) without any problem.

What I have tried in order to resolve this issue (with no result)

- Reinstall with embedded JRE
- Run AsciiDocFX as administrator

A possible clue to the cause of the problem: when installing I get the message:
Windows Defender Smartscreen prevented an unrecognized app from starting.

**Comment by ellipticview** [comment]
To reproduce:

1. Open "C:\Users\USERNAME\.AsciidocFX-1.6.9\location_config.json"
2. Change the following line (e.g. add a character so it is a non-existant path):
"stylesheetDefault": "C:\\Users\\USERNAME\\.AsciidocFX-1.6.9\\css\\asciidoctor-default.css",
3. Restart AsciidocFX.

In my case the line read:
"stylesheetDefault": "C:\\Users\\USERNAME\\.AsciidocFX-1.6.8\\css\\asciidoctor-default.css",

This line was created as part of the upgrade to 1.6.9 and I (manually) removed the 1.6.8 folder as part of my cleanup.

It is still peculiar (and misleading) that the error message refers to a completely different folder.

**Comment by rahmanusta** [comment]
Can you please try v1.7.0 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.0 ?

**Comment by ellipticview** [comment]
Confirmed that 1.7.0 fixes this issue.
