### ISSUE TITLE
Cannot download version 1.7.0

### ISSUE THREAD

**Issue by stenzengel** [asciidocfx/AsciidocFX#420]
As indicated in CHANGELOG.asc, there is a new version 1.7.0 of AsciidocFX available, but
- the URL in README.adoc returns HTTP Code 404 for "https://github.com/asciidocfx/AsciidocFX/releases/download/v1.7.0/AsciidocFX_Windows.exe"
- and the URL in "https://asciidocfx.com" downloads version 1.6.6

The update checker in AsciidocFX itself suggests to download version 1.6.9

**Comment by rahmanusta** [comment]
Hey, stay tuned :) not released yet, but in progress :)

**Comment by rahmanusta** [comment]
Can you please try v1.7.0 https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.0 ?
