### ISSUE TITLE
No automatic Doctype detection for "*.ad" files in 1.7.0

### ISSUE THREAD

**Issue by stenzengel** [asciidocfx/AsciidocFX#421]
After upgrading to version 1.7.0, the doctype detection does not seem to work anymore for existing *.ad files.

What I did:
- Upgrade AsciidocFX from version 1.6.9 to 1.7.0
- Open existing *.ad file in AsciidocFX

What happend:
- No syntax highlighting in editor pane and no preview

What I expected:
- Without manually changing the doctyp in the menu, syntax highlighting and preview work

Notes:
- When manually changing the Doctype to AsciiDoc, syntax highlighting and preview work fine.
- Opening files with extension "adoc" work fine, too.
- When downgrading to version 1.6.9, syntax highlighting and preview work fine for "*.ad" files again.

**Comment by rahmanusta** [comment]
The issue has been fixed. Please download and reinstall v1.7.0

**Comment by stenzengel** [comment]
Verified that the issue has been fixed
