### ISSUE TITLE
Asciimath stopped working in 1.7.0, it works in 1.6.9

### ISSUE THREAD

**Issue by josemariasola** [asciidocfx/AsciidocFX#426]
Just try

[asciimath]
--
a+1
--

The HTML output is \$1a+1\$2, and the PDF generation cancels.

I had to downgrade to 1.6.9.

I've seen a couple of changes related to asciimath in commit

https://github.com/asciidocfx/AsciidocFX/commit/c33afc626f98c805d0cb205ec32b40e631418a36#diff-f2c6a08f7228ecaf1bd623ea24229fde

Check:
- conf/public/js/asciidoctor-block-macro-extensions.js
- conf/public/js/asciidoctor-extension-helpers.js.

AsciidocFX is a great product, thanks for your work!

**Comment by rahmanusta** [comment]
@josemariasola , Hi thanks for reporting :) I'll look it probably next week

**Comment by cch123** [comment]
code highlighting also stops working in 1.7.0

**Comment by rahmanusta** [comment]
Hey, try https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.1

**Comment by josemariasola** [comment]
Hey @rahmanusta 
I tried it and asciimath worked like a charm.
Thanks!
