### ISSUE TITLE
"set" does not work for "include"

### ISSUE THREAD

**Issue by seto-hideki** [asciidocfx/AsciidocFX#427]
I use AsciidocFX 1.7.0
"set" does not work for "include". The code as below.

{set:TESTID:0001}
include:../test_{TESTID}.adoc[]

And the following code works.

:TESTID: 0001
include:../test_{TESTID}.adoc[]

I set a variable in "table" format , so I want to use "set",

**Comment by rahmanusta** [comment]
Hi,

can you use it like that?

```
:TESTID: 0001

include::../test_{TESTID}.adoc[]

And the following code works..

:TESTID: 0002
include::../test_{TESTID}.adoc[]
```

**Comment by seto-hideki** [comment]
Yes. I am sorry for my wrong codes.
