### ISSUE TITLE
"set" does not work for "ifeval", "ifdef".

### ISSUE THREAD

**Issue by seto-hideki** [asciidocfx/AsciidocFX#428]
I use AsciidocFX 1.7.0
"set" does not work for "ifeval", "ifdef". The code as below.

{set:test_id:0001}

ifeval::[{test_id} == 0001]
	testtest
endif::[]

ifdef::test_id[]
	testtestd
endif::[]

And the following code works.

test_id: 0001

ifeval::[{test_id} == 0001]
	testtest
endif::[]

ifdef::test_id[]
	testtestd
endif::[]

I set a variable in "table" format , so I want to use "set",

**Comment by rahmanusta** [comment]
Hi, can you use it like below?

```
:test_id: 0001

ifeval::[{test_id} == 0001]
testtest
endif::[]

ifdef::test_id[]
testtestd
endif::[]

And the following code works.

test_id: 0001

ifeval::[{test_id} == 0001]
testtest
endif::[]

ifdef::test_id[]
testtestd
endif::[]
```

**Comment by seto-hideki** [comment]
Yes. I am sorry to mistake cut / copy.
