### ISSUE TITLE
Add tooltips to toolbar buttons

### ISSUE THREAD

**Issue by lefou** [asciidocfx/AsciidocFX#43]
Currently, the buttons in the toolbar of the editor windows have no tooltips. This makes it rather hard to guess what to expect from a click. At least not all icons are self-explanatory.

**Comment by rahmanusta** [comment]
Thats true @lefou, im working on some ui experiments. Also, i need to say that, JavaFX's tooltip component is little problematic. It has been showing lately, and showing time is not configurable by now. However, we need to put tooltip to buttons.

**Comment by rahmanusta** [comment]
Do you think it is OK @lefou Tobias?

**Comment by lefou** [comment]
Latest release (v1.3.2) has tooltip, great. Thanks!
