### ISSUE TITLE
Code syntax highlighting not working in version 1.7.0

### ISSUE THREAD

**Issue by 3rady** [asciidocfx/AsciidocFX#430]
Syntax highlighting of code blocks does not seem to be working in version 1.7.0.  For example:

```
== This is a test

Here is some text.

[source,cpp]
----
//
// Comments
//
void MyFunc ( int Param1, char* Param2 )
{
  // Do stuff...
}
----
```

Syntax highlighting works in version 1.6.9.

Environment: Windows 10, 64-bit.

**Comment by rahmanusta** [comment]
Hey, try https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.1

**Comment by 3rady** [comment]
I can confirm that this has been resolved.  Thanks!
