### ISSUE TITLE
The word system renders as sys_t_e_m (version 1.7.1)

### ISSUE THREAD

**Issue by 3rady** [asciidocfx/AsciidocFX#431]
The word `system` renders as `sys_t_e_m`.  I have observed this in the preview window, HTML output, and PDF output.

Environment: Windows 10, AsciidocFX 1.7.1.

**Comment by rahmanusta** [comment]
Ops, it is my mistake. I'll resolve it today.

**Comment by rahmanusta** [comment]
Hi, please re-install https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.1, it is fixed.

**Comment by 3rady** [comment]
I have confirmed that the issue has been resolved.  Thanks so much for the quick response!
