### ISSUE TITLE
Diagrams in child documents do not render correctly in parent document (version 1.7.1)

### ISSUE THREAD

**Issue by 3rady** [asciidocfx/AsciidocFX#435]
Diagrams in child documents are not rendering properly.  For example, create the following files:

File `Parent.adoc`:

```
include::Child1.adoc[]

include::Child2.adoc[]
```

File `Child1.adoc`:
```
.State Machine
[plantuml,States.png,png]
----
[*] --> State1
State1 --> State2
State2 --> State1
----
```

File `Child2.adoc`:
```

.Blocks
[ditaa,file="io.png"]
----
     +---+
     |   |
---->+   |
     |   |
     +---+
----
```

The child documents render fine on their own, but the parent document renders like this:

![image](https://user-images.githubusercontent.com/17868878/62835547-9eb90380-bc0e-11e9-9df5-88170d237b91.png)

Environment: 
* Windows 10 64-bit
* AsciidocFX 1.7.1

**Comment by lifei** [comment]
same thing happen to me. any idea?

**Comment by lifei** [comment]
i check the old version 1.7.0, it works fine.
so there must be something wrong between 1.7.0 and 1.7.1

**Comment by lifei** [comment]
https://github.com/asciidocfx/AsciidocFX/compare/v1.7.0...v1.7.1

**Comment by lifei** [comment]
when I changed the directory `conf/public` with the one of version 1.7.0, the problem is gone. so there must be some untested changes in these javascript files which lead to this issue.

**Comment by rahmanusta** [comment]
Hi, can you check the new release ? https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.2

**Comment by lifei** [comment]
it works fine in v1.7.2
