### ISSUE TITLE
Linux installation in not in sync with manual

### ISSUE THREAD

**Issue by marcdexet-cnrs** [asciidocfx/AsciidocFX#447]
Hi

## Context

Manual says :" cd bin/, run ./AsciidocFX.sh"
There no more AsciidocFX.sh nor bin folder in the archive.

## Action

Correct manual

**Comment by lurch** [comment]
Looks like https://github.com/asciidocfx/AsciidocFX/blob/master/README.adoc#install-on-linux is correct but https://asciidocfx.com/#trueinstall-on-linux is lagging behind?

**Comment by rahmanusta** [comment]
New release is available https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.4
Please check if that fix your issue.
