### ISSUE TITLE
Tex math output problem in version 1.7.1 (Windows)

### ISSUE THREAD

**Issue by 3rady** [asciidocfx/AsciidocFX#450]
Tex math formulas do not output correctly as of version 1.7.1.  

For instance, this example on the AsciidocFX home page

```
[math,file="tex-formula.png"]
--
\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xyp
\end{align}
--
```

renders to this:

![tex-formula](https://user-images.githubusercontent.com/17868878/67171265-25a2fe80-f36b-11e9-8f7b-b24b43337ef5.png)

My environment is Windows 10 64-bit.

**Comment by jliu666** [comment]
I also met.

**Comment by ggessner** [comment]
i also encountered the problem!
For some reason the math keyword is not accepted anymore.
I assume commit cd8c64c4cca0e6f09fe9911334b4b575af4ea2f3 changed the behaviour.
Simply change keyword **math** -> **latexmath** or **mathml** and it will work again;
``` 
[latexmath,file="tex-formula.png"]
--
\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xyp
\end{align}
--
```

**Comment by rahmanusta** [comment]
Hi, could you please reinstall https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.4 and check?

**Comment by ggessner** [comment]
Hey, I can confirm that with the newest version, the `math` identifier works as expected and returns the same result as with `latexmath`.

**Comment by rahmanusta** [comment]
Thanks for testing 👍 I'm closing the issue.
