### ISSUE TITLE
asciidoctor stem s_t_e_m problem

### ISSUE THREAD

**Issue by yapbenzet** [asciidocfx/AsciidocFX#451]
AsciidocFX parse stem as s_t_e_m as shown in attached picture..

This is only a windows operating system problem.

![2019-10-29_10-52-04](https://user-images.githubusercontent.com/23086713/67747692-5b667800-fa3a-11e9-81a3-613476707d8f.png)

**Comment by rahmanusta** [comment]
Sorry, reinstalling the latest version https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.1 resolve that issue.

**Comment by yapbenzet** [comment]
confirm that problem solved when i reinstall..
thanks.
