### ISSUE TITLE
Listing block is not recognized correctly

### ISSUE THREAD

**Issue by ghorwin** [asciidocfx/AsciidocFX#457]
Hi all - AsciidocFX is awesome, and this bug report is really only cosmetic. Please see attached screenshot. When a listing block contains listing block separators itself, the syntax highlighting doesn pick up the different levels of listing blocks as Asciidoc defines.

Suppose you start a listing block with 5 dashes and finish it with 5 dashes. Then, you write a line with many more dashes (or fewer) inside the listing block. This appears to confuse the syntax highlighting (see attached image)

**Comment by rahmanusta** [comment]
Hi, can you share the attached image?

**Comment by ghorwin** [comment]
Sure. In the screenshot look at the block in the middle. The HTML/PDF Output is correct, though, so it seems only to be an editor issue.

![AsciidocFX_code_block_delimiter_problem](https://user-images.githubusercontent.com/6892676/78469991-1d2a5e80-7726-11ea-8edd-05b15b938322.png)

**Comment by rahmanusta** [comment]
You talk about the editor part right (middle)? not preview part ? If so, this should be reported https://github.com/ajaxorg/ace since we use that component, and have no control of this part.

**Comment by ghorwin** [comment]
Ok, thanks for the info. I'll submit a bug report there.
