### ISSUE TITLE
Freezing in v1.7.1

### ISSUE THREAD

**Issue by potatoqualitee** [asciidocfx/AsciidocFX#461]
First, thank you so very much for AsciidocFX. I am writing a book for Manning Publications, and when I asked what .adoc editor I should use, my editor told me that she uses AsciidocFX. It's a fabulous solution.

I am using this version of Windows:

![image](https://user-images.githubusercontent.com/8278033/69883424-67ad5180-12d4-11ea-9727-61d9af19e12e.png)

And I get freezes when AsciidocFX is "idle" for a short period of time. If I'm continuously editing, it's no problem, but if I go do something and come back (I haven't timed it but it feels like less than 5 minutes), I cannot type or open any documents from the side pane. I _may_ be able to scroll, but after selecting a paragraph where I'd write, it does not accept my keyboard input.

I have to close AsciidocFX, which works with no resistance. Then I reopen and have no problems until I'm idle again.

I reverted to 1.7.0 and will see if that helps.

**Comment by potatoqualitee** [comment]
Can confirm 1.7.0 still worked after 20 minutes of being idle 👍

**Comment by rahmanusta** [comment]
New release is available https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.4
Please check if that fix your issue.

**Comment by rahmanusta** [comment]
I’m closing the issue, let me know if I can help further

**Comment by potatoqualitee** [comment]
Thank you!
