### ISSUE TITLE
No syntrax diagram preview available

### ISSUE THREAD

**Issue by inponomarev** [asciidocfx/AsciidocFX#463]
It seems that AsciidocFX does not try to generate Syntrax diagrams preview (although Asciidoctor Diagram supports this type of diagrams)

## What AsciiDocFX shows:

![изображение](https://user-images.githubusercontent.com/20153286/70825810-5e54d680-1df6-11ea-8e74-ff25bbaba1f3.png)

## Actual result of compilation:

![изображение](https://user-images.githubusercontent.com/20153286/70825885-90663880-1df6-11ea-8ec7-2e8e394e7f5a.png)

**Comment by rahmanusta** [comment]
Hi, AsciidocFX doesn’t support it.

**Comment by inponomarev** [comment]
I see, and that's the issue 😄 If AsciidocFX does support Ditaa, GraphViz, PlantUML, why can't it support another diagram notation supported by Asciidoctor itself?

**Comment by rahmanusta** [comment]
Since AsciidocFX uses Asciidoctor.js, and AsciidocFX has its own plugins to support those diagrams.

**Comment by inponomarev** [comment]
This is no longer an issue with modern AsciidocFX, closing this for clarity :-) 
![image](https://github.com/user-attachments/assets/16e0dc01-3dbe-4acd-8a48-ae29f779b118)
