### ISSUE TITLE
Cannot generate PDF

### ISSUE THREAD

**Issue by RosanaKonciute** [asciidocfx/AsciidocFX#465]
I created a document on AsciidocFX. It has few levels (section-subsection-subsubsection) and it is located in few levels on folder system. I click PDF -> Save and I see in the log That PDF conversion ended. But it also says that generated 0 pages in total. it really creates pdf file, but when I open it I get the message "There was an error opening this ducument. The is demage and could not be repaired".

Why I can not generate pdf?

**Comment by rahmanusta** [comment]
I can tell why if you share the document.

**Comment by RosanaKonciute** [comment]
Please find attached main document ("wholeDocument") and folder structure

[Issue.zip](https://github.com/asciidocfx/AsciidocFX/files/4117326/Issue.zip)

**Comment by rahmanusta** [comment]
I recommend you creating your file structure, step by step, and see result on every step by generating pdf. At first look, I see two issue:

- AsciidocFX doesn't like :docinfo1:
- A document tree cannot have more than one first level header ( = )

**Comment by RosanaKonciute** [comment]
Fixed structure and deleted :docinfo1:. Now it generates pdf but with two included documents only. Doesn't work if there more than two documents included.

For example, thi one works:

:leveloffset: 1
include::modules/1section.adoc[]
include::modules/2section.adoc[]
:leveloffset: -1

But this one do not work:

:leveloffset: 1
include::modules/1section.adoc[]
include::modules/2section.adoc[]
include::modules/3section.adoc[]
:leveloffset: -1

Have any ideas why?

**Comment by rahmanusta** [comment]
Try spaces like below

```
:leveloffset: 1

include::modules/1section.adoc[]

include::modules/2section.adoc[]

include::modules/3section.adoc[]

:leveloffset: -1
```

**Comment by rahmanusta** [comment]
I close that issue, you can reopen it if the issue is still exist.
