### ISSUE TITLE
color definition

### ISSUE THREAD

**Issue by RosanaKonciute** [asciidocfx/AsciidocFX#466]
Hi,

I want to define section title color and I'm doing like this:

[[introduction]]
= [blue]#Introduction#

It works. But I want to define color in HEX to able choose from all the color. 
How to define this color code - #d0e1e7 instead of "blue"?

**Comment by rahmanusta** [comment]
Asciidoc has no such feature imho. However, you can use css only for HTML output. It will not work for PDF

```
++++
you can write here html and css
++++
```
