### ISSUE TITLE
Request: Add Preview Only mode

### ISSUE THREAD

**Issue by arqeco** [asciidocfx/AsciidocFX#467]
Please add a "Preview Only" mode where the editor is hidden, and the left bar is also hidden, and only the preview panel is visible. 

Sometimes you already wrote enough and you need only to read, revision, or study the text. In this moment the editor view is not needed and a clean, "Zen", mode is preferable.

This mode could be enabled and disabled by a third right tab, between "Preview" and "Settings":
`Preview` `Preview Only` `Settings`

Thank you for AsciidocFX.

Greetings,
Márcio

**Comment by rahmanusta** [comment]
Hi, not the same but you can detach preview panel (right click to preview) and make it full screen.

**Comment by rahmanusta** [comment]
New release is available https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.4
Please check if that fix your issue.
