### ISSUE TITLE
Title image not working in PDF

### ISSUE THREAD

**Issue by RosanaKonciute** [asciidocfx/AsciidocFX#468]
Hello,

I'm trying to add logo into adoc file. Tried already different ways and it's not working at anyway. 

= Book Name
:title-logo-image: logo.png
:toc: left
:doctype: book
:toclevels: 5

Also, I tried this one:

= Book Name
:front-cover-image: image::logo.png[]
:toc: left
:doctype: book
:toclevels: 5

I tried to paste into whole code of chronicles-example and still I'm not getting any logo in my pdf.

**Comment by rahmanusta** [comment]
Hi, this is not supported in AsciidocFX.

**Comment by RosanaKonciute** [comment]
Could you please suggest me any free tool which supports?

**Comment by rahmanusta** [comment]
You can check Asciidoctor PDF, maybe it supports

**Comment by RosanaKonciute** [comment]
It really supports! Thank you so much!
