### ISSUE TITLE
inline math baseline raised from normal text

### ISSUE THREAD

**Issue by masa300V** [asciidocfx/AsciidocFX#469]
When generating a PDF output, I found a **baseline position of my inline math** is way higher than the other text baseline.
No matter I try different scaling inside my math expressions, it seems like resulting image output placed at raised baseline.
My example screenshot below: PDF result upper half, working AsciidocFX lower half.  Full-scale image has thin red lines to illustrate my finding.

![test_inline_math](https://user-images.githubusercontent.com/37952014/78456508-ba738d00-7669-11ea-8032-1989d34af68b.png)

I'm using version 1.7.1 on windows 10.
Please provide a way to control inline math (inline image too?) baseline position.

best regards,
Masashi

**Comment by rahmanusta** [comment]
Sorry, this component has no such feature. You can play with css for html and xslt for pdf.
