### ISSUE TITLE
v1.7.2 fails to launch on OSX Mojave 10.14.6

### ISSUE THREAD

**Issue by starksm64** [asciidocfx/AsciidocFX#470]
I updated to 1.7.2 from 1.7.1 and now the AsciidocFX.app fails to launch. I have tried removing and doing a new install and the same problem exists. The log indicates there is a version incompatibility problem with the javax.servlet.ServletContext class. It looks like two versions of the servlet api have been included.

After I removed the lib/servlet-api-2.2.jar file I was able to launch the application.

[asciidocfx.log](https://github.com/asciidocfx/AsciidocFX/files/4461881/asciidocfx.log)

**Comment by rahmanusta** [comment]
Thanks for reporting, I excluded the old dependency from fop. Please re-download the build https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.2

**Comment by ViraHavrylenko** [comment]
Still there is a problem with Catalina 10.15.4

**Comment by rahmanusta** [comment]
New release is available https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.4
Please check if that fix your issue.

**Comment by starksm64** [comment]
Yes it does fix the issue

**Comment by rahmanusta** [comment]
Thanks
