### ISSUE TITLE
v1.7.2 fails to upgrade / install on homebrew with checksum error

### ISSUE THREAD

**Issue by ThomasStuetz** [asciidocfx/AsciidocFX#471]
It seems the Checksum-file may be not correct

%> brew cask install asciidocfx

==> Downloading https://github.com/asciidocfx/AsciidocFX/releases/download/v1.7.2/Asc
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'asciidocfx'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'asciidocfx' does not match.
Expected: 8849be62e8f771b3f1700821b84dce90160f2cdff12da26a0ecb0cce5612688e
  Actual: ad0fa55a7ee8fb5316ca24255bd31549a42f1ba4dd50d382871053991b2ceb0a
    File: /Users/xxx/Library/Caches/Homebrew/downloads/643c6fd28f39cb51f116eea653fbe63518d813d110e6fb13db9530a25743cddc--AsciidocFX_Mac.dmg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md

The same happened when upgrading.

**Comment by rahmanusta** [comment]
Hi,

I updated the cask. Please check.

**Comment by htl-leonding** [comment]
works smooth now, thank you
