### ISSUE TITLE
1.7.2 - attributes - docname not set for preview

### ISSUE THREAD

**Issue by pstueck** [asciidocfx/AsciidocFX#474]
Bug originally posted on [Asciidoctor#475](https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/475). I was told it has to be an AsciidoctorFX issue.

Copied from Asciidoctor ...

When I have a document named "myADoc.adoc" with an active preview pane, a code snippet like &hellip;
```adoc
\{docname} is {docname}
\{outfilesuffix} is {outfilesuffix}
```
displays in the preview pane as
> {docname} is {docname}
{outfilesuffix} is .html

but what I expect to see is &hellip;
> {docname} is myADoc
{outfilesuffix} is .html

Thus something like &hellip;
```adoc
ifeval::["myADoc" == "{docname}"]
// do some stuff specifically for this file
endif::[]
```
never does work in preview :-(

Regards
Peter

**Comment by tomdem29** [comment]
for informations i have the same "problem" with 1.7.2 :
no {docname}, {docfile} {docfilesuffix} rendering (in html and pdf).
These attributes are perfectly render with asccidoctor-pdf : 
Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

Regards
Tom

**Comment by rahmanusta** [comment]
Hi,

Can you please try https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.3 ?

**Comment by tomdem29** [comment]
Hi rahmanusta,
works great for me with v1.7.3.
Thanks.

**Comment by rahmanusta** [comment]
Thanks!

I'm closing the current issue. Let me know if you require further help.
