### ISSUE TITLE
AsciidocFX in Ubuntu 18.04 LTS: is jdk 8 installation also required?

### ISSUE THREAD

**Issue by knzudgt** [asciidocfx/AsciidocFX#475]
I would like to install `AsciidocFX` in `Ubuntu 18.04 LTS`.
The installation instructions say that I have to untar the package and run the following:

    $ cd bin
    $ ./AsciidocFX.sh

Am I also required to install `jdk 8` or its installation is included in the installation of `AsciidocFX`?

**Comment by rahmanusta** [comment]
Hi, just install and run, you don't need to install java. AsciidocFX has Java 12 bundled inside.

**Comment by rahmanusta** [comment]
Hi, I'm closing the current issue. Let me know if you require further help.
