### ISSUE TITLE
Looking for help! How to support 2 paper formats when creating a pdf File with AsciiDocFX?

### ISSUE THREAD

**Issue by Udo-101** [asciidocfx/AsciidocFX#480]
Hello!
I like the functionality of AsciiDocFX that allows to easily create a pdf file from the asciidoc source.
I have the need to support 2 paper formats for the pdf files - A4 and A5. 
I know the place were to change the paper format in fo-pdf.xsl.
But how could I select the right format to use from within AsciiDocFX?

Thank you for any help you can provide.
Kind regards, Udo

**Comment by rahmanusta** [comment]
Hi, just change fo-pdf.xml and generate pdf from AbciidocFX. It will just pick up and generate pdf like how xsls are configured. No additional configuration included.

**Comment by Udo-101** [comment]
@rahmanusta: Thank you very much for your immediate response.
Hm, I do not find a fo-pdf.xml in the AsciiDocFX installation directory, Just fo-pdf.xsl in AsciidocFX\conf\docbook-config
That's were I made my changes. I can have a file containing the A4 definition and a second one with the A5 definition.
But what can I do to be able to select in the AsciiDocFX GUI either the A4 size or the A5 size?

Thanks and kind regards,

Udo

**Comment by rahmanusta** [comment]
I mean fo-pdf.xsl or related docbook files. There is no option in AsciidocFX GUI to select page size or etc. AsciidocFX just pick up xsl files and generate PDF.

**Comment by Udo-101** [comment]
@rahmanusta: Thanks again for the fast response and the clarification.
I created now a fo-pdf.xsl for every format. And I use a batch file to select the right file for printing. Not sophisticated but working.
Thank you for your help.
Kind regards,

Udo
