### ISSUE TITLE
asciimath inline keyboard shortcurt request

### ISSUE THREAD

**Issue by yapbenzet** [asciidocfx/AsciidocFX#488]
hi,

we use asciidocfx for our documentation and use asciimath for mathematical equations... So we use alot of asciimath:[ ] inline asciimath.. I know that math + tab can add math BLOCK but i need asciimath:[ ] INLINE..

so how can i add a shortcut like math2 or ascmath + tab for asciimath:[ ]

**Comment by rahmanusta** [comment]
New release is available https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.4

Proper commit can be seen https://github.com/asciidocfx/AsciidocFX/commit/f0e660c7af4ed00b4ab448370aa5a8345eb82895

Please check if that fix your issue.

**Comment by rahmanusta** [comment]
I’m closing that issue, let me know if I can help further
