### ISSUE TITLE
Outline is incorrectly shown

### ISSUE THREAD

**Issue by hysci** [asciidocfx/AsciidocFX#489]
Document contents:
= a
== b
=== c
==== d
===== e

Wrong outline snapshot:
![image](https://user-images.githubusercontent.com/6468488/96678097-91b3aa80-13a3-11eb-9f23-46fe8284ac72.png)

Platform: 
Windows 10 1912

AsciiDocFx Version:
1.7.3

**Comment by rahmanusta** [comment]
Hi,

Can you put space between lines?

**Comment by hysci** [comment]
Wow, your suggestion works. The actual case is as follows, I was trying to find a way to repo it with minimum texts. Let me try to reduce the document size (with ~1 thousand of lines)
![image](https://user-images.githubusercontent.com/6468488/96834852-48339000-1475-11eb-8626-8283ff985600.png)

**Comment by therealhammer** [comment]
I am having the same problem. 

Once the outline gets more complex, it just shows weird hierarchies 

![image](https://user-images.githubusercontent.com/32392096/189539694-730f5cd1-c004-4133-9961-25cbd65cb28a.png)

**Comment by rahmanusta** [comment]
Hi, Thanks for reporting. I just fixed the issue. Can you reinstall https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.8 and check if it works ?

**Comment by therealhammer** [comment]
OMG it works! Thank you so much for fixing it so quickly! I'm in the middle of writing a report with asciidoc where i have to change chapters a lot and this is such an improvement!
Can't thank you enough @rahmanusta !
