### ISSUE TITLE
dynamic c/p of images/screenshots

### ISSUE THREAD

**Issue by wibrt** [asciidocfx/AsciidocFX#492]
feature request:

programs like tiddlywiki, qownotes, zim, .. support the ability to paste an image into the editor,
it would be nice to have something similar like this in asciidocfx,
speeding up productivity

for example after pasting an image in qownotes, the following code is shown (their own markup):
![qownnotes-media-BzZWks](media/qownnotes-media-BzZWks-881037374.png)
and the actual pasted image is shown in the the preview

for example:
![image](https://user-images.githubusercontent.com/17875724/104010532-edc0ea80-51ac-11eb-9864-758658ce4c54.png)

--

so for asciidocfx this would translate to:
1. paste the image
2. automatically add code image::images/image_id_string.png[]
3. optionally ask for the desired name of image when pasting, with a images/image_id_string.png already prefilled in the input field for this
4. optionally make the images directory a setting, maybe a separate setting from the images that come from the filesystem, which are more likely to have a meaningful name
4.1 dir images for images put there by the user
4.2 dir images_pasted for this use case or pasted images which might have not such meaningful name

**Comment by wibrt** [comment]
ctrl+v doesnt work, but it this seems implemented with clipboard pasting, using the mouse to paste the content of the clipboard

just wondering/asking, why does ctrl+v only work for text and not for the clipboard?

**Comment by rahmanusta** [comment]
Sorry, you can use ctrl-shift-v, I think it should paste the clipboard image.
