### ISSUE TITLE
PlantUML picture in Preview is incomplete/wrong if svg is selected

### ISSUE THREAD

**Issue by DaLynxx** [asciidocfx/AsciidocFX#498]
AsciidocFX version: 1.7.3
Platform: Windows 10

The following 
```
[plantuml, diagram-classes, png]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....
```
Generates a correct picture. However if I change it to `[plantuml, diagram-classes, svg]` the picture is incomplete in the preview.
, i.e. it is there but there are lines/boxes missing,

The svg picture is correctly generated when you look at the created file in the folder. The PDF generation in AsciidocFX uses the svg file with no problem since you can zoom in without the picture becoming "pixelized".

**Comment by rahmanusta** [comment]
JavaFX's SVG support is limited, SVG output will be correct in browser or PDF output.
