### ISSUE TITLE
AsciidocFX_Mac.dmg fail on MacOS Catalina

### ISSUE THREAD

**Issue by stevebeisner** [asciidocfx/AsciidocFX#499]
I don't know about other MacOS versions, but on Catalina (10.15.7)
the AsciidocFX Installer.app fails with  with error shown in this 
screen capture.
![Screen Shot 2021-01-30 at 11 16 10 AM](https://user-images.githubusercontent.com/587346/106365957-b813ab00-62ed-11eb-903a-de119f7946b4.png)
~Steve Beisner beisner@alum.mit.edu

**Comment by stevebeisner** [comment]
The same failure occurs when using the homebrew install method.

**Comment by rahmanusta** [comment]
Hi Steve,

I’ll check why this is showed, but you can trust the package in our github release page.

Can you try this? I hope it helps

“Move the package to the Desktop and then hold Control and click the file to launch the installer. When the message appears, click Continue.”

**Comment by stevebeisner** [comment]
Thanks for your quick reply.  This looks like great work, so I look forward to
being able to install it.  Here's what I've tried:
From "https://github.com/asciidocfx/AsciidocFX/releases", 
I clicked and downloadeded, "AsciidocFX_Mac.dmg".
Mounted "AsciidocFX_Mac.dmg", dragged "AsciidocFX Installer.app" to Desktop.
I held down the CTRL key and double clicked the installer: "AsciidocFX Installer.app".
Boom... the error message dialog  ("can't be opened") appears.  
I went back and re-downloaded, but same thing always occurs.

I suspect this is a MacOS Catalina problem:  Apple is getting really
**_fussy_** about installing new apps, but I've always been able to get
it done... until now, with Asciidocfx.

Steve Beisner

**Comment by stevebeisner** [comment]
Thanks for your quick reply. This looks like great work, so I look forward
to
being able to install it. Here's what I've tried:
From "https://github.com/asciidocfx/AsciidocFX/releases",
I clicked and downloadeded, "AsciidocFX_Mac.dmg".
Mounted "AsciidocFX_Mac.dmg", dragged "AsciidocFX Installer.app" to Desktop.
I held down the CTRL key and double clicked the installer: "AsciidocFX
Installer.app".
Boom... the error message dialog ("can't be opened") appears.
I went back and re-downloaded, but same thing always occurs.

I suspect this is a MacOS Catalina problem: Apple is getting really
*fussy* about installing new apps, but I've always been able to get
it done... until now, with Asciidocfx.

Steve Beisner

**Comment by rahmanusta** [comment]
New release is available https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.4

Please check if that fix your issue.

**Comment by rahmanusta** [comment]
I’m closing the issue, let me know if I can help further

**Comment by oddcb** [comment]
Hi. This is still an issue with 1.7.4. 

The problem seems to be that the app is not notarized or from a known developer. See "If you want to open an app that hasn’t been notarized or is from an unidentified developer" at https://support.apple.com/en-us/HT202491

You can bypass the restriction by going to Security and privacy and allow the installer to run, as described in the linked page above.
