### ISSUE TITLE
Let apply settings to define the margin limits to export PDF

### ISSUE THREAD

**Issue by manueljordan** [asciidocfx/AsciidocFX#500]
Hello

Please, would be possible enable margins configurations prior to export or generate a PDF?. 
Some times long lines breaks in two lines, but I can see a good amount of empty space for the left and right margins.
So if I can reduce them I am sure that the content is going to be shown in one line.

Thanks for your understanding

**Comment by life888888** [comment]
AsciidocFX 1.7.6+
add in your adoc file header  `:pdf-page-margin: [5cm, 1cm]`

REF: https://docs.asciidoctor.org/pdf-converter/latest/asciidoc-attributes/

I have tested this setting and it works.

**Comment by manueljordan** [comment]
Huge thanks for this!, as I can see (not tested yet) it works for cms and inches
