### ISSUE TITLE
AsciidocFX or jvm issue (hth)

### ISSUE THREAD

**Issue by wibrt** [asciidocfx/AsciidocFX#501]
Reported at

https://github.com/AdoptOpenJDK/openjdk-support/issues/254

(linux, debian stable)

**Comment by wibrt** [comment]
The feedback from openjdk is:

`I assume you have downloaded a precompiled version? If that's the case, please ask the AsciidocFX people to update the JVM and OpenJFX to 15. OpenJDK 12 has been out of support for a long time. It also looks like the problem originates in OpenJFX.`

hth, maybe also for other issues of AsciidocFX

**Comment by rahmanusta** [comment]
New release is available https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.4

Please check if that fix your issue.
