### ISSUE TITLE
URGENT: asciidocfx does not create ditaa - diagrams when hash has not changed (means after you finished your code)

### ISSUE THREAD

**Issue by erdincay** [asciidocfx/AsciidocFX#503]
- open asciidocfx
- create an asciidoc file 
- create an ditaa diagram
- finish your ditaa diagram

```
[ditaa]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
+--------+   +--------+----+    +---------------+
|        +---+ Asciidoctor +--->|               |
|  Text  |   +-------------+    |   Beautiful   |
|Document|   |   !magic!   |    |    Output     |
|     {d}|   |             |    |               |
+---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lotsxx of work           |
     +-----------------------------------+
....
```

- close asciidocfx
- restart asciidocfx
- diagram is not generated

**Turning off the Cache did not change this, I assume it does not create the diagram when the HASH does not change, 
OR I assume that the cached file is somewhat deleted ?** 

Environment: 

- Windows 10 - Version 1909
- openjdk version "1.8.0_282"
- OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
- OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)

**Comment by erdincay** [comment]
@rahmanusta plz, urgent

**Comment by lefou** [comment]
@erdincay Did you forgot to append the patch for this urgent issue? I'm sure, providing a pull request with a fix will speed up a bugfix release significantly.

**Comment by erdincay** [comment]
> 
> 
> @erdincay Did you forgot to append the patch for this urgent issue? I'm sure, providing a pull request with a fix will speed up a bugfix release significantly.

@lefou, which patch do you want from me? 

i did not write any patch for this, as I do not know where the issue is, I assume deactivating the caching will do the job, but it does not work

**Comment by rahmanusta** [comment]
@erdincay type a key or click HTML/PDF to regenerate diagrams.

**Comment by erdincay** [comment]
![grafik](https://user-images.githubusercontent.com/11290149/111135520-0ec30480-857d-11eb-8f27-295390304071.png)

@rahmanusta I did press a key, I did try regenerating the PDF to enable a recreation of the diagram, but it does not work, I have attached an screenshot for you.

**Comment by erdincay** [comment]
@rahmanusta have updated my previous answer with the image (please page reload to view)

**Comment by rahmanusta** [comment]
Please share your document so we can review.

**Comment by erdincay** [comment]
Please rename from 'RS.adoc.txt' to 'RS.adoc', GitHub does not allow uploading *.adoc files over this comment section.
[RS.adoc.txt](https://github.com/asciidocfx/AsciidocFX/files/6140495/RS.adoc.txt)

**Comment by rahmanusta** [comment]
Seems there is a bug, I'll it take a look.

**Comment by erdincay** [comment]
> Seems there is a bug, I'll it take a look.

Is there any update on this issue, @rahmanusta ?

**Comment by rahmanusta** [comment]
It will be fixed in the next release, it is in progress.

**Comment by erdincay** [comment]
> It will be fixed in the next release, it is in progress.

hi @rahmanusta, do you have any date for the next release of AsciidocFX?

**Comment by rahmanusta** [comment]
@erdincay Working on this, most probably will be in May.

**Comment by rahmanusta** [comment]
New release is available https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.4

**Comment by rahmanusta** [comment]
I’m closing the issue, let me know if you need help

**Comment by erdincay** [comment]
> I’m closing the issue, let me know if you need help

Everything is working fine, will report back in case of any issues! Well done, and big thanks from our team.
