### ISSUE TITLE
Ability to change html id anchor?

### ISSUE THREAD

**Issue by hohwille** [asciidocfx/AsciidocFX#51]
You seem to have a buildin server (http://localhost:44299) that renders the asciidoc as html. This is very cool. However I am using github wiki infrastructure to maintain documentation and that generates anchors for sections by replacing whitespaces with a hypen while you seem to use an underscore and also add one underscore as prefix. Therefore my page-internal links are not working in your preview.

I am aware that there is no standard for this but as github (gollum) is quite a prominent case for asciidoc rendering it would be awesome if asciidocfx could be configured to render the anchor ids in a compatible way (using hypen instead of underscore and without a prefix).

**Comment by hohwille** [comment]
FYI:
https://github.com/oasp/oasp-docgen/wiki
https://github.com/oasp/oasp4j/wiki
http://oasp.github.io/oasp4j/1.0.0/OASP4J.pdf

**Comment by ozlerhakan** [comment]
Hi @hohwille ,

If I undestand you correctly, what you are pointing out does not related to AsciidocFX. This behavior directly relates to the way of rendering asciidoc pages. By default, each page is rendered as you explained, whereas if you make some changes in your asciidoc file like putting the following ones at the top of your doc : 

````
:sectanchors: 
:idprefix: 
:numbered:
```` 
, you can manipulate each anchor now. Here is the examples that you may want to examine:
 https://github.com/kodsnip/Java-QA/blob/master/questions.adoc
 https://github.com/kodsnip/Java-QA/blob/master/README.adoc
 
 Also I can recommend you to take a look at this Asciidoc documentation which describes the point : http://asciidoctor.org/docs/user-manual/#titles-as-headings

**Comment by rahmanusta** [comment]
Hey @hohwille . Did Hakan's answer solve your problem?

**Comment by hohwille** [comment]
@ozlerhakan: thanks for your suggestion. It almost solves my problem. Using the suggested code in every asciidoc page removes the prefix but still uses underscores instead of hyphens. And as this is not honored by github I still need a solution to make the same links work on github wiki as well as in asciidocfx.
Did I understand correctly that the rendering is actually done by product that you integrated into asciidocfx and so this is actually not a matter of asciidocfx itself. If so what are you using? asciidoctor?

**Comment by hohwille** [comment]
actually github honors some things of that and changes to links to include the section number.
So :sectanchors: actually breaks all my links as it includes the section number not only to the displayed text but also to the anchors what makes them unstable and kind of useless. Nice feature but not suitable to me.
:idprefix: helped to get rid of the prefix.

**Comment by ozlerhakan** [comment]
You're welcome @hohwille , we are also learning such things about asciidoctor :)

If GitHub wiki is the case, and what I showed did not solve your problem, then try this option:
```
:idseparator: -
```
I found it in the asciidoctor repo hosted on GitHub : https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/section.rb#L87

I hope this can help your need.

**Comment by hohwille** [comment]
Awesome. You are my hero! :+1: 
Works like a charm.

**Comment by hohwille** [comment]
FYI:
ifndef::env-github[:numbered:]
https://github.com/github/markup/issues/293
