### ISSUE TITLE
How to export PDF with chinese fonts

### ISSUE THREAD

**Issue by tbs575** [asciidocfx/AsciidocFX#512]
I using asciidocFX v1.7.3 on windows 7, can not export PDF with chinese character. chinese character became #### in PDF.

**Comment by rahmanusta** [comment]
Hi, probably to setup correct fonts for chinese characters. You can see font selections in https://github.com/asciidocfx/AsciidocFX/blob/master/conf/docbook-config/fo-pdf.xsl . You may need to change your local fo-pdf.xsl.

**Comment by tbs575** [comment]
thanks, fixed

**Comment by tbs575** [comment]
@rahmanusta Hi, as URL add chinese fonts, export PDF OK, but met new issue.  Level 3 Section Title chinese can not export correctly. see pic.

modified fo-pdf.xsl
--- 
    <xsl:template name="pickfont-sans">
        <xsl:text>SimHei,Sans-serif,Arial,Arial Unicode MS,Helvetica,serif,Georgia,Times New Roman</xsl:text>
    </xsl:template>

    <xsl:template name="pickfont-serif">
        <xsl:text>SimHei,Sans-serif,Arial,Arial Unicode MS,Helvetica,serif,Georgia,Times New Roman</xsl:text>
    </xsl:template>

    <xsl:template name="pickfont-mono">
        <xsl:text>SimHei,Liberation Mono,Lucida Console,Monaco,Consolas,Courier New,Courier,monospace,Arial Unicode MS,Lucida Sans Unicode</xsl:text>
    </xsl:template>

    <xsl:template name="pickfont-dingbat">
        <xsl:call-template name="pickfont-sans"/>
    </xsl:template>

    <xsl:template name="pickfont-symbol">
        <xsl:text>SimHei,Symbol,ZapfDingbats</xsl:text>
    </xsl:template>

    <xsl:template name="pickfont-math">
        <xsl:text>Liberation Serif,Sans-serif,serif,Times-Roman</xsl:text>
    </xsl:template>
----
in editor is right.
![image](https://user-images.githubusercontent.com/30616402/115485761-eb7c2b00-a287-11eb-9492-996ac218ee45.png)

but error in export PDF
![image](https://user-images.githubusercontent.com/30616402/115486023-61809200-a288-11eb-8526-a30c940552ef.png)

**Comment by rahmanusta** [comment]
You can find the solution here https://github.com/asciidocfx/AsciidocFX/issues/287

**Comment by rahmanusta** [comment]
You can find the solution here https://github.com/asciidocfx/AsciidocFX/issues/287

```
Index: conf/docbook-config/fo-pdf.xsl
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/conf/docbook-config/fo-pdf.xsl b/conf/docbook-config/fo-pdf.xsl
--- a/conf/docbook-config/fo-pdf.xsl	(revision 07679a892bde5098e7a9b0e94fe832a1456c5846)
+++ b/conf/docbook-config/fo-pdf.xsl	(date 1618985193766)
@@ -854,37 +854,26 @@
 
     <xsl:attribute-set name="section.title.level1.properties">
         <xsl:attribute name="font-size">12pt</xsl:attribute>
-        <xsl:attribute name="font-weight">bold</xsl:attribute>
     </xsl:attribute-set>
 
     <xsl:attribute-set name="section.title.level2.properties">
         <xsl:attribute name="font-size">12pt</xsl:attribute>
-        <xsl:attribute name="font-style">italic</xsl:attribute>
-        <xsl:attribute name="font-weight">bold</xsl:attribute>
     </xsl:attribute-set>
 
     <xsl:attribute-set name="section.title.level3.properties">
         <xsl:attribute name="font-size">12pt</xsl:attribute>
-        <xsl:attribute name="font-style">italic</xsl:attribute>
-        <xsl:attribute name="font-weight">bold</xsl:attribute>
     </xsl:attribute-set>
 
     <xsl:attribute-set name="section.title.level4.properties">
         <xsl:attribute name="font-size">12pt</xsl:attribute>
-        <xsl:attribute name="font-style">italic</xsl:attribute>
-        <xsl:attribute name="font-weight">bold</xsl:attribute>
     </xsl:attribute-set>
 
     <xsl:attribute-set name="section.title.level5.properties">
         <xsl:attribute name="font-size">12pt</xsl:attribute>
-        <xsl:attribute name="font-style">italic</xsl:attribute>
-        <xsl:attribute name="font-weight">bold</xsl:attribute>
     </xsl:attribute-set>
 
     <xsl:attribute-set name="section.title.level6.properties">
         <xsl:attribute name="font-size">12pt</xsl:attribute>
-        <xsl:attribute name="font-style">italic</xsl:attribute>
-        <xsl:attribute name="font-weight">bold</xsl:attribute>
     </xsl:attribute-set>
 
     <xsl:attribute-set name="component.title.properties">

```

**Comment by tbs575** [comment]
@rahmanusta 
thanks your help, but still issue. please see pic. more '#' (red mark), why?
![image](https://user-images.githubusercontent.com/30616402/115514319-8ee43480-a2b6-11eb-893d-ce6e8f42f10e.png)

**Comment by rahmanusta** [comment]
Hmm, can you please send the letters? I don't know how to type such :)

**Comment by tbs575** [comment]
@rahmanusta 

= 第一级

== 第二级

=== 第三级

==== 第四级

**Comment by rahmanusta** [comment]
I don't have this,

do you have there some hidden character ? Could you please share your asciidoc file ?

![image](https://user-images.githubusercontent.com/1158804/115523164-16b54900-a28d-11eb-86a7-5a6c2c23f4a8.png)

**Comment by tbs575** [comment]
@rahmanusta  thanks
[111.txt](https://github.com/asciidocfx/AsciidocFX/files/6350638/111.txt)

**Comment by tbs575** [comment]
@rahmanusta thanks your help, I change chineses font, Using 'Microsoft YaHei', issue gone. I am not sure that is font files issue or more configure with fo-pdf.xsl
