### ISSUE TITLE
PDF generation not working in v1.7.4

### ISSUE THREAD

**Issue by ssl-utn-frba** [asciidocfx/AsciidocFX#515]
Today I downloaded v1.7.4. While generating the PDF an error occurred and no PDF was generated.

I had to downgrade to v1.7.3, where I was able to generate the PDF.

I promise I will add more detail to this issue, I'm in a rush but I wanted the community to know about the problem.

AsciidocFX is a great product, thanks @rahmanusta.

**Comment by rahmanusta** [comment]
Hi, thanks for reporting. Could you please share a sample document to check the issue?

**Comment by ssl-utn-frba** [comment]
Hi, I've downloaded v1.7.4 again to try triggering the issue again, but luckily everything works now.
The 1.7.4 release from two days ago fixed the issue I had went the 1.7.4 from 6 days ago.
Thanks!
