### ISSUE TITLE
Prompt to save changes on exit

### ISSUE THREAD

**Issue by bblonski** [asciidocfx/AsciidocFX#52]
I've lost work several times by forgetting to save before exiting.  It would be nice if AsciidocFX prompted to save unsaved work or at least warn when there are unsaved work before exiting.

**Comment by rahmanusta** [comment]
We are thinking to implement it in further release.

**Comment by rahmanusta** [comment]
This was implemented and will be available in 1.3.4 release.

**Comment by bblonski** [comment]
Great work, but I noticed that it only works when you close a tab and not when you close the application itself.  Is there any chance you could add the same prompt when you try to close the application?

**Comment by rahmanusta** [comment]
Yes it can be. That didnt fall in my mind :)
