### ISSUE TITLE
Can't save as PDF

### ISSUE THREAD

**Issue by owieboy** [asciidocfx/AsciidocFX#53]
When I try to save my asciidoc as PDF I get a bunch of #########
![selection_072](https://cloud.githubusercontent.com/assets/7962021/6549907/a99a04fa-c656-11e4-8df1-dbe8d10be7a6.png)

**Comment by rahmanusta** [comment]
Hi;

You need to install Microsoft core fonts package

**Comment by rahmanusta** [comment]
For example for ubuntu/debian ```sudo apt-get install graphviz ttf-mscorefonts-installer```

**Comment by owieboy** [comment]
That worked, thanks.
