### ISSUE TITLE
.adoc to pdf with 3rd header is# in Chinese

### ISSUE THREAD

**Issue by hanbing5210** [asciidocfx/AsciidocFX#534]
the file of exported pdf ![image](https://user-images.githubusercontent.com/32626294/139524850-157cbf4e-fd2b-4b12-af3a-df279d4c6824.png)

code in .adoc 
![image](https://user-images.githubusercontent.com/32626294/139524880-58823a07-e589-4832-9a6c-7b8261018fb4.png)

**Comment by Ayowel** [comment]
Could you copy/paste your .adoc or add it as an attachment to make reproducing the issue easier ?

**Comment by life888888** [comment]
- You can reference https://github.com/life888888/asciidocfx-pdf-cjk-patch to fix it.
- AsciidocFX/conf/docbook-config/fo-pdf.xsl
- AsciidocFX/conf/docbook-config/fop.xconf.xml
- 根本問題是  中文字型的 斜體字 , 粗斜體 字型 沒有被設定, 那些中文顯示成為 `#` 都是因為 被設定為 斜體 , 只要有斜體 或 粗斜體 或 斜粗體,

**Comment by hanbing5210** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by life888888** [comment]
1. After AsciidocFX 1.7.6+, PDF Engine  Default is ASCIIDOCTOR。Not FOP。
You can use https://github.com/asciidocfx/Asciidoctor-CJK-Demo and custom you CJK Font and Theme.
But You will missing Bold, Italic , Bold Italic style fonts.

2 You can use https://github.com/life888888/asciidoctor-pdf-cjk-ext#asciidocfx
support Chinese, Japanese, Korean.
Fonts: Noto Sans CJK, Noto Sans Mono CJK, Noto Serif CJK
Suppoty 4 style fonts:  Regular, Bold, Italic , Bold Italic.

**Comment by hanbing5210** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
