### ISSUE TITLE
Let AsciidocFX define the web browser when Browser is clicked

### ISSUE THREAD

**Issue by manueljordan** [asciidocfx/AsciidocFX#537]
Hello

Currently if I do click in the `Browser` yellow option it opens the default Web Browser of the OS. I did do a research in the `Settings` tab and I couldn't find for each section an option to define the web browser to be opened.

Thanks for your understanding

**Comment by rahmanusta** [comment]
Unfortunately, this feature is not implemented.

**Comment by rahmanusta** [comment]
I want to get What is the problem with the default browser? and Why just don't change the default browser ?

**Comment by manueljordan** [comment]
For example, I have in the OS 4 different Web Browsers - consider that the default defined in the OS is Opera - but for AsciidocFX I want define explicitly other different - let say Firefox. Therefore that is the request, when I have loaded the view preview and a click is done in any link - it should open Firefox (custom web Browser) and not Opera (OS' default)

**Comment by rahmanusta** [comment]
Feature has been implemented, and it will be available in next release.

**Comment by manueljordan** [comment]
Huge thanks for this new addition!

**Comment by manueljordan** [comment]
For Linux Ubuntu 22:04 - I got the 1.8.4 release ... in the _Settings_ tabs located in the rigth, in what tab is expected to accomplish this configuration? I couldn't find it.

**Comment by rahmanusta** [comment]
It will be available at v1.8.5

**Comment by manueljordan** [comment]
Thanks for the reply and information

**Comment by rahmanusta** [comment]
This feature is available https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.8.5
