### ISSUE TITLE
v1.7.4 Previews not working

### ISSUE THREAD

**Issue by Ulathar** [asciidocfx/AsciidocFX#542]
Hello there,

I can't seem to get the previews to work using .md Markdown documents, see this very simple test file:
![grafik](https://user-images.githubusercontent.com/6397124/151356374-0afaac28-818c-4695-848c-1dd1179b0c51.png)

There are no errors or warnings on the console / log and when I convert to PDF or HTML the output looks good, too.
So I have no clue why the preview is always empty / just a white page.

**Comment by rahmanusta** [comment]
Hi, Markdown is not a supported format in AsciidocFX.

**Comment by Ulathar** [comment]
You mean in terms of previews or in general? Because the converted / exported documents work just fine, also it offers syntax highlighting when you choose "Markdown" as file type. Now i am confused :).

**Comment by rahmanusta** [comment]
AsciidocFX is using the Asciidoctor library, which supports the Asciidoc markup language. Additionally, it can support a small  set of support for Markdown, but it is not that fully supported in Asciidoctor and AsciidocFX. If you don't have a spesific reason I may recommend you using Asciidoc rather then Markdown :)

**Comment by Ulathar** [comment]
Ah understood, that makes sense, thank you for the clarification! 
Issue resolved then, i'ed say (unless MD support is planned for the future).
