### ISSUE TITLE
AsciidocFX breaks on ARM 

### ISSUE THREAD

**Issue by albertoSoto** [asciidocfx/AsciidocFX#543]
I have tried to use on a mac M1pro.
The software starts but it breaks randomly
No big details are shown on the log file

It should be added an ARM compilation.
I've tried to help with it, but I can't compile it due to packager key problems

Would be great to keep using this amazing software!

**Comment by rahmanusta** [comment]
Hi, M1 builds are available here  https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.7
