### ISSUE TITLE
Illegal character in path

### ISSUE THREAD

**Issue by Johan1974** [asciidocfx/AsciidocFX#547]
Hello,

I am using vscode for creating asciidoc manuals. This works fine but does not seem to support the full asciidoctor syntax. 
So i am allways looking for other editors to see if they can do a better job. 

My documentation works fine in vscode but when i try this in asciidocfx it can read include files what i use a lot to limit double text. 
I am getting an error there is an illegal character? Can you tell me what characters are not allowed?

I have added the log it produced.

[Illegal character in path.txt](https://github.com/asciidocfx/AsciidocFX/files/8274855/Illegal.character.in.path.txt)

Hope you can help.

Johan

**Comment by Ayowel** [comment]
Looks like the problem is due to the space in your path, if you can rename the directory to remove/replace the space for `1 BASISDOC`, it should work.
This is something that should be fixed ni asciidoc, but in general it's good practice to avoid using spaces in paths.

**Comment by rahmanusta** [comment]
Can you check the latest release if it works ? https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.9
