### ISSUE TITLE
Problems with PDF Conversion

### ISSUE THREAD

**Issue by feherPhD** [asciidocfx/AsciidocFX#549]
In the Hungarian language we use special characters, 
Linux : UTF-8 coding
= Test With Hungarian National Characters

aáeéiíoóöőuúüű

AÁEÉIÍOÓÖŐUÚÜŰ
![Kijelölés_049](https://user-images.githubusercontent.com/107246497/173084294-a3d662dc-749f-42d0-bf7c-d4e9bead9f9f.png)

The Long őŐűŰ character missing in the PDF file:

**Comment by gillesB** [comment]
In the newer versions Asciidoctor can be used to render PDFs.
For me this solved the problem without further steps.

After installing the newest version, ensure that in the PDF settings `ASCIIDOCTOR` is selected and not `FOP`.

![image001](https://user-images.githubusercontent.com/1679281/188172201-bfd5ad18-fb2f-4634-88d8-b69a7d30d914.png)
