### ISSUE TITLE
Update to current plantuml.jar & support of "skin rose" to use former color scheme

### ISSUE THREAD

**Issue by bohni** [asciidocfx/AsciidocFX#552]
plantuml has new releases, current is v1.2022.06

Since 1.2022.01 there is a new color scheme.

Old behavior can be obtained by using "skin rose", but this is ignored in AsciidocFX 1.7.4 with new plantuml.jar copied to lib-folder

**Comment by rahmanusta** [comment]
Hi,

Can you give a try to https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.5 ?

It has v1.2022.5

**Comment by rahmanusta** [comment]
Hi, sorry, AsciidoctorJ has its own plantuml version and separate from the one under /lib. However, I'm not sure the old one will interfere with the version in AsciidoctorJ. More story short, I updated the v1.7.5 with version change https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.5 , it now includes the v1.2022.5

**Comment by bohni** [comment]
Thanks, issue solved.

Rendering now uses new color scheme.

"skin rose" is now supported fpr old color scheme
