### ISSUE TITLE
Mermaid broken on 1.7.5

### ISSUE THREAD

**Issue by fpizzinicce** [asciidocfx/AsciidocFX#553]
Tried the examples but shows this error:

Failed to generate image: Could not find the 'mmdc' executable in PATH; add it to the PATH or specify its location using the 'mmdc' document attribute

**Comment by rahmanusta** [comment]
Some extensions require additional tool to install such as for mermaid https://github.com/mermaid-js/mermaid-cli

**Comment by fpizzinicce** [comment]
I tried instaling mermaid globally but shows the same error :(
It works fine on 1.7.4 though...

**Comment by rahmanusta** [comment]
Mermaid on v1.7.4 was experimental and had some issues. 

You can install the mmdc tool locally like below

`npm install @mermaid-js/mermaid-cli`

and later include the path as a document attribute like below

```
:mmdc: ./node_modules/.bin/mmdc

[mermaid,target="mermaid-graph"]
--
graph TD
    A[Start] --> B{Is it?};
    B -- Yes --> C[OK];
    C --> D[Rethink];
    D --> B;
    B -- No ----> E[End];
--
```

**Comment by fpizzinicce** [comment]
Works!

Thanks @rahmanusta
