### ISSUE TITLE
Chinese cannot be displayed normally after windows11 saves pdf files

### ISSUE THREAD

**Issue by xp12047** [asciidocfx/AsciidocFX#554]
Please help, thanks    
![mmexport1658896568548](https://user-images.githubusercontent.com/56335408/181163103-b49fbd66-5b1b-4a49-91e5-46424789ee8e.png)
![mmexport1658896572808](https://user-images.githubusercontent.com/56335408/181163112-63a5e3b8-020d-4988-97aa-aa5e8127bcf5.png)

**Comment by rahmanusta** [comment]
Hi,

You need to create a custom theme. An example can be seen here https://github.com/asciidocfx/asciidoctor-cjk-demo

**Comment by xp12047** [comment]
> 你好，
> 
> 您需要创建一个自定义主题。可以在这里看到一个例子https://github.com/asciidocfx/asciidoctor-cjk-demo

thank you very much

**Comment by life888888** [comment]
開箱即用 , 我建立了 https://github.com/life888888/asciidoctor-pdf-cjk-ext
你只需要下載 https://github.com/life888888/asciidoctor-pdf-cjk-ext/releases/download/v0.1.0/pdf-ext-notosans-cjk-sc.jar 
到你的  AsciidocFX/lib 目錄下

修改 `AsciidocFX/conf/asciidoctor_pdf.json`
和    `/home/yourUserName/.asciidocfx-1.7.6/asciidoctor_pdf.json`

```
{
    "backend": "pdf",
    "jsPlatform": "Asciidoctorj",
    "safe": "unsafe",
    "header_footer": true,
    "converter": "ASCIIDOCTOR",
    "attributes": {
        "pdf-fontsdir": "uri:classloader:/data/fonts;GEM_FONTS_DIR;",
        "pdf-themesdir": "uri:classloader:/data/themes",
        "pdf-theme": "default-ext-notosans-cjk-sc",
        "showtitle": "true",
        "allow-uri-read": "true",
        "source-highlighter": "rouge",
        "icons": "font",
        "imagesdir": "images",
        "experimental": "true"
    }
}
```

然後就能產生包含中文的 PDF。
theme 可以選擇 default-ext-notosans-cjk-sc, default-notosans-cjk-sc, notosans-cjk-sc
你也可以下載  pdf-ext-notosansmono-cjk-sc.jar , pdf-ext-notoserif-cjk-sc.jar 會有 Noto Sans Mono CJK, Noto Serif CJK 字型

**Comment by xp12047** [comment]
> 開箱即用 , 我建立了 https://github.com/life888888/asciidoctor-pdf-cjk-ext 你只需要下載 https://github.com/life888888/asciidoctor-pdf-cjk-ext/releases/download/v0.1.0/pdf-ext-notosans-cjk-sc.jar 到你的 AsciidocFX/lib 目錄下
> 
> 修改 `AsciidocFX/conf/asciidoctor_pdf.json` 和 `/home/yourUserName/.asciidocfx-1.7.6/asciidoctor_pdf.json`
> 
> ```
> {
>     "backend": "pdf",
>     "jsPlatform": "Asciidoctorj",
>     "safe": "unsafe",
>     "header_footer": true,
>     "converter": "ASCIIDOCTOR",
>     "attributes": {
>         "pdf-fontsdir": "uri:classloader:/data/fonts;GEM_FONTS_DIR;",
>         "pdf-themesdir": "uri:classloader:/data/themes",
>         "pdf-theme": "default-ext-notosans-cjk-sc",
>         "showtitle": "true",
>         "allow-uri-read": "true",
>         "source-highlighter": "rouge",
>         "icons": "font",
>         "imagesdir": "images",
>         "experimental": "true"
>     }
> }
> ```
> 
> 然後就能產生包含中文的 PDF。
> 
> theme 可以選擇 default-ext-notosans-cjk-sc, default-notosans-cjk-sc, notosans-cjk-sc。
> 
> 你也可以下載 pdf-ext-notosansmono-cjk-sc.jar , pdf-ext-notoserif-cjk-sc.jar 會有 Noto Sans Mono CJK, Noto Serif CJK 字型
> 
> 重點是 支援 4 種 Style : 一般 Regular, 粗體 Bold, 斜體 Italic, 粗斜體 BoldItalic
> 
> 還包含了一些特殊的 Unicode 符號以及 Emoji Fonts
> 
> 每個 jar 包含 3種 , PDF Theme : default-ext-notosans-cjk-sc , default-notosans-cjk-sc, notosans-cjk-sc
> 
> ![themes-diff](https://user-images.githubusercontent.com/101442875/195976766-d8e596d7-c834-4c9d-b49f-c8fc2abc2a58.png)
> 
> 測試用的 PDF-CJK-TEST_TW.adoc
> 
> [PDF-CJK-TEST_TW.adoc.txt](https://github.com/asciidocfx/AsciidocFX/files/9791549/PDF-CJK-TEST_TW.adoc.txt)

谢谢😊
