### ISSUE TITLE
PlantUML with Math (jlatexmath) is not working

### ISSUE THREAD

**Issue by alonbl** [asciidocfx/AsciidocFX#556]
Hi,

When trying to use plantuml with math, the render does not work.

Example:

```
# My Title
Alon Bar-Lev <alon.barlev@gmail.com>

[plantuml]
....
@startmath
f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
@endmath
....
```

When building this with `asciidoctorj-2.5.5` it rendered correctly.

I can see that `AsciidocFX\lib\asciidoctorj-diagram-plantuml-1.2022.5.jar` exists and embeds `jlatexmath-1.0.7.jar`.
And `asciidoctorj-2.5.5/lib/asciidoctorj-diagram-plantuml-1.2022.5.jar` are the same.

So I not sure why it does not work AsciidocFX and does work with asciidoctorj.

Maybe there is a conflict between this and `AsciidocFX\conf\public\mathjax\MathJax.js` setting, not sure.

Version: 1.7.5
OS: Windows

Thanks!

**Comment by rahmanusta** [comment]
Hi,

Required to add jlatexmath dependency to AsciidocFX due to reflective access. I reuploaded the release. Can you reinstall v1.7.5 and see if it works ? https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.5

**Comment by alonbl** [comment]
Working,
Thanks!
