### ISSUE TITLE
Title is missing in Preview and PDF

### ISSUE THREAD

**Issue by gillesB** [asciidocfx/AsciidocFX#557]
Hello,

the title is missing in the preview pane and in the generated PDF.
(I have not tested the other export functionality.)

Steps to reproduce:

* Delete .AsciidocFX-1.7.5 in the user folder
* (Download and) open Version 1.7.5 (29.07.2022)
* Do not import settings
* Copy the content from the `Support.adoc` to the `new` tab
* Remove the first `=`

This results in the following:

![grafik](https://user-images.githubusercontent.com/1679281/182621542-30e0625b-7fcd-4bbe-b7c3-d344b7180c9e.png)

I do not have a bug fix yet, but the problem seems to be that the used `Attributes` are somehow faulty.
E.g.: In `AsciidocAsciidoctorjConverter` if one replaces

```Java
Attributes attributes = configBean.getAsciiDocAttributes(document.getAttributes());
attributes.setAttribute("preview", true);
```

with 

```Java
AttributesBuilder attributesBuilder = Attributes.builder();
attributesBuilder.showTitle(true);
Attributes attributes = attributesBuilder.build();
```

the title shows up again.

As said this is not a bugfix, as the attributes from the preferences are ignored.

**Comment by rahmanusta** [comment]
Hi @gillesB, I updated the v1.7.5, can you reinstall and check it ? https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.5

**Comment by gillesB** [comment]
Hello,

the title appears now in the preview, but unfortunately not in the PDF
creation.
The appended PDF was created as described in the OP.

**Comment by gillesB** [comment]
[test.pdf](https://github.com/asciidocfx/AsciidocFX/files/9284723/test.pdf)

**Comment by rahmanusta** [comment]
I missed the showtitle attribute to default config, but it can be added to document anytime. New update includes showtitle for PDF by default

**Comment by gillesB** [comment]
Great it works now with a fresh install. Thank you.
