### ISSUE TITLE
ifdef only works in preview with attributes defined in the document header

### ISSUE THREAD

**Issue by a-worsley** [asciidocfx/AsciidocFX#560]
The following works as expected when compiled with AsciiDoctor. But the AsciiDocFX previewer only displays the test inside the var-1 conditional block (var-2 conditional block does not get displayed).

```
= AsciiDocFX Bug
// var-1 is in the document header
:var-1:

// var-2 is not in the document header
:var-2:

ifdef::var-1[]
var-1 is included
endif::[]

ifdef::var-2[]
var-2 is included...or at least it should be
endif::[]
```

**Comment by rahmanusta** [comment]
Hi, thanks for reporting. Version 1.7.8 should fix the issue: https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.7.8

**Comment by a-worsley** [comment]
Seems to work now, thanks!
