### ISSUE TITLE
Feature Request: Support for Nested Tables

### ISSUE THREAD

**Issue by mach-wkl** [asciidocfx/AsciidocFX#561]
A Coworker needs to use Nested Tables as documented in https://docs.asciidoctor.org/asciidoc/latest/tables/nested/ - there seems to be no support for this in AsciidocFX yet.

**Comment by rahmanusta** [comment]
It seems working, what version do you use ?

<img width="989" alt="image" src="https://user-images.githubusercontent.com/1158804/189099890-a5d24201-88fa-450e-8c46-780639ee2c2a.png">
