### ISSUE TITLE
Hello, How to center the title

### ISSUE THREAD

**Issue by xp12047** [asciidocfx/AsciidocFX#562]
I want to center the # paragraph.  But use [.text-center] # Paragraph to be centered.  
no effect

**Comment by rahmanusta** [comment]
It should work for only HTML output. For PDF you should look into PDF themeing. https://docs.asciidoctor.org/pdf-converter/latest/theme/

**Comment by xp12047** [comment]
> 它应该只适用于 HTML 输出。
> 
> <img alt="图片" width="989" src="https://user-images.githubusercontent.com/1158804/189748700-e80085aa-b428-4959-ab94-4649d4096aa5.png">
> 
> 对于 PDF，您应该查看 PDF 主题。https://docs.asciidoctor.org/pdf-converter/latest/theme/

thank you very much!😊
