### ISSUE TITLE
Brew install fails - Error: SHA256 mismatch

### ISSUE THREAD

**Issue by robcarruthers** [asciidocfx/AsciidocFX#568]
``` shell
❯ brew install --cask asciidocfx
==> Downloading https://github.com/asciidocfx/AsciidocFX/releases/download/v1.7.8/AsciidocFX_Mac_M1.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/19916900/553dbf30-84d8-4a81-ae19-bc4596038df6?X-Amz-
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: f7e2bb8c6e91a8afee18225d3032fbe3ac09cb48ffb59ce82829f0d7984c298d
  Actual: ee8c74c1776fe7b5367c69f0aebb3cebb64e6642ff8443ff9f07ae126160f51d
    File: /Users/rob/Library/Caches/Homebrew/downloads/fe09a6aa2e5cb2a14aa856ac6f75d4df2e5766083d9fec30392bf657f434c370--AsciidocFX_Mac_M1.dmg
To retry an incomplete download, remove the file above.
```

**Comment by Traufvihal** [comment]
I had the same error, while not a fix I've managed to bypass this by running `brew edit --cask asciidocfx` and updating the arm version with the sha from AsciidocFX 1.7.8 (the actual value in your logs). Anyway, the SHA codes for any version can be found here: https://github.com/asciidocfx/AsciidocFX/releases
However after doing this, you face this issue https://github.com/asciidocfx/AsciidocFX/issues/533
In my case I cannot mess around with Gatekeeper so I need some alternative to avoid this.

**Comment by rahmanusta** [comment]
Can you install the latest release?
