### ISSUE TITLE
Equations and Formulas (STEM) problem 

### ISSUE THREAD

**Issue by yapbenzet** [asciidocfx/AsciidocFX#574]
stem in asciidoc files: 
stem:[sqrt(4) = 2]
display as this : 
\$sqrt(4) = 2\$

There is a problem with inline Latex : 

latexmath:[C = \alpha + \beta Y^{\gamma} + \epsilon]

this is display as : 
\(C = \alpha + \beta Y^{\gamma} + \epsilon\)

Also there is a problem with 

[asciimath] 
++++
[int_0^1 x^n dx = \frac{1}{n+1}]
++++

**Comment by rahmanusta** [comment]
Hello, thank for reporting the issues. The issues has been resolved in https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.8.2
