### ISSUE TITLE
Enable move any tab page

### ISSUE THREAD

**Issue by manueljordan** [asciidocfx/AsciidocFX#577]
So far until 1.8.3 if is opened some files - where each one is available in its own tab page - is **not** possible move a specific tab page to a specific position.

For example is exists the following files opened and sorted as:

```
aaa bbb ddd ccc
```

is not possible either select `ddd` and move it to the right or select `ccc` and move it to the left. Currently I must close `ddd` and open again to see it as the latest tab page opened.

**Comment by manueljordan** [comment]
Should be closed with https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.8.5 ?

**Comment by rahmanusta** [comment]
Yes, it should also be available

**Comment by manueljordan** [comment]
Yes. I've confirmed it works. Huge Thanks for the support.
