### ISSUE TITLE
declaring images with image:: is not running

### ISSUE THREAD

**Issue by styopy** [asciidocfx/AsciidocFX#580]
you can not declare images how described. it seems to be an older issue. I used version 1.7.x and there it was running without problems.

**Comment by rahmanusta** [comment]
Can you share soma details?

What version do you use?
What Operating System?
and some documents/screenshots of the problem?

**Comment by rahmanusta** [comment]
default :images_dir: attribute is images, so you don't need to set images. Btw, You can override it to any value.
