### ISSUE TITLE
Possible bug for "Find and Replace Text" Shortcut

### ISSUE THREAD

**Issue by manueljordan** [asciidocfx/AsciidocFX#585]
At the [Some Shortcuts](https://github.com/asciidocfx/AsciidocFX#some-shortcuts) section appears the following item:

```
Ctrl+F , Ctrl+F   Find and Replace Text
```

Well it does not work, with the first `Ctrl+F` is opened the _Search for_, but for the second time for `Ctrl+F` nothing happens. Therefore to replace must be done click in the `+` icon/button. 

I have this experience in Linux and Windows with 1.8.3, therefore I am assuming the shortcut is incorrect.

**Comment by rahmanusta** [comment]
You can see and customize editor shortcuts in Settings.

https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.8.6

**Comment by manueljordan** [comment]
Huge thanks, let me confirm it!
