### ISSUE TITLE
1.8.5 breaks includes with substitution in path

### ISSUE THREAD

**Issue by Nuck-TH** [asciidocfx/AsciidocFX#591]
In 1.8.5 includes with substitutions in path doesn't work:
![1 8 5_bug](https://user-images.githubusercontent.com/9101828/235998396-03bb6cae-52b4-42a0-951e-0603212f6885.png)
Works as expected in 1.8.4:
![1 8 4_works](https://user-images.githubusercontent.com/9101828/235998553-7e008221-2bd3-4e1e-b89c-906b4b2f9fa3.png)

**Comment by rahmanusta** [comment]
Hi,

Please reinstall it https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.8.5

**Comment by Nuck-TH** [comment]
Seems to be working now, thanks.
