### ISSUE TITLE
Enable Ctrl + F support in the Preview views

### ISSUE THREAD

**Issue by manueljordan** [asciidocfx/AsciidocFX#593]
Hello - so far to 1.8.5 when either `Preview` or `Preview Only` is opened, it renders the `.adoc` file as expected. If this file has more of 500 or 1000 lines (it could be even less of 500 lines), it does not match the same position. I mean, if in the `.adoc` file the cursor is on line 500 when is rendered: the content shown can be located normally either in the top or bottom - and not in the line 500; same behavior if some content is selected in the line 500 in the `.adoc`.

Is possible add `Ctrl` + `F` in the rendered tab? to let me copy some content of the line 500 and use it in the `Preview` view and go to there directly.

Thanks for your understanding

**Comment by rahmanusta** [comment]
Here you go, search function has been implemented.

https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.8.6

**Comment by manueljordan** [comment]
Huge thanks!
