### ISSUE TITLE
is AsciiDocFX still active?

### ISSUE THREAD

**Issue by FiSHYsolutions** [asciidocfx/AsciidocFX#597]
i was wondering if this project is still active. i discovered adoc for me, but there is a huge lack of useable wysiwyg-editors in my opinion. AsciiDocFX seems to close the gap a little bit, but obviously it has a lot of problems (including images is not a strength for example) and also it has a shitload of open issues (194 right now). i downloaded 279 MB to get v1.8.5 and it's absolutely unuseable. should i be patient or should i move on? thx a lot.

**Comment by rahmanusta** [comment]
I don't think you have the right to reproach. I'm developing AsciidocFX for my own needs and it's working right now. You are free to send pull requests to make it better or you may consider investing on the project.
