### ISSUE TITLE
Request : Add UI Text Size Config Setting.

### ISSUE THREAD

**Issue by life888888** [asciidocfx/AsciidocFX#599]
Is it possible to increase and adjust the text size of the tree UI on the left and the text size set by the ITEM of the TAB on the right?

Because even with a large screen, the menu text cannot be resized to a larger size. Editor can be resized, but the setting menu of the right TAB cannot be resized.
![screen](https://github.com/asciidocfx/AsciidocFX/assets/101442875/12b91ba3-0cb8-4543-a79e-05945d6a2ddc)

**Comment by rahmanusta** [comment]
You can configure them in css files located under conf/themes folder.

**Comment by life888888** [comment]
> You can configure them in css files located under conf/themes folder.

Can you please provide some more tips? Do I need to create a new css file or modify the existing css file (conf/themes/Shared.css & conf/themes/default/Style.css)? If I want to change the left What keywords should be modified to make the "workdir" of Tab or the directory tree inside become larger font size ?

**Comment by rahmanusta** [comment]
You can edit the existing ones or you can create your own theme. You can check the JavaFX css guide in here https://docs.oracle.com/javafx/2/api/javafx/scene/doc-files/cssref.html

**Comment by life888888** [comment]
I will try again, thank you.

**Comment by life888888** [comment]
# Update
## Before

![screen](https://github.com/asciidocfx/AsciidocFX/assets/101442875/007df3f9-a636-4709-9859-60d331785f38)

## After

![screen_after](https://github.com/asciidocfx/AsciidocFX/assets/101442875/832b46e9-241e-44f4-b405-5a1da3daae72)

add `-fx-font-size: 24px;`  to some block

AsciidocFX/conf/themes/Shared.css

[Shared.css.txt](https://github.com/asciidocfx/AsciidocFX/files/12911885/Shared.css.txt)

AsciidocFX/conf/themes/default/Style.css

[Style.css.txt](https://github.com/asciidocfx/AsciidocFX/files/12911880/Style.css.txt)

1. Due to poor eyesight, I changed to a larger screen, but the menu, tree structure, Tab and Settings text and labels in the AsciidocFX panel still look too small.
2. After adjusting the css file under the theme according to the suggestions, the text and labels in the menu, tree structure, Tab and Settings have all become larger.
