### ISSUE TITLE
<shift> + <Pos1> and <shift> + <End> not working in 1.8.6

### ISSUE THREAD

**Issue by pschlein** [asciidocfx/AsciidocFX#609]
With the release of version 1.8.6 the combination ```<shift> + <pos1>``` and ```<shift> + <end>``` to select either the whole line before or after the cursor does not work anymore (with a german keyboard) . With 1.8.5 that worked.

Single key ```<pos1>``` or ```<end>``` work, but not the selection of the remaining line.

Thanks

**Comment by rahmanusta** [comment]
You should be able to configure it Shortcut settings. "Select to line start" and "Select to line end"

**Comment by pschlein** [comment]
Thanks for the hint...
