### ISSUE TITLE
Undo not working on Mac

### ISSUE THREAD

**Issue by sbaechler** [asciidocfx/AsciidocFX#61]
Following up on a chat on Gitter.

When I press CMD-Z or CTRL-Z nothing happens. I expect the editor to undo the last action.

I'm using version 1.3.4 on a Mac, Yosemite. My Java version is 8 Update 25.

**Comment by rahmanusta** [comment]
Hi @sbaechler . I tried some works in this https://github.com/asciidocfx/AsciidocFX/tree/ctrlyzfix branch. Can you try this ?

**Comment by sbaechler** [comment]
Sorry, no change. Now only ctrl+y and ctrl+z work, but undo und redo are still swapped. So ctrl+y is undo and ctrl+z is redo.
The log message appears so the new code is doing something.

**Comment by rahmanusta** [comment]
Thanks @sbaechler . I disabled all shortcuts except ctrl+y and ctrl+y. Can you try another fix proposal from https://github.com/asciidocfx/AsciidocFX/tree/ctrlyzfix

**Comment by sbaechler** [comment]
This time, nothing works. I tried CMD and CTRL Y and Z.

**Comment by rahmanusta** [comment]
Can we make a teamviewer session with you? @sbaechler

**Comment by sbaechler** [comment]
It looks like this is a bug in JavaFX. Almost two years old!
http://stackoverflow.com/questions/17014175/how-to-detect-if-a-users-keyboard-is-in-azerty-in-java

**Comment by sbaechler** [comment]
The new link to the JDK bug: https://bugs.openjdk.java.net/browse/JDK-8087915. 
It is now targeted to JDK9 with the possibility to be backported to 8 eventually.
