### ISSUE TITLE
Asciidoc FX v1.8.6 > Include Directive > Include by Tagged Region is nonfunctional

### ISSUE THREAD

**Issue by lopsotronic** [asciidocfx/AsciidocFX#615]
The following markup inside of a file `../DMC/DMC-DEMO-000-10-00-01A-280A-A.adoc`

> `include::../CIR/DMC-DEMO-000-00-00-01A-0A4A-A.adoc[tag=Flammable]

Referencing the following include target file `../CIR/DMC-DEMO-000-00-00-01A-0A4A-A.adoc`

> = List of Warnings - Common information repository
> 
> // tag::HighVoltage[]
> WARNING: High voltage kills! ZAP    
> // end::HighVoltage[]
> 
> // tag::Flammable[]
> WARNING: Fuel may cause burning to death
> // end::Flammable[]
> 
> // tag::Detergent[]
> WARNING: Do not get detergent into your eyes. If it gets into your eyes, wash them immediately in clean warm water.
> // end::Detergent[]

Does not reference tag::Flammable, but instead returns the entire contents of the include file

The same markup works on vanilla Asciidoctor.js in Visual Studio Code, and I thought AsciidocFX used the JS implementation, but I am very open to correction.

**Comment by lopsotronic** [comment]
Also confirmed functional on AsciidocFX185 and 179

**Comment by rahmanusta** [comment]
It is in progress to resolve that issue, thanks for reporting

**Comment by rahmanusta** [comment]
Hi, you can see the fix in https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.8.7
