### ISSUE TITLE
AsciidoxFX Source Code Block Include Content by Line Ranges NOT WORKING

### ISSUE THREAD

**Issue by life888888** [asciidocfx/AsciidocFX#618]
# AsciidoxFX Source Code Block Include Content by Line Ranges NOT WORKING

AsciidoxFX Source Code Block Include Content by Line Ranges NOT WORKING

## AsciidocFX Test Version

AsciidocFX 1.8.6 Deb

## Test Adoc

**Source Code Block Include Content by Line Ranges**

```adoc
[source,java]  
.HelloWorld.java
---- 
include::code/HelloWorld.java[lines=3..5]
----
```

I want include `HelloWorld.java` only line 3 to line 5.

But AsciidocFX , include full contents of  `HelloWorld.java`.

### Test Result

AsciidocFX preview or save to html is same result : include full contents of  `HelloWorld.java`.

**FAIL: include full content of file.**

![asciidocfx-preview](https://github.com/asciidocfx/AsciidocFX/assets/101442875/d41fd0fe-45c7-453d-a64c-5a9a633bfdac)

## Other Test - A
sciidoctor and AsciidoctorJ

I also test the adoc file using :

- Docker image `asciidoctor/docker-asciidoctor` (Asciidoctor 2.0.20)  
- AsciidoctorJ 2.5.10 (same version as AsciidocFX 1.8.6) 
- AsciidoctorJ 3.0.0-alpha.2

It OK , only include `HelloWorld.java` only line 3 to line 5.

## My Test Code

```shell
.
├── code
│   ├── HelloWorld.java
│   └── index.html
├── demo-code-include.adoc
└── docinfo.html
```

**demo-code-include.adoc**

```adoc
= Demo Source Codes Include
:imagesdir: img
:source-highlighter: rouge
:docinfo: shared

Demo Source Codes Include

'''

[source,java]  
.HelloWorld.java
---- 
include::code/HelloWorld.java[lines=3..5]
----


[%linenums,java]  
.HelloWorld.java - show line numbers
---- 
include::code/HelloWorld.java[lines=3..5]
----

'''

[source,html]  
.index.html
---- 
include::code/index.html[lines=8..10]
----

[%linenums,html]  
.index.html - show line numbers
---- 
include::code/index.html[lines=8..10]
----


<<<
```

**code/index.html**

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Hello World</title>
</head>
 
<body>
  <div>Hello World</div>
</body>
 
</html>
```

**code/HelloWorld.java**

```java
public class HelloWorld {

    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
    
}
```

**docinfo.html**
```html
<style>
pre.rouge .hll {
  background-color: #ffc;
  display: block;
}
pre.rouge .hll * {
  background-color: initial;
}
</style>
```

## Other Test Code - Asciidoctor and AsciidoctorJ

```shell
# Use Asciidoctor Docker
$ docker run --rm -u $(id -u):$(id -g) -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor -o demo-code-include-docker-asciidoctor-2.0.20.html demo-code-include.adoc 

# Use asciidoctorj-2.5.10
$ TOOLS/asciidoctorj-2.5.10/bin/asciidoctorj -o demo-code-include-asciidoctorj-2.5.10.html demo-code-include.adoc 

# Use asciidoctorj-3.0.0-alpha.2-SNAPSHOT
$ TOOLS/asciidoctorj-3.0.0-alpha.2-SNAPSHOT/bin/asciidoctorj -o demo-code-include-asciidoctorj-3.0.0-alpha.2.html demo-code-include.adoc 
```

**Test OK**

Only include  Content by Line Ranges

![asciidoctorj-2 5 10](https://github.com/asciidocfx/AsciidocFX/assets/101442875/99d4f3ef-0f63-4eec-9e6c-d60460b1477e)

**Comment by life888888** [comment]
Using AsciidocFX 1.8.5 works as expected.

However, using AsciidocFX 1.8.6 results in nonfunctional behavior.

**Comment by rahmanusta** [comment]
Thanks for reporting, it is in progress to resolve that issue

**Comment by rahmanusta** [comment]
Hi, you can see the fix in https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.8.7

**Comment by life888888** [comment]
Test OK.
