### ISSUE TITLE
Add about AsciidocFX to show version number

### ISSUE THREAD

**Issue by indigo423** [asciidocfx/AsciidocFX#62]
It is hard to find the version number. I would make sense to add a "About AsciidocFX" in at the menu bar on MacOSX.

**Comment by rahmanusta** [comment]
Yes, it is already here.

![image](https://cloud.githubusercontent.com/assets/1158804/6805046/a5d31cc2-d249-11e4-8a0a-4cc49de0a61f.png)

**Comment by indigo423** [comment]
Thx for the quick reply --> suggestion a "?" instead of "..."

**Comment by rahmanusta** [comment]
I'm not sure for "?". @hakdogan what do you think?

**Comment by hakdogan** [comment]
I think About AsciidocFX phrase more suitable for the general use in Mac OS X @indigo423 @rahmanusta

**Comment by rahmanusta** [comment]
Ah sorry :) I attached @hakdogan mistakenly :)

@ozlerhakan  What do you think for "?" instead of three dash ?

**Comment by ozlerhakan** [comment]
as @hakdogan hocam mentioned, we may change the name of the "About" part to clarify about what it really is, Or we can only mention the version number as a disabled menu instead of letting users to click the About section.

About the question, I dont think that ? can point the rest of the AFX services. we can find another icon instead?

**Comment by indigo423** [comment]
Thank you guys taking this issue serious, I was not sure, maybe it's just me don't understanding the three dashes and not finding the version number :)

**Comment by rahmanusta** [comment]
Thanks @indigo423 :) Maybe you can pick an icon from http://fortawesome.github.io/Font-Awesome/icons/

**Comment by rahmanusta** [comment]
Thanks @indigo423 :) Maybe you can pick an icon from http://fortawesome.github.io/Font-Awesome/icons/

**Comment by indigo423** [comment]
One of the info icons could make sense: http://fortawesome.github.io/Font-Awesome/icon/info/ or http://fortawesome.github.io/Font-Awesome/icon/info-circle/

**Comment by rahmanusta** [comment]
They are good candidates. But this menu is not about "info" totally.

**Comment by rahmanusta** [comment]
I will close this issue, we can chat on gitter if any extra words.
