### ISSUE TITLE
UI: regression: Pg-up not functional in edit window of ver. 1.8.6, while ok in ver 1.8.5 [ solved ].

### ISSUE THREAD

**Issue by newbie-02** [asciidocfx/AsciidocFX#620]
[ edit 2 ] Can be changed in 'Settings - Shortcut Settings - Page Up' from 'Alt+Page Up'  
to 'Page Up', caution, I'm not aware which other functionalities may be harmed. [ /edit ]  
  
[ edit ] workaround: 'alt-Pg-up' works [ /edit ]  
  
'Header only' issue, after updating to 1.8.6 ( urged by the frequent pop-ups )  
I experienced Pg-up key no effect in edit window ( while Pg-down works and both  
work in preview pane ).  
Reverted to ver. 1.8.5 by renaming /opt/AsciidocFX directory and copying unzipped  
tar download to /opt/AsciidocFX, issue gone. ( Kali ( debian ) Linux on Intel Xeon  
hardware ).

**Comment by rahmanusta** [comment]
Hi, AsciidocFX has moved to different shortcut management which is configurable. You can see default shortcuts on Settings > Shortcut Settings and customize them.
