### ISSUE TITLE
GUI blocked, no editing possible

### ISSUE THREAD

**Issue by ccossou** [asciidocfx/AsciidocFX#623]
Hi, 
In the editor, if I select some text, the only key that then work are "Delete" or "Backspace" . If I start to write something it doesn't work. I assume this is not how this is supposed to work, but maybe I'm wrong. But this is how it works on any other editors I've ever used.

[edit]
Just an edit, I experienced a similar issue just a bit after, no selection was done, and I still couldn't type any text in the window, no info was visible in the log section on the GUI. Only solution was to close the GUI. 

After lauching, I could overwrite selected text, so I changed the issue title to reflect that.

I've started the GUI in command line to try and get some error message I can feed here. 

When this happens, I can save the file proving that the UI is not completely frozen, and I can type in other windows than AsciidocFX. 
[/edit]

On the same note, the middle click copy/paste of Linux doesn't work. 

I'm on Ubuntu 22.04.3 LTS, Using the latest .deb file of AsciidocFX 1.8.7.

**Comment by ccossou** [comment]
I've made a video to showcase the issue. 
https://github.com/asciidocfx/AsciidocFX/assets/3242621/642a3f62-445c-4e62-8865-7ebd8ea9f4b4

Note that when I switch to the file that doesn't work, I type but nothing happen except the cursor blinking. 

The bug dissapear after I press on "Delete" after selecting the text "background". But before that "delete" press, No typing works, wether a text is selected or not, on that panel. The unsaved text meanline, correctly works. 

Hope it helps,

**Comment by rahmanusta** [comment]
Hi, how frequent do you face with the problem?
Does it happen only in one file or in some other files as well?
Does it fix when you close and reopen the file?

**Comment by ccossou** [comment]
I experience the issue 3 times today, and my day is not over yet. I would say approx. once per day. 
I happens with any file as far as I can tell. I haven't tried to close/reopen the file, as I just noticed as I filled this issue that I still could type for another file. 
I wonder if this could be due to something being activated without me noticing. I know that in Inkscape for instance, when you start to type the code for an utf8 character, typing is interrupter and you type the utf8 code instead. But I couldn't notice anything of that sort in that situation. 

However, it may (or may not) be correlated with column editing. At least this morning when this occured, I used complex shortcuts, like Ctrl+Shift+Alt for column edition. Maybe there's a link but I couldn't find a reliable way to reproduce the error yet.

**Comment by ccossou** [comment]
Just had the issue again, without typing any weird shortcuts. And closing/reopening the file solved the issue.

**Comment by rahmanusta** [comment]
<img width="657" alt="image" src="https://github.com/asciidocfx/AsciidocFX/assets/1158804/78a1211f-66df-4584-bda6-72e3c1209aee">

I noticed the key events on development and build behaves differently, and it causes some issues.
You can disable custom shortcut handler, and it should work as expected.

**Comment by rahmanusta** [comment]
I've just published the new version.  I hope it resolves the issue https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.8.8
Btw. If it repeates again, pressing Esc should resolve the key handler back to normal.

**Comment by ccossou** [comment]
I experienced the issue again with 1.8.8, but using "Esc" solved the issue and I could type again.

**Comment by rahmanusta** [comment]
Please test with https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.8.9 . I hope it resolves the key event issues
