### ISSUE TITLE
Keystrokes missed using editor in Windows (AsciidocFX version 1.8.8)

### ISSUE THREAD

**Issue by 3rady** [asciidocfx/AsciidocFX#627]
The editor sometimes does not register keystrokes when entering Markdown.  I am seeing a frequency of perhaps 1 out of 100 keystrokes being missed, maybe more.  The result is text with missing characters.  I haven't been able to detect any sort of pattern to the failure, it seems to happen if I'm typing fast or slow.  I did not notice this behavior in previous versions.

**Comment by rahmanusta** [comment]
Please test with https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.8.9 . I hope it resolves the key event issues

**Comment by 3rady** [comment]
I have used version 1.8.9 for a few hours and not had any issues with the key events.  Thank you for fixing it!
