### ISSUE TITLE
Shift-home and shift-end key combinations not working in Windows editor (AsciidocFX version 1.8.8)

### ISSUE THREAD

**Issue by 3rady** [asciidocfx/AsciidocFX#628]
While using the editor, holding down the shift key and pressing the home or end keys do not highlight text in the current line to the beginning or end of the line (which is the normal behavior for this key combination).  I had not noticed this issue prior to version 1.8.8 of the Windows build.

**Comment by rahmanusta** [comment]
Key handling mechanism has changed. There is default settings by ace and also you can configure it on Settings > Shortcut Settings.

Search "Select to" and you should see the default commands. You can modify the ones that you want. Let me know if it stills doesn't work. If it doesn't work, please enable debugging in the shortcut settings, and share the log output.

**Comment by 3rady** [comment]
I was able to modify the settings to my liking, thank you.

I would recommend that the default settings be the following, at least in the Windows release:

* _Select to line end_ = _Shift+End_
* _Select to line start_ = _Shift+Home_

Maybe it's just me, but I use those keyboard shortcuts *all the time*.  I didn't realize how much I use them until AsciidocFX stopped responding to them; it was really tripping me up!  I don't recall any other Windows programs using different shortcuts for those actions, I think they are pretty universal.

Thanks for all your work on this project.
