### ISSUE TITLE
AsciidocFX ignores comments when including files

### ISSUE THREAD

**Issue by rmx-it** [asciidocfx/AsciidocFX#64]
The following line should be ignored instead of trying to import preface.adoc:
````asciidoc
// include::preface.adoc[]
````

**Comment by ozlerhakan** [comment]
Hi again @rmx-it ,

For now, just use a comment block which will skip the specified lines:

```
////
 include::preface.adoc[]
////
```

**Comment by rmx-it** [comment]
Yes.
Thats ok.
