### ISSUE TITLE
The following test.adoc produces an error

### ISSUE THREAD

**Issue by rmx-it** [asciidocfx/AsciidocFX#65]
Here an example to generate an error when producing docbook .xml or .pdf output:

````asciidoc
= Book Title
:Author: xxx yyy
:Email: <xxx@yyy.com>
:doctype: book
:numbered:
:toc: left
:toclevels: 3
:toc-title: Contents
:sectanchors:
:icons: font
:linkcss:
:experimental:
:source-language: shell
:leveloffset: 0

== Foo

* This
* Example
* would `/xxx/${XXX}/.xxx.*`
* work.

* This Example does `/xxx/${XXX}/.xxx.*` not `/xxx/${XXX}/.xxx.*` work!
````

As it seems the two stars in one line do trigger the problem.

The following xml code gets generated during docbook generation:
````xml
<listitem>
<simpara>This Example does <literal>/xxx/${XXX}/.xxx.<emphasis role="strong"></literal> not <literal>/xxx/${XXX}/.xxx.</emphasis></literal> work!</simpara>
</listitem>
</itemizedlist>
````
The `<emphasis role="strong">` part generates the error.

**Comment by ozlerhakan** [comment]
Hi @rmx-it ,

In such cases, you need to use backslash ( '\' ) in order to solve format conflicts.

```
* This Example does `/xxx/${XXX}/.xxx.\*` not `/xxx/${XXX}/.xxx.*` work!
```

**Comment by rmx-it** [comment]
Maybe,
but at least AsciidocFX should not silently produce no output and leave me alone searching the culprit.
But no.
Verbatim cites should exactly that - verbatime cites.
For technical documents its quite common to copy-paste code and console snipplets.
I've choosen asciidoc because until now I hat to do the least conversions/adaptions to the sources
compared to Latex, Markdown, ...

So, at least AsciidocFX should print an hint in which line an error occured,
ideally AsciidocFX would do the masking itself if necessary.

**Comment by ozlerhakan** [comment]
Actually, what you see in the preview section is what you get, so AFX's preview section works as a debugger as well, you normally must see the reason from that part. For example, when you type the aforementioned line what do you see in the preview? Apparently you do not see the asterisks. This also relates to users' knowledge about the asciidoctor. Here is the documentation about the usage of [backslash](http://asciidoctor.org/docs/user-manual/#preventing-substitutions) that may help you digest.
Nevertheless, we will keep this in mind, thanks.
