### ISSUE TITLE
question / enhancement proposal, continue with previous level of structuring

### ISSUE THREAD

**Issue by newbie-02** [asciidocfx/AsciidocFX#651]
An example: if someone wants an output like: 
```
* Topic 
  some text, 
  ** Subtopic 1 
    some text, 
  ** Subtopic 2 
    some text, 
  continue with some text to Topic, e.g. conclusion, 
* Topic 2 
  some text, 
```
I didn't yet find a way to format the indented part `  continue with some text to Topic, e.g. conclusion,` in AsciidocFX, and in numbered lists keep the counting. 
Likely I overlooked something, thanks for any hint, or it could be a good idea to add an option for such???

**Comment by rahmanusta** [comment]
That is a question related to Asciidoctor syntax. You can ask this to Asciidoctor team https://chat.asciidoctor.org/

**Comment by newbie-02** [comment]
thank you, did so, https://asciidoctor.zulipchat.com/#narrow/stream/279642-users/topic/structure.2C.20continuing.20with.20.20previous.20level.2C
