### ISSUE TITLE
performance, flow of work, system load, 

### ISSUE THREAD

**Issue by newbie-02** [asciidocfx/AsciidocFX#652]
sorry, this is a more complex question ...  and about observations and assumptions rather than knowledge. 
 
observing the fan of my computer and my 'CPU-meter' it looks that AsciidocFX is quite power intense ... 
I get the impression as if again and again the whole text is read and worked through, even if I only change one character in a word. And becomes slow in long documents. 
 
That sounds counter-intuitive to the task to be performed. 
- have a text, 
- have a cursor position in it around which we need display on screen, 
- have a list - excerpt - with formatting directives and positions from - to which they should work, 
-- first derived from the text, later can be inserted and deleted in the list when relevant changes in the text, 
- take a meaningful long part of text around cursor position, 
- format and display acc. formatting directives affecting it, 
- work in that window, 
- sliding up and down as needed, 
- take formatting info from excerpt rather than re-read the whole text, 
- change excerpt list when changing formatting directives in the text, 
- from time to time re-check or re-fresh excerpt list acc. text. 
 
Assume ... just _assume_ ... AsciidocFX doesn't work that way as of now, and assume it could have better performance, less system load?

**Comment by newbie-02** [comment]
For example: inserting 1 character in a line with no special formatting in a 400k document causes 33 seconds of about 50% CPU load and 50% mem usage on a 3.2 GHz Xeon 4-core machine with 64 GB ram. 
In my opinion, that is considerable overkill. 
I think that concepts are used here that are not important for short texts, but do not scale well when the size of the texts increases. Evtl. AsciidocFX should have a hint in documentation up to which size / complexity one could expect it to work well, and where one goes into risk / slowness.

**Comment by rahmanusta** [comment]
Too much expectations, there is no such work capacity / financial background to meet your expectations.

I use AsciidocFX with Mac which works smooth and never noticed a performance problem. I even don’t have a windows machine to check how that works on Windows.

**Comment by newbie-02** [comment]
performance: it's a matter of text length / complexity to 'see', 
aside it's a matter of wasting energy to work with ineffective concepts. 
No win machine available is a questionable base for developing multi OS software ... 
( pls. don't ask for donation again, I know you need, my contribution is finding and pinpointing shortcomings )
