### ISSUE TITLE
Size too small to read

### ISSUE THREAD

**Issue by Adil-Gourinda** [asciidocfx/AsciidocFX#657]
1 - I have a laptop "Nokia PureBook 14 Lite"
2 - I installed "Kubuntu 22.04 LTS"
3 - I installed AsciidocFX from the deban package
=> The result is that the font size of the graphical interface is too small to read

**Comment by life888888** [comment]
You can refer to this to make settings : https://github.com/asciidocfx/AsciidocFX/issues/599
