### ISSUE TITLE
Polish letters can not be inserted into editor

### ISSUE THREAD

**Issue by aartiPl** [asciidocfx/AsciidocFX#66]
AsciiDoc editor probably captures some key strokes internally, so effectively some characters can not be inserted into editor (they don't appear on screen). In my case it applies to some specific Polish letters:
ą - RightAlt + a
ę - RightAlt + e
ś - RightAlt + s
ł - RightAlt + l

It's quite critical issue as it disallows to write comfortably common texts in Polish language.

**Comment by rahmanusta** [comment]
Hi @aartiPl ;

Can you try to declare shortcuts for your need like  Altgr + } in shortcuts.yml?

https://github.com/asciidocfx/AsciidocFX/blob/master/conf/shortcuts.yml

**Comment by aartiPl** [comment]
Unfortunately when I define shortcuts like below:
  Ctrl-Alt-e: 'ę'
  Ctrl-Alt-a: 'ą'

I get wrong input in editor:
Ä™
Ä…
respectively...
 
The case is that these shortcuts are standard shortcuts for Polish letters. While it might be ok for temporary solution, I think it is not acceptable as a long term solution. I don't have to do it for any other editor - they are defined by default Polish keyboard.

I have also noticed that sometimes arrow keys also are not working, while in the same time I am able to input some text.

BTW: I think that AsciiDocFx is already great editor with big potential. Thanks for your work!

**Comment by rahmanusta** [comment]
I fixed wrong input problem, and it will available in new release.

Unfortunately JavaFx supports only qwerty layout for now. There can be possible keyboard issues. But shortcuts.yml may help us in generally.

We saw arrow problem when typing [] and left arrow. That is weird, i will debug it.

Thanks for your good opinions.

**Comment by rahmanusta** [comment]
Hey @aartiPl , Can you try latest version 1.3.6 ?

I updated ace editor version, and maybe it works without shortcut.yml changes. If it not works again, try shortcuts.yml. I fixxed the character issue. You can declare your shortcuts like below;

```
Ctrl-Alt-e: 'ę'
Ctrl-Alt-a: 'ą'
```

**Comment by rahmanusta** [comment]
Hi @aartiPl . Did you try it=?

**Comment by aartiPl** [comment]
The problem disappeared last time, but now, in the latest version has reoccurred.
In the latest version there is also no shortcuts.yml file, so no way to fix it.

Can you please advice how to fix it?
