### ISSUE TITLE
UI: wrong coloring after code block

### ISSUE THREAD

**Issue by newbie-02** [asciidocfx/AsciidocFX#660]
hi, 
 
I got used to insert 'blocks' - 'Code Snippets' between '----' marks, it works fine in keeping the formatting, e.g. indentation. 
The text in the block and the marks are shown dark violet instead of black on screen. 
 
Up from some complexity I observe that the coloring doesn't end with the blocks, see example below. 
  
The parts '5-blablabla' and '6-blablabla' are shown dark violet. Confused. 
   
Assume unwanted formatting / behavior? 
    
```
* 1-blablabla
+
----
    2-blablabla
----
+
3-blablabla
+
----
    4-blablabla
----

5-blablabla

* 6-blablabla
```
 
Workaround: It doesn't happen when i precede the blocks with '[source,]'

**Comment by rahmanusta** [comment]
These are not valid code blocks. See https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-blocks/
