### ISSUE TITLE
Custom Stylesheet/Icons

### ISSUE THREAD

**Issue by ruckc** [asciidocfx/AsciidocFX#67]
It would be nice to support custom stylesheet/icons for the preview/browser view modes.

**Comment by rahmanusta** [comment]
I think so. So what about icons? Which icons?

**Comment by ruckc** [comment]
The Admonitions primarily, there seem to be various sets of Admonitions.

Also changing colors of headers and so forth.

**Comment by arngrimur** [comment]
In asciidoctor it apears to be  possible to add custom css by adding a tag in header of document like
= My First Experience with the Dangers of Documentation
:stylesheet: mystyles.css

see http://asciidoctor.org/docs/user-manual/#styling-the-html-with-css 

A similar solution would be nice

**Comment by rahmanusta** [comment]
:stylesheet: mystyles.css
:stylesdir: 

It already supports. Try like above.

**Comment by arngrimur** [comment]
Hi!
Thanks for the answer but I can not make that work . Probably I'm doing
something wrong. My code is

file.adoc
________________________

= Proposal for a domain driven design architecture for borgen-appnode.
:stylesheet: styles.css
:stylesdir:

[apa]#Fooooo#

styles.css
______________________

.apa{
    color:red;
}


Folder content
.
├── file.adoc
└── styles.css


I might be doing something wrong here but I can not figure out what

Kind regards
arngrimur



//arngrimur

**Comment by rahmanusta** [comment]
Hi, stylesheet is changable for producing HTML output. Embedded preview is not supporting changing stylesheet yet.

**Comment by arngrimur** [comment]
Hi and thanks for the information!

Now I understand, I have to save the output as html in order to get it
working. Clicking on the Browser button in the preview does not do the
trick. The css is not included but the outputted html from AscidocFX is
correct .

Kind regards
Arngrimur Bjarnason

//arngrimur

**Comment by rahmanusta** [comment]
You are welcome @arngrimur

**Comment by rahmanusta** [comment]
@arngrimur You can change or edit default stylesheet also https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.3.7-RC5

**Comment by stallio** [comment]
Does this not work for PDF output? Only HTML?

**Comment by rahmanusta** [comment]
It is for HTML, css is not available for PDF. We are using docbook toolchain. That is editable in docbook-config and docbook folders in conf directory
