### ISSUE TITLE
Support for custom paths for embedded images

### ISSUE THREAD

**Issue by fbruch** [asciidocfx/AsciidocFX#70]
Using the Maven Plugin I have configured the `imagesdir` property and omitted this image root directory in my document's image-tags.

I won't ask you to parse a `pom.xml` or such but maybe you have an idea on where to put properties like this for a certain project or how to support this use case, otherwise.

Thanks for a great editor for a great markup language!

**Comment by rahmanusta** [comment]
Thanks @fbruch . I didnt understand your case. Can you give an example for that?

Thanks

**Comment by fbruch** [comment]
Of course, sorry, I was a little tightlipped about my use case. I have a bunch of asciidoc-files in my project which is built using Maven. The pom.xml contains the following configuration for asciidoctor:

			<plugin>
					<groupId>org.asciidoctor</groupId>
					<artifactId>asciidoctor-maven-plugin</artifactId>
					<version>1.5.2</version>
					<dependencies>
						<dependency>
							<groupId>org.asciidoctor</groupId>
							<artifactId>asciidoctorj-pdf</artifactId>
							<version>1.5.0-alpha.6</version>
						</dependency>
					</dependencies>
					<executions>
						<execution>
							<id>output-html</id>
							<phase>package</phase>
							<goals>
								<goal>process-asciidoc</goal>
							</goals>
							<configuration>
								<outputDirectory>${project.build.directory}/generated-docs/html</outputDirectory>
								<sourceHighlighter>prettify</sourceHighlighter>
								<backend>xhtml5</backend>
								<attributes>
									<linkcss>false</linkcss>
									<icons>font@</icons>
									<numbered>true@</numbered>
									<toc>left@</toc>
									<toc-title>Inhaltsverzeichnis@</toc-title>
									<imagesdir>./images</imagesdir>
									<last-update-label>false</last-update-label>
									<docVersion>${project.version}</docVersion>
								</attributes>
							</configuration>
						</execution>
						<execution>
							<id>output-pdf</id>
							<phase>package</phase>
							<goals>
								<goal>process-asciidoc</goal>
							</goals>
							<configuration>
								<outputDirectory>${project.build.directory}/generated-docs/pdf</outputDirectory>
								<sourceHighlighter>coderay</sourceHighlighter>
								<backend>pdf</backend>
								<attributes>
									<pagenums>true@</pagenums>
									<numbered>true@</numbered>
									<last-update-label>false</last-update-label>
									<docVersion>${project.version}</docVersion>
								</attributes>
							</configuration>
						</execution>
					</executions>
				</plugin>

The relevant line for my case is this

	<imagesdir>./images</imagesdir>

which defines a default image root directory for all images tags in the documents built with this Maven-POM. 

An image-tag looks like this

	image::Encoding.png[align="left"]

But the image is located here (relatively to the document's location)

	./images/Encoding.png

The feature is described here: http://asciidoctor.org/docs/user-manual/#set-the-images-directory

The AsciidocFX preview works fine if I put

	:imagesdir: images

in each and every file of my project but this "not compatible" with the project-central property inside pom.xml, you see? If it would only need to be included in the root document I would consider using this directive a feasible workaround. But as this property is not transmitted to included documents (at least when editing the parts in AsciidocFX) I would prefer "another solution" :-)

Of course, AsciidocFX does and should not know how to read Maven-POMs but maybe you see another possibility to enable rendering of images in AsciidocFX' preview using some extra configuration for a particular project(directory) or file...

**Comment by rahmanusta** [comment]
Not in pom.xml but in config.yml, we can declare global imagesdir directory. This feature will be available in further release.

**Comment by fbruch** [comment]
Good News, thank you.

**Comment by rahmanusta** [comment]
@fbruch You can change Asciidoctor attributes in RC5 (Press), please try it https://github.com/asciidocfx/AsciidocFX/releases/tag/v1.3.7-RC5

To change attributes press F4 and add imagesdir attribute to the attribute table.

**Comment by rahmanusta** [comment]
@fbruch Can you try RC6 ? https://github.com/asciidocfx/AsciidocFX#how-to-install-asciidocfx

**Comment by fbruch** [comment]
Sorry for my extra late reply. `:imagesdir:`-directive in asciidoctor-files works like a charm :-) Thank you! Good work!

**Comment by escay** [comment]
Good to know:

The setting 'imagesdir' with value 'images' should be added to the Preview Settings tab as 'Asciidoctor attributes', and not to the DocBook settings tabas 'Asciidoctor attributes'. 

Once you figure this out it works. Tested in Windows version 1.5.5.
