### ISSUE TITLE
Allow serving up *.mp4 files

### ISSUE THREAD

**Issue by checketts** [asciidocfx/AsciidocFX#72]
Including a video ie  `video::myvid.mp4[]` fails. I believe the Spring MVC needs to be updated.

Ideally I'd like to put videos in a subdirectory as well.

**Comment by rahmanusta** [comment]
This feature implemented and will be available in further release. Also, I want to say that, JavaFX webview has a limitation to show videos. It supports only, flv videos. But, there is no limitation with external browser.

**Comment by checketts** [comment]
It appears to be supported in Java 8. https://docs.oracle.com/javase/8/javafx/api/javafx/scene/media/package-summary.html Or is that list different than what the webview supports?

Also where are the build instructions? I'm interested in trying it out, as well as learning from the code when running it locally.

**Comment by rahmanusta** [comment]
@checketts media component is different than webview. webview is another story.
