### ISSUE TITLE
Word Counter.

### ISSUE THREAD

**Issue by genova88** [asciidocfx/AsciidocFX#73]
Yazılımın alt tarafına kelime sayısı ve karakter sayısı paneli gelirse çok daha faydalı olacaktır. Örnek olarak bu sitedeki sağ paneli verebiliriz. http://www.wordcounter.net/ Tabi bu yazılımda Word gibi altta ufacık yazması yeterlidir.

**Comment by rahmanusta** [comment]
This feature will be available in further release

**Comment by genova88** [comment]
Thanks :+1:

**Comment by rahmanusta** [comment]
@genova88 word counter değil ama şan character counter var. 1.3.7 tam çıkmadık word counter ekleyebiliriz.
