### ISSUE TITLE
install4j.i4jruntime cann't be found

### ISSUE THREAD

**Issue by cosyman** [asciidocfx/AsciidocFX#75]
Maven cann't find install4j.i4jruntime artifact in maven repo <http://search.maven.org/>

**Comment by rahmanusta** [comment]
Hello, it is in asciidocfx.com repo

**Comment by cosyman** [comment]
I‘m sorry foy my lack of research,my maven mirror of * cause this problem

**Comment by rahmanusta** [comment]
No problem.
