### ISSUE TITLE
Replace functionality

### ISSUE THREAD

**Issue by mhautman** [asciidocfx/AsciidocFX#76]
Hi guys,

I saw I can search text with ctrl+f but I don't seem to find any info about a "Replace" functionality.

Can you tell me which shortcut this is and if there is none, open a feature request?

Regards,
Morgan

**Comment by rahmanusta** [comment]
Did you try ctrl-h ?

https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts

**Comment by mhautman** [comment]
Ok so ctrl-f and afterwards ctrl-h, Thanks you're doing a grate job! :)

**Comment by rahmanusta** [comment]
Thank you so much @mhautman :)
