### ISSUE TITLE
PDF generation creates footnotes from hyperlinks

### ISSUE THREAD

**Issue by yfain** [asciidocfx/AsciidocFX#77]
During PDF generation all hyprlinks from the text (e.g. http://www.google.com[Google]) are added as footnotes. This should not be happening.

**Comment by rahmanusta** [comment]
This is default behaviour. You are free to change docbook configurations in /conf folder

**Comment by yfain** [comment]
Never saw this before. Neither ascidoc-pdf, nor the Mobi or ePub generators  generate footnotes from links

**Comment by rahmanusta** [comment]
We migrated PDF module from https://github.com/asciidoctor/asciidoctor-fopub. I think this is a choice. You can change docbook PDF generation configurations as you need. Of course, you can make a pull request for that also. We are ready to think changing default behaviours.

**Comment by rahmanusta** [comment]
Hello @yfain . Do you think this issue is resolved?

**Comment by seinecle** [comment]
I need to reopen this issue: which setting should I turn off in the fo-pdf.xsl config file to suppress footnotes for links?
