### ISSUE TITLE
The tooltip Open File should be Open Directory

### ISSUE THREAD

**Issue by yfain** [asciidocfx/AsciidocFX#78]
When I clicked on Open File icon on the toolbar and found my directory, all file names were grayed out. Then I realized that this menu actually allows opening a directory, not a file. The wording in the tooltip should be changed to Open Directory.

**Comment by rahmanusta** [comment]
Hello;

Open file button open single or multiple files. I didnt understand your suggestion. Can you explain it with some graphics? Thanks.

**Comment by yfain** [comment]
After installing AsciidocFX, the tooltip reads "Open File", but it doesn't allow selecting a file - only a directory. When you already have some directory open, the tooltip properly reads "Change Workdir".
To avoid confusion for the new users, the tooltip should always read "Change Workdir".

**Comment by rahmanusta** [comment]
Can share us screenshots, I didnt understend your meant.
