### ISSUE TITLE
 Kindlegen is required

### ISSUE THREAD

**Issue by yfain** [asciidocfx/AsciidocFX#79]
Tried to save the file in the Mobi format, but got a window asking to specify the location of kindlegen executable. Please add a section in AsciidocFX documentation explaining that for generating Mobi the user should install kindlegen from http://www.amazon.com/gp/feature.html?docId=1000765211.

**Comment by rahmanusta** [comment]
That is great suggestion. Thanks!

Can you make a pull request for this update?

Thanks.
