### ISSUE TITLE
Copy HTML doesn't work

### ISSUE THREAD

**Issue by yfain** [asciidocfx/AsciidocFX#80]
Right-clicked in the HTML view and selected Copy Html menu. It doesn't work. The Copy Text menu doesn't work either.

**Comment by ozlerhakan** [comment]
Sorry but I miss one point, did you select an area (text area) before doing these 2 behaviours? Also as far as I know, after doing the "copy html", you should paste the copied content into a Word-like documents.

**Comment by yfain** [comment]
I tried with and without selecting HTML in the right panel. Then tried to paste into various text editors - nothing happened. I'm using Mac OS.

**Comment by ozlerhakan** [comment]
Hmm maybe there is an issue on Mac OS systems, but I have one more question, did you try to past it into a libreoffice or an openoffice document?

**Comment by yfain** [comment]
I selected all text in the right panel and then the menu Copy Html, and then pasted it into MS Word. This time it pasted the text, but not html.

**Comment by ozlerhakan** [comment]
seems like it is working as expected, this is an eligible option for word-like documents, but to be clear I need to call @rahmanusta .

**Comment by rahmanusta** [comment]
I know there is a naming difficuilties; @ozlerhakan @yfain 

* Copy HTML
 * Copies styled html content (Meaningful for word,openoffice, google drive e.g.)
* Copy Text
 * Copies unstyled text content
* Copy Source
 * Copies content plain Html

If you suggest us for naming, we can change it :)

**Comment by rahmanusta** [comment]
Do you think this issue resolved @yfain ?
