### ISSUE TITLE
The :imagesdir: directive is not supported

### ISSUE THREAD

**Issue by yfain** [asciidocfx/AsciidocFX#81]
I have an asciidoc document with images located in a subdirectory images, where all images are stored. It seems that AsciidocFX doesn't support the directive  :imagesdir: and shows broken links in place of images. Here's a fragment of my document (the image fig_1_01.png is not dislayed):

:imagesdir: ./

== Chapter 1. Writing Your First Program

Some text goes here

=== Installing Java on Your Computer

To start programming in Java you need to download Java Development Kit (JDK)

[[FIG1-1]]
.Selecting the Java SE version 
image::images/fig_1_01.png[]

**Comment by ozlerhakan** [comment]
Hi,

Here are the cases that shows how imagesdir works with the mentioned image dirs:

````
:imagesdir: images/

image::subimages/image0001.png[]
image::image001.png[]
````
or you could use as follows:

````
:imagesdir: .

image::images/subimages/image0001.png[]
image::images/image001.png[]
````

or

````
:imagesdir:

image::images/subimages/image0001.png[]
image::images/image001.png[]
````

**Comment by yfain** [comment]
Thank you! 

:imagesdir: . fixed the issue in my file.
