### ISSUE TITLE
Error reporting 

### ISSUE THREAD

**Issue by yfain** [asciidocfx/AsciidocFX#83]
AsciidocFX is a GUI tool, and it would be nice if error reporting would be more user-friendly. For example, exceptions that are happening shouldn't be quietly logged into the log file, but the user should see that the error has occurred with a short message from Exception.getMessage().

The same applies to the information messages. For example, when I started the PDF generation of the 250 page document, the progress bar reached the 100% , I went to check up on the PDF file, which was only 15 bytes long and Adobe Reader would report it corrupted. Then, a minute later I noticed that the size of the PDF file became 22MB and it opened successfully. 

Both errors and information messages should be reported on the GUI, e.g. in the status bar at the bottom of the AsciidocFX window.

**Comment by rahmanusta** [comment]
Yes, we are thinking to add a messagebox for error/info showing. Also, a XML validator for converted docbook content. This suggestion will increase comfort of users.

Thanks for great suggestions.

**Comment by yfain** [comment]
I'd avoid using message boxes - any popups require the user to do an extra click to close it.

**Comment by rahmanusta** [comment]
That is sure. What is your suggestion? How can we do that more user friendly?
Thanks.

**Comment by yfain** [comment]
I'd add an invisible Label  component at the bottom of the window. If there are no errors, the user won't see it. In case of an error make it visible with the error message.  For the informational messages (e.g. the PDF generation is completed) you could do the same + transitions so the message may fade away.

Writing the logs with errors is also useful, but I'd save the log file in the working directory of the user rather than in the log folder of AsiidocFX.

**Comment by rahmanusta** [comment]
Thanks @yfain . We will find the best way of it. @ozlerhakan what do you think to present info and errors in AFX?

**Comment by ozlerhakan** [comment]
Well, we actually decided to use this progress bar, whereas it does not convey the right sense when things still progress more than 20 sec, I think we need to find another option for the progression. :/ 

About the error reporting, I come up with several ideas but I don't know which one is good 

* Another dialog for exceptions as you already did for the shortcut services
* Creating a log file into a working directory if an error presents
* We may make use of the preview section as we can manipulate the HTML dom for displaying errors and info

**Comment by rahmanusta** [comment]
Hello @yfain . We implemented a log viewer for AsciidocFX. I prints logs to a table viewer. You can try version 1.3.7-RC1. Can you try and give feedbacks us ? Thanks
![untitled](https://cloud.githubusercontent.com/assets/1158804/8574107/a3784be4-259d-11e5-9d2b-2601ab6a4401.png)
