### ISSUE TITLE
Are exerpts of source files supported?

### ISSUE THREAD

**Issue by cchet** [asciidocfx/AsciidocFX#84]
I try to include source files and especially exerpts of them but it seems it is not possible.
The includes only work in pdf export and here i see the whole source file and not the exerpts of them.

Do I make somethiong wrong ?
Is it supported by this tool ?

**Comment by rahmanusta** [comment]
Hello, it is not supported for now, but absolutely, we will implement it.

**Comment by rahmanusta** [comment]
@cchet Can you try AsciidocFX v1.3.7-RC1 ?

**Comment by cchet** [comment]
Thanks i will give it a try

**Comment by cchet** [comment]
Thanks works now.

**Comment by rahmanusta** [comment]
:+1:
