### ISSUE TITLE
allow asciidoctor-diagram compatible syntax for uml blocks

### ISSUE THREAD

**Issue by CoolBalance** [asciidocfx/AsciidocFX#85]
Currently AsciidocFX and asciidoctor-diagram use different syntax to introduce a plantuml block. It would be useful if AsciidocFX could handle the asciidoctor-diagram syntax for use-cases where AsciidocFX is used as the editor for creating documents and the output formats are created using a build process (ie Maven).
AsciidocFX syntax is [uml,"file=filename.ext"] where ext might be"png" etc.
asciidoctor-diagram syntaxis [plantuml,filename,ext] where ext might be "png" etc.

**Comment by rahmanusta** [comment]
Hello @CoolBalance . We must do that.

**Comment by ahus1** [comment]
I am looking forward to this change. 

As a temporary workaround I found that the following conditional works for me: AsciidocFX defines the environment 'browser', while my command line asciidoctor doesn't define an environment. This way my diagram is rendered by both AsciidocFX and asciidoctor command line.

    ifdef::env-browser[]
    [uml,file="overview.png"]
    endif::env-browser[]
    ifndef::env-browser[]
    ["plantuml", "overview", "png"]
    endif::env-browser[]

**Comment by rahmanusta** [comment]
@ahus1 Could you reinstall v1.3.8 and try again ? https://github.com/asciidocfx/AsciidocFX/releases

**Comment by ahus1** [comment]
I confirm with works with version 1.3.8 (uploaded 37 (!) minutes ago)

**Comment by rahmanusta** [comment]
Is everything OK @ahus1 ?

**Comment by ahus1** [comment]
@ahus1 says: yes
