### ISSUE TITLE
Specific words cause headers to be indented

### ISSUE THREAD

**Issue by ellipticview** [asciidocfx/AsciidocFX#87]
It seems that AFX has specific keywords that cause headers to be indented in the HTML preview. Example:
```
== qwerty

Normal header as expected

== content

The header above is indented

== header

The header above is also indented
```

It seems that the words "content" or "header" are processed differently. For reference: note that asciidoctor does not have this issue. The PDF rendering in AFX is also fine.

**Comment by rahmanusta** [comment]
We are using default asciidoctor styleshet. Cause of this is https://github.com/asciidocfx/AsciidocFX/blob/master/src/main/resources/public/css/asciidoctor-default.css#L740-L741

You can make a workaround for that like below;

```
[[header-1]]
== header
```

**Comment by ellipticview** [comment]
If I render this document using asciidoctor e.g.:
```
asciidoctor sample.asc
```
then does this also use the default stylesheet? Because this renders correctly.

**Comment by rahmanusta** [comment]
I investigated that asciidoctor adds a default underscore to generated ids. For example asciidoctor adds _header for header title. But we changed this default prefix blank. And id="header" elements has a different css declaration in default asciidoctor stylesheet file.

For that reason, you should try to change id or to change idprefix to different than blank.

**Comment by ellipticview** [comment]
Why did you change the idprefix?

**Comment by rahmanusta** [comment]
I remember that for github anchor style
