### ISSUE TITLE
Mac version has broken cursor movement keyboard shortcuts

### ISSUE THREAD

**Issue by kittylyst** [asciidocfx/AsciidocFX#89]
On OS X 10.9.5, JDK 8u40:

1) Word-left & word-right (usually CMD-LEFTARROW / CMD-RIGHTARROW) does not work.

2) If you attempt to use word-left or word-right, the DOWN arrow stops working (although UP still works).

3) To recover DOWN arrow, have to use mouse to click elsewhere in the editor pane.

**Comment by lefou** [comment]
Same under Linux :-( In most cases that I watched this behaviour, I was switching back from another application (via keyboard). Reason might be some focus stealing.

**Comment by rahmanusta** [comment]
Hello guys, Thanks for feedbacks.

@kittylyst Can you try this pre-release https://github.com/asciidocfx/AsciidocFX/releases/download/v1.3.7-alpha/AsciidocFX_Mac.dmg

I wonder if it will solve the problem

**Comment by rahmanusta** [comment]
@lefou Can you test latest master in Linux environment?

**Comment by kittylyst** [comment]
@rahmanusta Confirmed fixed for me on the pre-release.

**Comment by rahmanusta** [comment]
That is great! Thanks @kittylyst

**Comment by lefou** [comment]
Looks like the issue is gone. Thanks!

**Comment by rahmanusta** [comment]
Thank you @lefou  and @kittylyst . You can use/try AsciidocFX version 1.3.7-RC1.
