### ISSUE TITLE
Only 3 levels of header are supported

### ISSUE THREAD

**Issue by gbjbaanb** [asciidocfx/AsciidocFX#91]
A title with 4 or 5 equals markers either side do not get generated as headings, so:

==== heading ====

does not get generated.

The ASCIIDoc spec says:

    11.2. One line titles

    One line titles consist of a single line delimited on either side by one or more equals characters (the number of equals characters corresponds to the section level minus one). Here are some examples:

    = Document Title (level 0) =
    == Section title (level 1) ==
    === Section title (level 2) ===
    ==== Section title (level 3) ====
    ===== Section title (level 4) =====

**Comment by rahmanusta** [comment]
You need to add something after headings space, word e.t.c. For example, when you add linebreak after headings, headings are generating correctly;

```
= Document Title (level 0) =

== Section title (level 1) ==

=== Section title (level 2) ===

==== Section title (level 3) ====

===== Section title (level 4) =====
```

**Comment by gbjbaanb** [comment]
Ah no, it was my own fault - an extra * in a comment block before my titles was causing these headings to be inside the block. I had tables that were still being generated correctly however which is what confused me. Sorry about that.
