### ISSUE TITLE
Preview (and rendering) of HTML cells does not seem to insert <br/> elements

### ISSUE THREAD

**Issue by takapa** [asciidocfx/AsciidocFX#92]
Newlines within table cells do not seem to render in the preview panel. According to the asciidoc documentation, two newlines in a table cell contents area implies a new paragraph.

![asciidoc](https://cloud.githubusercontent.com/assets/201870/8587963/ea38c64a-25fb-11e5-9c39-58a2a55d6605.png)

**Comment by ozlerhakan** [comment]
Hi @takapa ,

I am only thinking of putting a plus '+' in each sentences as below:

```
[cols=",^v",options="header"]
|===
|Default paragraphs |Centered verses
2*|Per id. + 
Consul *necessitatibus* per id, consetetur, eu pro everti postulant jomero verar ea mea, qui.  +
Consul *necessitatibus* per is, consetetur, eu pro everti postulant homero verar ea mea, qui.
|===
````
Using the +, you put each sentence on a separate line, since we are dealing with Asciidoctor.

**Comment by takapa** [comment]
Putting space & plus  " +" at the end of the end of each line does indeed work, but newlines should *also* work as per the example in the image attached in the original post. 

For reference, the following website renders the following asciidoc correctly.

https://asciidoclive.com/

```
[cols=",^v",options="header"]
|===
|Default paragraphs |Centered verses
2*|Per id.

Consul *necessitatibus* per id, consetetur, eu pro everti postulant jomero verar ea mea, qui.

Consul *necessitatibus* per is, consetetur, eu pro everti postulant homero verar ea mea, qui.
|===
```

**Comment by ozlerhakan** [comment]
Ah, so you need to use another attribute called :hardbreaks: for this purpose in **Asciidoctor** . Just put it to the header of your document:

```
:hardbreaks: 


[cols=",^v",options="header"]
|===
|Default paragraphs |Centered verses
2*|Per id.
Consul *necessitatibus* per id, consetetur, eu pro everti postulant jomero verar ea mea, qui.
Consul *necessitatibus* per is, consetetur, eu pro everti postulant homero verar ea mea, qui.
|===
```

I hope that helps.

**Comment by takapa** [comment]
I confirm this works.

It now appears that it was a difference between asciidoc and asciidoctor, something that I wasn't aware of until today!

Thank you for isolating the solution.

**Comment by ozlerhakan** [comment]
np @takapa , enjoy using AFX!
