### ISSUE TITLE
Writing five colons in AsciiDocFX crashes/hangs the program ":::::"

### ISSUE THREAD

**Issue by takapa** [asciidocfx/AsciidocFX#94]
Writing five colons in AsciiDocFX crashes/hangs the program. I'm sure this is something to do with the underlying libraries, but it may be worth scanning for this pattern to avoid killing the UI.

":::::"

**Comment by rahmanusta** [comment]
It is so much interesting :) @mojavelinux , what do you think about this issue?

**Comment by mojavelinux** [comment]
That's definitely a bug in Asciidoctor.js. It seems like the regular expression for a dlist is matching differently in the JavaScript environment than it does in the Ruby environment. As a result, it ends up going into an infinite loop. Could you file this against Asciidoctor core so we can investigate? Mention in the title that it affects Asciidoctor.js, but the change has to happen to core.

**Comment by mojavelinux** [comment]
Although you could put a temporary safeguard into AsciidocFX, in general we should assume that the underlying libraries don't crash. Otherwise, you end up playing whake-a-mode from the UI code, which is not a good direction.

**Comment by takapa** [comment]
Glad it's a "proper" bug. Took me hours to isolate the source of the crash to this partiular ascii pattern :)

**Comment by mojavelinux** [comment]
Thanks for the research @takapa!! You zeroed us right in on the fix.

Upon further review, it appears that this is a transpile error in Opal. It is supposed to be checking if a value is nil, but the logic gets confused and it always returns true. I can rewrite it in core to workaround the issue, but we may have also found a bug in Opal as well.

**Comment by mojavelinux** [comment]
Aha, I see what it is. We are using a do...while loop and Opal is translating that into a regular while loop. The first iteration of the loop never runs, therefore we get an infinitely loop.

**Comment by mojavelinux** [comment]
Yep, that fixed it. I think we can update Asciidoctor.js with a patch without having to change core. We may still change core...or we'll try to fix the problem in Opal. Either way, we'll need an Asciidoctor.js 1.5.2.1 release to address it.

**Comment by takapa** [comment]
Did this affect the github asciidoc rendering?

I wanted to try it out, but was fearful I'd break my account if I saved a file in it with the five colons of death.

**Comment by mojavelinux** [comment]
Nope, this is purely an Asciidoctor.js issue. As I mentioned, when Asciidoctor.js is made, the `do...while` loop turns into a `while` loop and changes the logic.

I'll follow-up shortly with steps to get it applied to Asciidoctor.js. In the meantime, I've found a way to use a regular while loop in core to make this patch unnecessary in the future (turns out, we didn't need the `do...while` anyway).

**Comment by rahmanusta** [comment]
Thank you @takapa and @mojavelinux . Can we think it is as an Opal bug ? Which version of Asciidoctor.js will be OK for this issue ?

**Comment by mojavelinux** [comment]
This is indeed an Opal bug, but we're able to work around it without changing Opal. It's now fixed in master, which means it will be available in 1.5.3 unless we decide we need a release sooner. I'm working to get 1.5.3 out this summer.

**Comment by rahmanusta** [comment]
Thank you @mojavelinux . I will use directly Asciidoctor master. :+1:

**Comment by rahmanusta** [comment]
@takapa Please try https://github.com/asciidocfx/AsciidocFX/releases

**Comment by takapa** [comment]
Confirmed fixed in RC3.
