### ISSUE TITLE
Feature Request : Add toggle to enable/disable preview calculation

### ISSUE THREAD

**Issue by takapa** [asciidocfx/AsciidocFX#95]
AsciiDocFX currently seems to use a timer based on the last edit to the document, and then fire a preview update - *even if the preview window is not visible*.

I propose a toggle switch at the top of either the editor window, or the explorer window, that disables rendering of the document upon document change.

The reason for this is if you are editing a larger sized document, then rendering can take several seconds, and whilst the timer mechanic is fine for a short sequential edit, any hesitation locks up the UI for several seconds until the render is complete. Meaning that I'm unable to navigate the document even with cursor keys whilst it is calculating the preview. 

For 90% of the files I need to edit, this is not a problem, but there are some particularly large files that sometimes I need to edit, and I don't want to can't break down into smaller units. In these cases, not being able to toggle off the preview render really slows down editing.

**Comment by rahmanusta** [comment]
+1

**Comment by rahmanusta** [comment]
@takapa We implemented this feature in master. This feature will be available in release v1.3.7. Thanks for your support to AsciidocFX project!

**Comment by rahmanusta** [comment]
@takapa , Please try RC2 https://github.com/asciidocfx/AsciidocFX/releases

You can toggle rendering in preview panel by right-click menu.

**Comment by takapa** [comment]
Tested working in RC3.
