### ISSUE TITLE
[source, json] split json into two code blocks

### ISSUE THREAD

**Issue by cchet** [asciidocfx/AsciidocFX#96]
A json file included via 
```
[source,json]
include::../../source/composer/composer.json[]
```
produces the following output
![bug_asciidoc_split_json](https://cloud.githubusercontent.com/assets/2004943/8638784/e2f597ec-28c5-11e5-8716-2e2df79778da.PNG)

**Comment by rahmanusta** [comment]
@cchet Did you try like below?;

```asciidoc
[source,json]
----
include::../../source/composer/composer.json[]
----
```

**Comment by cchet** [comment]
Yes I did, then the '---' are added to the top and the bottom of the rendered code blocks but still the code blocks are split.
I am currently at work, but when I'm at home I will provide an screenshot.
I had this one in the first place but removed them before I submitted this issue.

**Comment by cchet** [comment]
Ok, you are right, it works that way.
Seems I was mislead by myself.

Thanks
