### ISSUE TITLE
[RFE] Provide AsciiDoc real time validation

### ISSUE THREAD

**Issue by jaredmorgs** [asciidocfx/AsciidocFX#97]
I know you can implement validators like https://atom.io/packages/redpen in Atom. The non-atom version of RedPen is compatible with continuous integration services like Travis, so I wonder if the validator (or something like it) could be added to the app to close the loop for new users.

RedPen has recently added AsciiDoc support along with markdown support. It would be a great offering for the app to offer real time validation.

**Comment by rahmanusta** [comment]
Thank you @jaredmorgs .I had never seen redpen yet. I'll try it. I think,  we can integrate it in further releases.
