### ISSUE TITLE
Saving a New Document from the `new*` tab only saves up to the point where you saved the doc

### ISSUE THREAD

**Issue by jaredmorgs** [asciidocfx/AsciidocFX#98]
I created a new document this morning, using the new* tab, clicked the `Save` button, and saved it using a `filename.adoc` pattern to a local directory.

When I tried to reopen the file again to show a colleague, all the text was gone from the file. It's like the contents of the file was never saved even though I was regularly clicking the save button as I was working.

I did not see any obvious reasons why this would have happened while I was authoring the document. Did not notice any errors or warnings that caught my attention.

Trying to replicate the bug, I typed some markup into the empty doc and noted that the asterix indicating a change to the document began to display. In hindsight, I didn't see this marker on the tab when I was typing out my document after saving it.

I think this is the root cause of the issue: When you initially save the document from the `new*` tab, the app doesn't allow any further changes to be saved until you close the document and reload it. 

This issue may not have manifested before because folks might have been opening up existing docs.

**Comment by rahmanusta** [comment]
Hello @jaredmorgs ; Sorry for this bug. After resolving it I will push a hotfix with RC2

**Comment by jaredmorgs** [comment]
No problem. It also happens when you rename a file in the app, which I
discovered today. I was aware of the bug so no data lost. 😉

On Wed, 15 Jul 2015 17:16 Rahman Usta <notifications@github.com> wrote:

> Hello @jaredmorgs <https://github.com/jaredmorgs> ; Sorry for this bug.
> After resolving it I will push a hotfix with RC2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidocfx/AsciidocFX/issues/98#issuecomment-121512530>
> .
>
-- 

Sent from Mobile.

**Comment by rahmanusta** [comment]
Thank you @jaredmorgs . This bug is fixed at master. I'm thinking to release RC2 today or tomorrow. Thanks for your support to AsciidocFX!

**Comment by jaredmorgs** [comment]
Great work. Let me know when it's out and I'll test and verify.

On Thu, 16 Jul 2015 07:03 Rahman Usta <notifications@github.com> wrote:

> Thank you @jaredmorgs <https://github.com/jaredmorgs> . This bug is fixed
> at master. I'm thinking to release RC2 today or tomorrow. Thanks for your
> support to AsciidocFX!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidocfx/AsciidocFX/issues/98#issuecomment-121746570>
> .
>
-- 

Sent from Mobile.

**Comment by rahmanusta** [comment]
@jaredmorgs , Please try RC2  https://github.com/asciidocfx/AsciidocFX/releases

**Comment by jaredmorgs** [comment]
Hey there Rahman

I just tested RC2. The issue with saving has now been fixed. Thanks for
fixing it so rapidly.

I've been showing folks how you can copy HTML into an AsciidocFX window and
it instantly converts it to AsciiDoc markup. They can't believe how well it
works. Even for complex HTML docs. I'll be doing a quick demo of it
tomorrow and recording it for folks.

On Thu, 16 Jul 2015 at 18:39 Rahman Usta <notifications@github.com> wrote:

> @jaredmorgs <https://github.com/jaredmorgs> , Please try RC2
> https://github.com/asciidocfx/AsciidocFX/releases
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidocfx/AsciidocFX/issues/98#issuecomment-121879607>
> .
>
-- 

Sent from Mobile.

**Comment by rahmanusta** [comment]
Hey Jared;

Thank you so much for reporting this issue. I'm glad to hear that your folks liked AsciidocFX. Demo recording for AsciidocFX will be great! Please share it with me!
