### ISSUE TITLE
reloading documents that have changed externally

### ISSUE THREAD

**Issue by jechlin** [asciidocfx/AsciidocFX#99]
Eg I often use a different editor, or switch git branches. At the moment I have to close and reopen.

Also "Save" causes a problem, because you may have unsaved edits when the file changes. I think it should "save" on window deactivation... most programs I use these days , eg IDEA, Google Docs, don't have this concept of "saving", which is a bit anachronistic.

If it was an intellij idea plugin that would solve this issue...

**Comment by rahmanusta** [comment]
reloading and external change detection feature pushed to master as your suggestion @jechlin . Thank for your suggestion!

Saving automatically also may be good feature for AsciidocFX. Btw, someone can develop a plugin for intellij idea, but you know this is a different product :)

**Comment by jechlin-test** [comment]
Thanks a lot @rahmanusta.

I might have a go myself at making it an IDEA plugin... when I get some time. I just think you'd get so much for free, eg great editor, dark theme, tree view for outline, dockable resizable windows etc. But if you're not an IDEA user I can see that this wouldn't have the same appeal.

**Comment by rahmanusta** [comment]
I'm an IDEA user but IDEA is a code editor.

**Comment by rahmanusta** [comment]
@jechlin-test , please try RC2 Please try https://github.com/asciidocfx/AsciidocFX/releases

**Comment by jechlin** [comment]
Sorry, I used my test user account before.

> I'm an IDEA user but IDEA is a code editor.

I hear you, but prior to using AsciidocFX (and thanks again for it), I was relatively happy writing adoc in IDEA. To me adoc is not that far removed from code anyway, in fact I read some quote that writing adoc was like "coding documentation". 

Besides, I also use IDEA for writing html and various other things that aren't code. It might not be for everyone, but for me not having to leave IDEA would be ideal, I particularly find the white background of other tools very jarring after using Darcula for years. Anyway, like I say, happy to have a go at it myself.

Thanks for the RC, will update.
